//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.CreditoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditoService.ICreditoService")]
    public interface ICreditoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetOfertasActivas", ReplyAction="http://tempuri.org/ICreditoService/GetOfertasActivasResponse")]
        FGA.Models.Creditos_Ofertas[] GetOfertasActivas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetOfertasActivas", ReplyAction="http://tempuri.org/ICreditoService/GetOfertasActivasResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_Ofertas[]> GetOfertasActivasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetOfertaById", ReplyAction="http://tempuri.org/ICreditoService/GetOfertaByIdResponse")]
        FGA.Models.Creditos_Ofertas GetOfertaById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetOfertaById", ReplyAction="http://tempuri.org/ICreditoService/GetOfertaByIdResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_Ofertas> GetOfertaByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/PublicarOferta", ReplyAction="http://tempuri.org/ICreditoService/PublicarOfertaResponse")]
        void PublicarOferta(FGA.Models.Creditos_Ofertas oferta, int[] requisitosIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/PublicarOferta", ReplyAction="http://tempuri.org/ICreditoService/PublicarOfertaResponse")]
        System.Threading.Tasks.Task PublicarOfertaAsync(FGA.Models.Creditos_Ofertas oferta, int[] requisitosIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/InactivarOferta", ReplyAction="http://tempuri.org/ICreditoService/InactivarOfertaResponse")]
        void InactivarOferta(int id, int usuarioModificaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/InactivarOferta", ReplyAction="http://tempuri.org/ICreditoService/InactivarOfertaResponse")]
        System.Threading.Tasks.Task InactivarOfertaAsync(int id, int usuarioModificaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetRequisitosOferta", ReplyAction="http://tempuri.org/ICreditoService/GetRequisitosOfertaResponse")]
        FGA.Models.Creditos_OfertaRequisitos[] GetRequisitosOferta(int ofertaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetRequisitosOferta", ReplyAction="http://tempuri.org/ICreditoService/GetRequisitosOfertaResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_OfertaRequisitos[]> GetRequisitosOfertaAsync(int ofertaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetSolicitudesPorEntidad", ReplyAction="http://tempuri.org/ICreditoService/GetSolicitudesPorEntidadResponse")]
        FGA.Models.Creditos_Solicitudes[] GetSolicitudesPorEntidad(string entidadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetSolicitudesPorEntidad", ReplyAction="http://tempuri.org/ICreditoService/GetSolicitudesPorEntidadResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_Solicitudes[]> GetSolicitudesPorEntidadAsync(string entidadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetSolicitudesRecibidas", ReplyAction="http://tempuri.org/ICreditoService/GetSolicitudesRecibidasResponse")]
        FGA.Models.Creditos_Solicitudes[] GetSolicitudesRecibidas(string entidadOferenteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetSolicitudesRecibidas", ReplyAction="http://tempuri.org/ICreditoService/GetSolicitudesRecibidasResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_Solicitudes[]> GetSolicitudesRecibidasAsync(string entidadOferenteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/CrearSolicitud", ReplyAction="http://tempuri.org/ICreditoService/CrearSolicitudResponse")]
        void CrearSolicitud(FGA.Models.Creditos_Solicitudes solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/CrearSolicitud", ReplyAction="http://tempuri.org/ICreditoService/CrearSolicitudResponse")]
        System.Threading.Tasks.Task CrearSolicitudAsync(FGA.Models.Creditos_Solicitudes solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ResolverSolicitud", ReplyAction="http://tempuri.org/ICreditoService/ResolverSolicitudResponse")]
        void ResolverSolicitud(int solicitudId, int estadoId, int usuarioId, string motivoRechazo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ResolverSolicitud", ReplyAction="http://tempuri.org/ICreditoService/ResolverSolicitudResponse")]
        System.Threading.Tasks.Task ResolverSolicitudAsync(int solicitudId, int estadoId, int usuarioId, string motivoRechazo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/CargarDocumento", ReplyAction="http://tempuri.org/ICreditoService/CargarDocumentoResponse")]
        void CargarDocumento(FGA.Models.Creditos_Documentos documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/CargarDocumento", ReplyAction="http://tempuri.org/ICreditoService/CargarDocumentoResponse")]
        System.Threading.Tasks.Task CargarDocumentoAsync(FGA.Models.Creditos_Documentos documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ValidarDocumento", ReplyAction="http://tempuri.org/ICreditoService/ValidarDocumentoResponse")]
        void ValidarDocumento(int documentoId, bool esValido, int usuarioSacId, string comentarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/ValidarDocumento", ReplyAction="http://tempuri.org/ICreditoService/ValidarDocumentoResponse")]
        System.Threading.Tasks.Task ValidarDocumentoAsync(int documentoId, bool esValido, int usuarioSacId, string comentarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetDocumentosPorSolicitud", ReplyAction="http://tempuri.org/ICreditoService/GetDocumentosPorSolicitudResponse")]
        FGA.Models.Creditos_Documentos[] GetDocumentosPorSolicitud(int solicitudId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetDocumentosPorSolicitud", ReplyAction="http://tempuri.org/ICreditoService/GetDocumentosPorSolicitudResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_Documentos[]> GetDocumentosPorSolicitudAsync(int solicitudId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetTiposDocumento", ReplyAction="http://tempuri.org/ICreditoService/GetTiposDocumentoResponse")]
        FGA.Models.Creditos_TipoDocumento[] GetTiposDocumento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetTiposDocumento", ReplyAction="http://tempuri.org/ICreditoService/GetTiposDocumentoResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_TipoDocumento[]> GetTiposDocumentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetMonedas", ReplyAction="http://tempuri.org/ICreditoService/GetMonedasResponse")]
        FGA.Models.Creditos_Moneda[] GetMonedas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditoService/GetMonedas", ReplyAction="http://tempuri.org/ICreditoService/GetMonedasResponse")]
        System.Threading.Tasks.Task<FGA.Models.Creditos_Moneda[]> GetMonedasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditoServiceChannel : FGA_En_Linea.CreditoService.ICreditoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditoServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.CreditoService.ICreditoService>, FGA_En_Linea.CreditoService.ICreditoService {
        
        public CreditoServiceClient() {
        }
        
        public CreditoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Creditos_Ofertas[] GetOfertasActivas() {
            return base.Channel.GetOfertasActivas();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_Ofertas[]> GetOfertasActivasAsync() {
            return base.Channel.GetOfertasActivasAsync();
        }
        
        public FGA.Models.Creditos_Ofertas GetOfertaById(int id) {
            return base.Channel.GetOfertaById(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_Ofertas> GetOfertaByIdAsync(int id) {
            return base.Channel.GetOfertaByIdAsync(id);
        }
        
        public void PublicarOferta(FGA.Models.Creditos_Ofertas oferta, int[] requisitosIds) {
            base.Channel.PublicarOferta(oferta, requisitosIds);
        }
        
        public System.Threading.Tasks.Task PublicarOfertaAsync(FGA.Models.Creditos_Ofertas oferta, int[] requisitosIds) {
            return base.Channel.PublicarOfertaAsync(oferta, requisitosIds);
        }
        
        public void InactivarOferta(int id, int usuarioModificaId) {
            base.Channel.InactivarOferta(id, usuarioModificaId);
        }
        
        public System.Threading.Tasks.Task InactivarOfertaAsync(int id, int usuarioModificaId) {
            return base.Channel.InactivarOfertaAsync(id, usuarioModificaId);
        }
        
        public FGA.Models.Creditos_OfertaRequisitos[] GetRequisitosOferta(int ofertaId) {
            return base.Channel.GetRequisitosOferta(ofertaId);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_OfertaRequisitos[]> GetRequisitosOfertaAsync(int ofertaId) {
            return base.Channel.GetRequisitosOfertaAsync(ofertaId);
        }
        
        public FGA.Models.Creditos_Solicitudes[] GetSolicitudesPorEntidad(string entidadId) {
            return base.Channel.GetSolicitudesPorEntidad(entidadId);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_Solicitudes[]> GetSolicitudesPorEntidadAsync(string entidadId) {
            return base.Channel.GetSolicitudesPorEntidadAsync(entidadId);
        }
        
        public FGA.Models.Creditos_Solicitudes[] GetSolicitudesRecibidas(string entidadOferenteId) {
            return base.Channel.GetSolicitudesRecibidas(entidadOferenteId);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_Solicitudes[]> GetSolicitudesRecibidasAsync(string entidadOferenteId) {
            return base.Channel.GetSolicitudesRecibidasAsync(entidadOferenteId);
        }
        
        public void CrearSolicitud(FGA.Models.Creditos_Solicitudes solicitud) {
            base.Channel.CrearSolicitud(solicitud);
        }
        
        public System.Threading.Tasks.Task CrearSolicitudAsync(FGA.Models.Creditos_Solicitudes solicitud) {
            return base.Channel.CrearSolicitudAsync(solicitud);
        }
        
        public void ResolverSolicitud(int solicitudId, int estadoId, int usuarioId, string motivoRechazo) {
            base.Channel.ResolverSolicitud(solicitudId, estadoId, usuarioId, motivoRechazo);
        }
        
        public System.Threading.Tasks.Task ResolverSolicitudAsync(int solicitudId, int estadoId, int usuarioId, string motivoRechazo) {
            return base.Channel.ResolverSolicitudAsync(solicitudId, estadoId, usuarioId, motivoRechazo);
        }
        
        public void CargarDocumento(FGA.Models.Creditos_Documentos documento) {
            base.Channel.CargarDocumento(documento);
        }
        
        public System.Threading.Tasks.Task CargarDocumentoAsync(FGA.Models.Creditos_Documentos documento) {
            return base.Channel.CargarDocumentoAsync(documento);
        }
        
        public void ValidarDocumento(int documentoId, bool esValido, int usuarioSacId, string comentarios) {
            base.Channel.ValidarDocumento(documentoId, esValido, usuarioSacId, comentarios);
        }
        
        public System.Threading.Tasks.Task ValidarDocumentoAsync(int documentoId, bool esValido, int usuarioSacId, string comentarios) {
            return base.Channel.ValidarDocumentoAsync(documentoId, esValido, usuarioSacId, comentarios);
        }
        
        public FGA.Models.Creditos_Documentos[] GetDocumentosPorSolicitud(int solicitudId) {
            return base.Channel.GetDocumentosPorSolicitud(solicitudId);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_Documentos[]> GetDocumentosPorSolicitudAsync(int solicitudId) {
            return base.Channel.GetDocumentosPorSolicitudAsync(solicitudId);
        }
        
        public FGA.Models.Creditos_TipoDocumento[] GetTiposDocumento() {
            return base.Channel.GetTiposDocumento();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_TipoDocumento[]> GetTiposDocumentoAsync() {
            return base.Channel.GetTiposDocumentoAsync();
        }
        
        public FGA.Models.Creditos_Moneda[] GetMonedas() {
            return base.Channel.GetMonedas();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Creditos_Moneda[]> GetMonedasAsync() {
            return base.Channel.GetMonedasAsync();
        }
    }
}
