//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.CatalogoCuentaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogoCuentaService.ICatalogoCuenta")]
    public interface ICatalogoCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/GetAll", ReplyAction="http://tempuri.org/ICatalogoCuenta/GetAllResponse")]
        FGA.Models.CatalogoCuenta[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/GetAll", ReplyAction="http://tempuri.org/ICatalogoCuenta/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.CatalogoCuenta[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/GetPage", ReplyAction="http://tempuri.org/ICatalogoCuenta/GetPageResponse")]
        FGA_En_Linea.CatalogoCuentaService.GetPageResponse GetPage(FGA_En_Linea.CatalogoCuentaService.GetPageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/GetPage", ReplyAction="http://tempuri.org/ICatalogoCuenta/GetPageResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.CatalogoCuentaService.GetPageResponse> GetPageAsync(FGA_En_Linea.CatalogoCuentaService.GetPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Get", ReplyAction="http://tempuri.org/ICatalogoCuenta/GetResponse")]
        FGA.Models.CatalogoCuenta Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Get", ReplyAction="http://tempuri.org/ICatalogoCuenta/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.CatalogoCuenta> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Add", ReplyAction="http://tempuri.org/ICatalogoCuenta/AddResponse")]
        FGA_En_Linea.CatalogoCuentaService.AddResponse Add(FGA_En_Linea.CatalogoCuentaService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Add", ReplyAction="http://tempuri.org/ICatalogoCuenta/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.CatalogoCuentaService.AddResponse> AddAsync(FGA_En_Linea.CatalogoCuentaService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Update", ReplyAction="http://tempuri.org/ICatalogoCuenta/UpdateResponse")]
        void Update(FGA.Models.CatalogoCuenta entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Update", ReplyAction="http://tempuri.org/ICatalogoCuenta/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.CatalogoCuenta entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Delete", ReplyAction="http://tempuri.org/ICatalogoCuenta/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoCuenta/Delete", ReplyAction="http://tempuri.org/ICatalogoCuenta/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int records;
        
        public GetPageRequest() {
        }
        
        public GetPageRequest(int pageNumber, int size, string filter, int records) {
            this.pageNumber = pageNumber;
            this.size = size;
            this.filter = filter;
            this.records = records;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.CatalogoCuenta[] GetPageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int records;
        
        public GetPageResponse() {
        }
        
        public GetPageResponse(FGA.Models.CatalogoCuenta[] GetPageResult, int records) {
            this.GetPageResult = GetPageResult;
            this.records = records;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.CatalogoCuenta entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.CatalogoCuenta entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.CatalogoCuenta entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.CatalogoCuenta entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoCuentaChannel : FGA_En_Linea.CatalogoCuentaService.ICatalogoCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoCuentaClient : System.ServiceModel.ClientBase<FGA_En_Linea.CatalogoCuentaService.ICatalogoCuenta>, FGA_En_Linea.CatalogoCuentaService.ICatalogoCuenta {
        
        public CatalogoCuentaClient() {
        }
        
        public CatalogoCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.CatalogoCuenta[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.CatalogoCuenta[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.CatalogoCuentaService.GetPageResponse FGA_En_Linea.CatalogoCuentaService.ICatalogoCuenta.GetPage(FGA_En_Linea.CatalogoCuentaService.GetPageRequest request) {
            return base.Channel.GetPage(request);
        }
        
        public FGA.Models.CatalogoCuenta[] GetPage(int pageNumber, int size, string filter, ref int records) {
            FGA_En_Linea.CatalogoCuentaService.GetPageRequest inValue = new FGA_En_Linea.CatalogoCuentaService.GetPageRequest();
            inValue.pageNumber = pageNumber;
            inValue.size = size;
            inValue.filter = filter;
            inValue.records = records;
            FGA_En_Linea.CatalogoCuentaService.GetPageResponse retVal = ((FGA_En_Linea.CatalogoCuentaService.ICatalogoCuenta)(this)).GetPage(inValue);
            records = retVal.records;
            return retVal.GetPageResult;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.CatalogoCuentaService.GetPageResponse> GetPageAsync(FGA_En_Linea.CatalogoCuentaService.GetPageRequest request) {
            return base.Channel.GetPageAsync(request);
        }
        
        public FGA.Models.CatalogoCuenta Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.CatalogoCuenta> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.CatalogoCuentaService.AddResponse FGA_En_Linea.CatalogoCuentaService.ICatalogoCuenta.Add(FGA_En_Linea.CatalogoCuentaService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.CatalogoCuenta entity) {
            FGA_En_Linea.CatalogoCuentaService.AddRequest inValue = new FGA_En_Linea.CatalogoCuentaService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.CatalogoCuentaService.AddResponse retVal = ((FGA_En_Linea.CatalogoCuentaService.ICatalogoCuenta)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.CatalogoCuentaService.AddResponse> AddAsync(FGA_En_Linea.CatalogoCuentaService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.CatalogoCuenta entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.CatalogoCuenta entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
