//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.ParametrosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParametrosService.IParametrosService")]
    public interface IParametrosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/GetAll", ReplyAction="http://tempuri.org/IParametrosService/GetAllResponse")]
        FGA.Models.Parametros[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/GetAll", ReplyAction="http://tempuri.org/IParametrosService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Parametros[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Get", ReplyAction="http://tempuri.org/IParametrosService/GetResponse")]
        FGA.Models.Parametros Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Get", ReplyAction="http://tempuri.org/IParametrosService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Parametros> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Add", ReplyAction="http://tempuri.org/IParametrosService/AddResponse")]
        FGA_En_Linea.ParametrosService.AddResponse Add(FGA_En_Linea.ParametrosService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Add", ReplyAction="http://tempuri.org/IParametrosService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.ParametrosService.AddResponse> AddAsync(FGA_En_Linea.ParametrosService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Update", ReplyAction="http://tempuri.org/IParametrosService/UpdateResponse")]
        void Update(FGA.Models.Parametros entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Update", ReplyAction="http://tempuri.org/IParametrosService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Parametros entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Delete", ReplyAction="http://tempuri.org/IParametrosService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParametrosService/Delete", ReplyAction="http://tempuri.org/IParametrosService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Parametros entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Parametros entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Parametros entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Parametros entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParametrosServiceChannel : FGA_En_Linea.ParametrosService.IParametrosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParametrosServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.ParametrosService.IParametrosService>, FGA_En_Linea.ParametrosService.IParametrosService {
        
        public ParametrosServiceClient() {
        }
        
        public ParametrosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParametrosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametrosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParametrosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Parametros[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Parametros[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Parametros Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Parametros> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.ParametrosService.AddResponse FGA_En_Linea.ParametrosService.IParametrosService.Add(FGA_En_Linea.ParametrosService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Parametros entity) {
            FGA_En_Linea.ParametrosService.AddRequest inValue = new FGA_En_Linea.ParametrosService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.ParametrosService.AddResponse retVal = ((FGA_En_Linea.ParametrosService.IParametrosService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.ParametrosService.AddResponse> AddAsync(FGA_En_Linea.ParametrosService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Parametros entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Parametros entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
