//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.NoticiaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoticiaService.IServiceOf_Noticia")]
    public interface IServiceOf_Noticia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Noticia/GetAllResponse")]
        FGA.Models.Noticia[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Noticia/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Noticia[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Get", ReplyAction="http://tempuri.org/IServiceOf_Noticia/GetResponse")]
        FGA.Models.Noticia Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Get", ReplyAction="http://tempuri.org/IServiceOf_Noticia/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Noticia> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Add", ReplyAction="http://tempuri.org/IServiceOf_Noticia/AddResponse")]
        FGA_En_Linea.NoticiaService.AddResponse Add(FGA_En_Linea.NoticiaService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Add", ReplyAction="http://tempuri.org/IServiceOf_Noticia/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.NoticiaService.AddResponse> AddAsync(FGA_En_Linea.NoticiaService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Update", ReplyAction="http://tempuri.org/IServiceOf_Noticia/UpdateResponse")]
        void Update(FGA.Models.Noticia entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Update", ReplyAction="http://tempuri.org/IServiceOf_Noticia/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Noticia entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Delete", ReplyAction="http://tempuri.org/IServiceOf_Noticia/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Noticia/Delete", ReplyAction="http://tempuri.org/IServiceOf_Noticia/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Noticia entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Noticia entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Noticia entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Noticia entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_NoticiaChannel : FGA_En_Linea.NoticiaService.IServiceOf_Noticia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_NoticiaClient : System.ServiceModel.ClientBase<FGA_En_Linea.NoticiaService.IServiceOf_Noticia>, FGA_En_Linea.NoticiaService.IServiceOf_Noticia {
        
        public ServiceOf_NoticiaClient() {
        }
        
        public ServiceOf_NoticiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_NoticiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_NoticiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_NoticiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Noticia[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Noticia[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Noticia Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Noticia> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.NoticiaService.AddResponse FGA_En_Linea.NoticiaService.IServiceOf_Noticia.Add(FGA_En_Linea.NoticiaService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Noticia entity) {
            FGA_En_Linea.NoticiaService.AddRequest inValue = new FGA_En_Linea.NoticiaService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.NoticiaService.AddResponse retVal = ((FGA_En_Linea.NoticiaService.IServiceOf_Noticia)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.NoticiaService.AddResponse> AddAsync(FGA_En_Linea.NoticiaService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Noticia entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Noticia entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
