//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.PerfilEntidadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerfilEntidadService.IServiceOf_PerfilEntidad")]
    public interface IServiceOf_PerfilEntidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/GetAll", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/GetAllResponse")]
        FGA.Models.PerfilEntidad[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/GetAll", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.PerfilEntidad[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Get", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/GetResponse")]
        FGA.Models.PerfilEntidad Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Get", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.PerfilEntidad> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Add", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/AddResponse")]
        FGA_En_Linea.PerfilEntidadService.AddResponse Add(FGA_En_Linea.PerfilEntidadService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Add", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.PerfilEntidadService.AddResponse> AddAsync(FGA_En_Linea.PerfilEntidadService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Update", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/UpdateResponse")]
        void Update(FGA.Models.PerfilEntidad entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Update", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.PerfilEntidad entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Delete", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_PerfilEntidad/Delete", ReplyAction="http://tempuri.org/IServiceOf_PerfilEntidad/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.PerfilEntidad entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.PerfilEntidad entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.PerfilEntidad entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.PerfilEntidad entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_PerfilEntidadChannel : FGA_En_Linea.PerfilEntidadService.IServiceOf_PerfilEntidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_PerfilEntidadClient : System.ServiceModel.ClientBase<FGA_En_Linea.PerfilEntidadService.IServiceOf_PerfilEntidad>, FGA_En_Linea.PerfilEntidadService.IServiceOf_PerfilEntidad {
        
        public ServiceOf_PerfilEntidadClient() {
        }
        
        public ServiceOf_PerfilEntidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_PerfilEntidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_PerfilEntidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_PerfilEntidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.PerfilEntidad[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.PerfilEntidad[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.PerfilEntidad Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.PerfilEntidad> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.PerfilEntidadService.AddResponse FGA_En_Linea.PerfilEntidadService.IServiceOf_PerfilEntidad.Add(FGA_En_Linea.PerfilEntidadService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.PerfilEntidad entity) {
            FGA_En_Linea.PerfilEntidadService.AddRequest inValue = new FGA_En_Linea.PerfilEntidadService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.PerfilEntidadService.AddResponse retVal = ((FGA_En_Linea.PerfilEntidadService.IServiceOf_PerfilEntidad)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.PerfilEntidadService.AddResponse> AddAsync(FGA_En_Linea.PerfilEntidadService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.PerfilEntidad entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.PerfilEntidad entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
