//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.Rpt_GraphService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Rpt_GraphService.IServiceOf_Rpt_Graph")]
    public interface IServiceOf_Rpt_Graph {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/GetAllResponse")]
        FGA.Models.Rpt_Graph[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Rpt_Graph[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Get", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/GetResponse")]
        FGA.Models.Rpt_Graph Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Get", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Rpt_Graph> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Add", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/AddResponse")]
        FGA_En_Linea.Rpt_GraphService.AddResponse Add(FGA_En_Linea.Rpt_GraphService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Add", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.Rpt_GraphService.AddResponse> AddAsync(FGA_En_Linea.Rpt_GraphService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Update", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/UpdateResponse")]
        void Update(FGA.Models.Rpt_Graph entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Update", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Rpt_Graph entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Delete", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Graph/Delete", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Graph/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Rpt_Graph entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Rpt_Graph entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Rpt_Graph entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Rpt_Graph entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Rpt_GraphChannel : FGA_En_Linea.Rpt_GraphService.IServiceOf_Rpt_Graph, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Rpt_GraphClient : System.ServiceModel.ClientBase<FGA_En_Linea.Rpt_GraphService.IServiceOf_Rpt_Graph>, FGA_En_Linea.Rpt_GraphService.IServiceOf_Rpt_Graph {
        
        public ServiceOf_Rpt_GraphClient() {
        }
        
        public ServiceOf_Rpt_GraphClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Rpt_GraphClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Rpt_GraphClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Rpt_GraphClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Rpt_Graph[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Rpt_Graph[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Rpt_Graph Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Rpt_Graph> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.Rpt_GraphService.AddResponse FGA_En_Linea.Rpt_GraphService.IServiceOf_Rpt_Graph.Add(FGA_En_Linea.Rpt_GraphService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Rpt_Graph entity) {
            FGA_En_Linea.Rpt_GraphService.AddRequest inValue = new FGA_En_Linea.Rpt_GraphService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.Rpt_GraphService.AddResponse retVal = ((FGA_En_Linea.Rpt_GraphService.IServiceOf_Rpt_Graph)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.Rpt_GraphService.AddResponse> AddAsync(FGA_En_Linea.Rpt_GraphService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Rpt_Graph entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Rpt_Graph entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
