//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.UsuarioEstadoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioEstadoService.IServiceOf_UsuarioEstado")]
    public interface IServiceOf_UsuarioEstado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/GetAll", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/GetAllResponse")]
        FGA.Models.UsuarioEstado[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/GetAll", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.UsuarioEstado[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Get", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/GetResponse")]
        FGA.Models.UsuarioEstado Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Get", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.UsuarioEstado> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Add", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/AddResponse")]
        FGA_En_Linea.UsuarioEstadoService.AddResponse Add(FGA_En_Linea.UsuarioEstadoService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Add", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.UsuarioEstadoService.AddResponse> AddAsync(FGA_En_Linea.UsuarioEstadoService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Update", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/UpdateResponse")]
        void Update(FGA.Models.UsuarioEstado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Update", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.UsuarioEstado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Delete", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_UsuarioEstado/Delete", ReplyAction="http://tempuri.org/IServiceOf_UsuarioEstado/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.UsuarioEstado entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.UsuarioEstado entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.UsuarioEstado entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.UsuarioEstado entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_UsuarioEstadoChannel : FGA_En_Linea.UsuarioEstadoService.IServiceOf_UsuarioEstado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_UsuarioEstadoClient : System.ServiceModel.ClientBase<FGA_En_Linea.UsuarioEstadoService.IServiceOf_UsuarioEstado>, FGA_En_Linea.UsuarioEstadoService.IServiceOf_UsuarioEstado {
        
        public ServiceOf_UsuarioEstadoClient() {
        }
        
        public ServiceOf_UsuarioEstadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_UsuarioEstadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_UsuarioEstadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_UsuarioEstadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.UsuarioEstado[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.UsuarioEstado[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.UsuarioEstado Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.UsuarioEstado> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.UsuarioEstadoService.AddResponse FGA_En_Linea.UsuarioEstadoService.IServiceOf_UsuarioEstado.Add(FGA_En_Linea.UsuarioEstadoService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.UsuarioEstado entity) {
            FGA_En_Linea.UsuarioEstadoService.AddRequest inValue = new FGA_En_Linea.UsuarioEstadoService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.UsuarioEstadoService.AddResponse retVal = ((FGA_En_Linea.UsuarioEstadoService.IServiceOf_UsuarioEstado)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.UsuarioEstadoService.AddResponse> AddAsync(FGA_En_Linea.UsuarioEstadoService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.UsuarioEstado entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.UsuarioEstado entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
