//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.EvalResponsableCategoriaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvalResponsableCategoriaService.IEvalResponsableCategoriaService")]
    public interface IEvalResponsableCategoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/GetByUsusario", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetByUsusarioResponse")]
        Entities.Entities.Evaluacion.EvalResponsableCategoria[] GetByUsusario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/GetByUsusario", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetByUsusarioResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria[]> GetByUsusarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/GetByEntidad", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetByEntidadResponse")]
        Entities.Entities.Evaluacion.EvalResponsableCategoria[] GetByEntidad(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/GetByEntidad", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetByEntidadResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria[]> GetByEntidadAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Existe", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/ExisteResponse")]
        int Existe(string idEntidad, int idUsuario, int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Existe", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/ExisteResponse")]
        System.Threading.Tasks.Task<int> ExisteAsync(string idEntidad, int idUsuario, int idCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/GetAll", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetAllResponse")]
        Entities.Entities.Evaluacion.EvalResponsableCategoria[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/GetAll", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetAllResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Get", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetResponse")]
        Entities.Entities.Evaluacion.EvalResponsableCategoria Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Get", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/GetResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Add", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/AddResponse")]
        FGA_En_Linea.EvalResponsableCategoriaService.AddResponse Add(FGA_En_Linea.EvalResponsableCategoriaService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Add", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.EvalResponsableCategoriaService.AddResponse> AddAsync(FGA_En_Linea.EvalResponsableCategoriaService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Update", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/UpdateResponse")]
        void Update(Entities.Entities.Evaluacion.EvalResponsableCategoria entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Update", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalResponsableCategoria entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Delete", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalResponsableCategoriaService/Delete", ReplyAction="http://tempuri.org/IEvalResponsableCategoriaService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalResponsableCategoria entity;
        
        public AddRequest() {
        }
        
        public AddRequest(Entities.Entities.Evaluacion.EvalResponsableCategoria entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalResponsableCategoria entity;
        
        public AddResponse() {
        }
        
        public AddResponse(Entities.Entities.Evaluacion.EvalResponsableCategoria entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvalResponsableCategoriaServiceChannel : FGA_En_Linea.EvalResponsableCategoriaService.IEvalResponsableCategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvalResponsableCategoriaServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.EvalResponsableCategoriaService.IEvalResponsableCategoriaService>, FGA_En_Linea.EvalResponsableCategoriaService.IEvalResponsableCategoriaService {
        
        public EvalResponsableCategoriaServiceClient() {
        }
        
        public EvalResponsableCategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvalResponsableCategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvalResponsableCategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvalResponsableCategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Entities.Evaluacion.EvalResponsableCategoria[] GetByUsusario(int id) {
            return base.Channel.GetByUsusario(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria[]> GetByUsusarioAsync(int id) {
            return base.Channel.GetByUsusarioAsync(id);
        }
        
        public Entities.Entities.Evaluacion.EvalResponsableCategoria[] GetByEntidad(string id) {
            return base.Channel.GetByEntidad(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria[]> GetByEntidadAsync(string id) {
            return base.Channel.GetByEntidadAsync(id);
        }
        
        public int Existe(string idEntidad, int idUsuario, int idCategoria) {
            return base.Channel.Existe(idEntidad, idUsuario, idCategoria);
        }
        
        public System.Threading.Tasks.Task<int> ExisteAsync(string idEntidad, int idUsuario, int idCategoria) {
            return base.Channel.ExisteAsync(idEntidad, idUsuario, idCategoria);
        }
        
        public Entities.Entities.Evaluacion.EvalResponsableCategoria[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Entities.Entities.Evaluacion.EvalResponsableCategoria Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalResponsableCategoria> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.EvalResponsableCategoriaService.AddResponse FGA_En_Linea.EvalResponsableCategoriaService.IEvalResponsableCategoriaService.Add(FGA_En_Linea.EvalResponsableCategoriaService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref Entities.Entities.Evaluacion.EvalResponsableCategoria entity) {
            FGA_En_Linea.EvalResponsableCategoriaService.AddRequest inValue = new FGA_En_Linea.EvalResponsableCategoriaService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.EvalResponsableCategoriaService.AddResponse retVal = ((FGA_En_Linea.EvalResponsableCategoriaService.IEvalResponsableCategoriaService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.EvalResponsableCategoriaService.AddResponse> AddAsync(FGA_En_Linea.EvalResponsableCategoriaService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(Entities.Entities.Evaluacion.EvalResponsableCategoria entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalResponsableCategoria entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
