//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.NotificacionesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificacionesService.INotificacionesService")]
    public interface INotificacionesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/GetAll", ReplyAction="http://tempuri.org/INotificacionesService/GetAllResponse")]
        FGA.Models.Notificaciones[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/GetAll", ReplyAction="http://tempuri.org/INotificacionesService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Notificaciones[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Get", ReplyAction="http://tempuri.org/INotificacionesService/GetResponse")]
        FGA.Models.Notificaciones Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Get", ReplyAction="http://tempuri.org/INotificacionesService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Notificaciones> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Add", ReplyAction="http://tempuri.org/INotificacionesService/AddResponse")]
        FGA_En_Linea.NotificacionesService.AddResponse Add(FGA_En_Linea.NotificacionesService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Add", ReplyAction="http://tempuri.org/INotificacionesService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.NotificacionesService.AddResponse> AddAsync(FGA_En_Linea.NotificacionesService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Update", ReplyAction="http://tempuri.org/INotificacionesService/UpdateResponse")]
        void Update(FGA.Models.Notificaciones entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Update", ReplyAction="http://tempuri.org/INotificacionesService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Notificaciones entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Delete", ReplyAction="http://tempuri.org/INotificacionesService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificacionesService/Delete", ReplyAction="http://tempuri.org/INotificacionesService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Notificaciones entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Notificaciones entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Notificaciones entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Notificaciones entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificacionesServiceChannel : FGA_En_Linea.NotificacionesService.INotificacionesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificacionesServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.NotificacionesService.INotificacionesService>, FGA_En_Linea.NotificacionesService.INotificacionesService {
        
        public NotificacionesServiceClient() {
        }
        
        public NotificacionesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificacionesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Notificaciones[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Notificaciones[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Notificaciones Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Notificaciones> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.NotificacionesService.AddResponse FGA_En_Linea.NotificacionesService.INotificacionesService.Add(FGA_En_Linea.NotificacionesService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Notificaciones entity) {
            FGA_En_Linea.NotificacionesService.AddRequest inValue = new FGA_En_Linea.NotificacionesService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.NotificacionesService.AddResponse retVal = ((FGA_En_Linea.NotificacionesService.INotificacionesService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.NotificacionesService.AddResponse> AddAsync(FGA_En_Linea.NotificacionesService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Notificaciones entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Notificaciones entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
