//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.Rpt_EstructuraCamelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Rpt_EstructuraCamelService.IServiceOf_Rpt_EstructuraCamel")]
    public interface IServiceOf_Rpt_EstructuraCamel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/GetAllResponse")]
        FGA.Models.Rpt_EstructuraCamel[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Rpt_EstructuraCamel[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Get", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/GetResponse")]
        FGA.Models.Rpt_EstructuraCamel Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Get", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Rpt_EstructuraCamel> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Add", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/AddResponse")]
        FGA_En_Linea.Rpt_EstructuraCamelService.AddResponse Add(FGA_En_Linea.Rpt_EstructuraCamelService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Add", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.Rpt_EstructuraCamelService.AddResponse> AddAsync(FGA_En_Linea.Rpt_EstructuraCamelService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Update", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/UpdateResponse")]
        void Update(FGA.Models.Rpt_EstructuraCamel entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Update", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Rpt_EstructuraCamel entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Delete", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/Delete", ReplyAction="http://tempuri.org/IServiceOf_Rpt_EstructuraCamel/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Rpt_EstructuraCamel entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Rpt_EstructuraCamel entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Rpt_EstructuraCamel entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Rpt_EstructuraCamel entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Rpt_EstructuraCamelChannel : FGA_En_Linea.Rpt_EstructuraCamelService.IServiceOf_Rpt_EstructuraCamel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Rpt_EstructuraCamelClient : System.ServiceModel.ClientBase<FGA_En_Linea.Rpt_EstructuraCamelService.IServiceOf_Rpt_EstructuraCamel>, FGA_En_Linea.Rpt_EstructuraCamelService.IServiceOf_Rpt_EstructuraCamel {
        
        public ServiceOf_Rpt_EstructuraCamelClient() {
        }
        
        public ServiceOf_Rpt_EstructuraCamelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Rpt_EstructuraCamelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Rpt_EstructuraCamelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Rpt_EstructuraCamelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Rpt_EstructuraCamel[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Rpt_EstructuraCamel[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Rpt_EstructuraCamel Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Rpt_EstructuraCamel> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.Rpt_EstructuraCamelService.AddResponse FGA_En_Linea.Rpt_EstructuraCamelService.IServiceOf_Rpt_EstructuraCamel.Add(FGA_En_Linea.Rpt_EstructuraCamelService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Rpt_EstructuraCamel entity) {
            FGA_En_Linea.Rpt_EstructuraCamelService.AddRequest inValue = new FGA_En_Linea.Rpt_EstructuraCamelService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.Rpt_EstructuraCamelService.AddResponse retVal = ((FGA_En_Linea.Rpt_EstructuraCamelService.IServiceOf_Rpt_EstructuraCamel)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.Rpt_EstructuraCamelService.AddResponse> AddAsync(FGA_En_Linea.Rpt_EstructuraCamelService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Rpt_EstructuraCamel entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Rpt_EstructuraCamel entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
