//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.XML_ExcepcionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XML_ExcepcionService.IXML_ExcepcionService")]
    public interface IXML_ExcepcionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/GetAll", ReplyAction="http://tempuri.org/IXML_ExcepcionService/GetAllResponse")]
        FGA.Models.XML_Excepcion[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/GetAll", ReplyAction="http://tempuri.org/IXML_ExcepcionService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Excepcion[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/Add", ReplyAction="http://tempuri.org/IXML_ExcepcionService/AddResponse")]
        FGA_En_Linea.XML_ExcepcionService.AddResponse Add(FGA_En_Linea.XML_ExcepcionService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/Add", ReplyAction="http://tempuri.org/IXML_ExcepcionService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.XML_ExcepcionService.AddResponse> AddAsync(FGA_En_Linea.XML_ExcepcionService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/Update", ReplyAction="http://tempuri.org/IXML_ExcepcionService/UpdateResponse")]
        void Update(FGA.Models.XML_Excepcion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/Update", ReplyAction="http://tempuri.org/IXML_ExcepcionService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.XML_Excepcion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/Delete", ReplyAction="http://tempuri.org/IXML_ExcepcionService/DeleteResponse")]
        void Delete(FGA.Models.XML_Excepcion id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/Delete", ReplyAction="http://tempuri.org/IXML_ExcepcionService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(FGA.Models.XML_Excepcion id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/GetByFile", ReplyAction="http://tempuri.org/IXML_ExcepcionService/GetByFileResponse")]
        FGA.Models.XML_Excepcion[] GetByFile(string idFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ExcepcionService/GetByFile", ReplyAction="http://tempuri.org/IXML_ExcepcionService/GetByFileResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Excepcion[]> GetByFileAsync(string idFile);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.XML_Excepcion entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.XML_Excepcion entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.XML_Excepcion entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.XML_Excepcion entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXML_ExcepcionServiceChannel : FGA_En_Linea.XML_ExcepcionService.IXML_ExcepcionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XML_ExcepcionServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.XML_ExcepcionService.IXML_ExcepcionService>, FGA_En_Linea.XML_ExcepcionService.IXML_ExcepcionService {
        
        public XML_ExcepcionServiceClient() {
        }
        
        public XML_ExcepcionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XML_ExcepcionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XML_ExcepcionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XML_ExcepcionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.XML_Excepcion[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Excepcion[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.XML_ExcepcionService.AddResponse FGA_En_Linea.XML_ExcepcionService.IXML_ExcepcionService.Add(FGA_En_Linea.XML_ExcepcionService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.XML_Excepcion entity) {
            FGA_En_Linea.XML_ExcepcionService.AddRequest inValue = new FGA_En_Linea.XML_ExcepcionService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.XML_ExcepcionService.AddResponse retVal = ((FGA_En_Linea.XML_ExcepcionService.IXML_ExcepcionService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.XML_ExcepcionService.AddResponse> AddAsync(FGA_En_Linea.XML_ExcepcionService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.XML_Excepcion entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.XML_Excepcion entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(FGA.Models.XML_Excepcion id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(FGA.Models.XML_Excepcion id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public FGA.Models.XML_Excepcion[] GetByFile(string idFile) {
            return base.Channel.GetByFile(idFile);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Excepcion[]> GetByFileAsync(string idFile) {
            return base.Channel.GetByFileAsync(idFile);
        }
    }
}
