<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Otp.NET" Version="1.2.2" />
  </ItemGroup>

</Project>
