//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.ProyectoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProyectoService.IProyectoService")]
    public interface IProyectoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/GetAll", ReplyAction="http://tempuri.org/IProyectoService/GetAllResponse")]
        FGA.Models.Proyecto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/GetAll", ReplyAction="http://tempuri.org/IProyectoService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Proyecto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Get", ReplyAction="http://tempuri.org/IProyectoService/GetResponse")]
        FGA.Models.Proyecto Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Get", ReplyAction="http://tempuri.org/IProyectoService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Proyecto> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Add", ReplyAction="http://tempuri.org/IProyectoService/AddResponse")]
        FGA_En_Linea.ProyectoService.AddResponse Add(FGA_En_Linea.ProyectoService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Add", ReplyAction="http://tempuri.org/IProyectoService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.ProyectoService.AddResponse> AddAsync(FGA_En_Linea.ProyectoService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Update", ReplyAction="http://tempuri.org/IProyectoService/UpdateResponse")]
        void Update(FGA.Models.Proyecto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Update", ReplyAction="http://tempuri.org/IProyectoService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Proyecto entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Delete", ReplyAction="http://tempuri.org/IProyectoService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyectoService/Delete", ReplyAction="http://tempuri.org/IProyectoService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Proyecto entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Proyecto entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Proyecto entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Proyecto entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProyectoServiceChannel : FGA_En_Linea.ProyectoService.IProyectoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProyectoServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.ProyectoService.IProyectoService>, FGA_En_Linea.ProyectoService.IProyectoService {
        
        public ProyectoServiceClient() {
        }
        
        public ProyectoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProyectoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Proyecto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Proyecto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Proyecto Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Proyecto> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.ProyectoService.AddResponse FGA_En_Linea.ProyectoService.IProyectoService.Add(FGA_En_Linea.ProyectoService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Proyecto entity) {
            FGA_En_Linea.ProyectoService.AddRequest inValue = new FGA_En_Linea.ProyectoService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.ProyectoService.AddResponse retVal = ((FGA_En_Linea.ProyectoService.IProyectoService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.ProyectoService.AddResponse> AddAsync(FGA_En_Linea.ProyectoService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Proyecto entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Proyecto entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
