//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.CalendarioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalendarioService.ICalendarioService")]
    public interface ICalendarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/GetByDate", ReplyAction="http://tempuri.org/ICalendarioService/GetByDateResponse")]
        FGA.Models.Calendario GetByDate(System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/GetByDate", ReplyAction="http://tempuri.org/ICalendarioService/GetByDateResponse")]
        System.Threading.Tasks.Task<FGA.Models.Calendario> GetByDateAsync(System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/GetAll", ReplyAction="http://tempuri.org/ICalendarioService/GetAllResponse")]
        FGA.Models.Calendario[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/GetAll", ReplyAction="http://tempuri.org/ICalendarioService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Calendario[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Get", ReplyAction="http://tempuri.org/ICalendarioService/GetResponse")]
        FGA.Models.Calendario Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Get", ReplyAction="http://tempuri.org/ICalendarioService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Calendario> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Add", ReplyAction="http://tempuri.org/ICalendarioService/AddResponse")]
        FGA_En_Linea.CalendarioService.AddResponse Add(FGA_En_Linea.CalendarioService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Add", ReplyAction="http://tempuri.org/ICalendarioService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.CalendarioService.AddResponse> AddAsync(FGA_En_Linea.CalendarioService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Update", ReplyAction="http://tempuri.org/ICalendarioService/UpdateResponse")]
        void Update(FGA.Models.Calendario entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Update", ReplyAction="http://tempuri.org/ICalendarioService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Calendario entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Delete", ReplyAction="http://tempuri.org/ICalendarioService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarioService/Delete", ReplyAction="http://tempuri.org/ICalendarioService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Calendario entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Calendario entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Calendario entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Calendario entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalendarioServiceChannel : FGA_En_Linea.CalendarioService.ICalendarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalendarioServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.CalendarioService.ICalendarioService>, FGA_En_Linea.CalendarioService.ICalendarioService {
        
        public CalendarioServiceClient() {
        }
        
        public CalendarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalendarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Calendario GetByDate(System.DateTime periodo) {
            return base.Channel.GetByDate(periodo);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Calendario> GetByDateAsync(System.DateTime periodo) {
            return base.Channel.GetByDateAsync(periodo);
        }
        
        public FGA.Models.Calendario[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Calendario[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Calendario Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Calendario> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.CalendarioService.AddResponse FGA_En_Linea.CalendarioService.ICalendarioService.Add(FGA_En_Linea.CalendarioService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Calendario entity) {
            FGA_En_Linea.CalendarioService.AddRequest inValue = new FGA_En_Linea.CalendarioService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.CalendarioService.AddResponse retVal = ((FGA_En_Linea.CalendarioService.ICalendarioService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.CalendarioService.AddResponse> AddAsync(FGA_En_Linea.CalendarioService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Calendario entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Calendario entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
