//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.Exclusion_ProyectarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Exclusion_ProyectarService.IExclusion_PeriodoService")]
    public interface IExclusion_PeriodoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Habilitar", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/HabilitarResponse")]
        void Habilitar(System.DateTime Periodo, string Cuenta, string IdEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Habilitar", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/HabilitarResponse")]
        System.Threading.Tasks.Task HabilitarAsync(System.DateTime Periodo, string Cuenta, string IdEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/GetAll", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/GetAllResponse")]
        FGA.Models.Exclusion_Periodos_Proyectar[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/GetAll", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Exclusion_Periodos_Proyectar[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Get", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/GetResponse")]
        FGA.Models.Exclusion_Periodos_Proyectar Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Get", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Exclusion_Periodos_Proyectar> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Add", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/AddResponse")]
        FGA_En_Linea.Exclusion_ProyectarService.AddResponse Add(FGA_En_Linea.Exclusion_ProyectarService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Add", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.Exclusion_ProyectarService.AddResponse> AddAsync(FGA_En_Linea.Exclusion_ProyectarService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Update", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/UpdateResponse")]
        void Update(FGA.Models.Exclusion_Periodos_Proyectar entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Update", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Exclusion_Periodos_Proyectar entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Delete", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExclusion_PeriodoService/Delete", ReplyAction="http://tempuri.org/IExclusion_PeriodoService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Exclusion_Periodos_Proyectar entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Exclusion_Periodos_Proyectar entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Exclusion_Periodos_Proyectar entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Exclusion_Periodos_Proyectar entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExclusion_PeriodoServiceChannel : FGA_En_Linea.Exclusion_ProyectarService.IExclusion_PeriodoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Exclusion_PeriodoServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.Exclusion_ProyectarService.IExclusion_PeriodoService>, FGA_En_Linea.Exclusion_ProyectarService.IExclusion_PeriodoService {
        
        public Exclusion_PeriodoServiceClient() {
        }
        
        public Exclusion_PeriodoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Exclusion_PeriodoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Exclusion_PeriodoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Exclusion_PeriodoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Habilitar(System.DateTime Periodo, string Cuenta, string IdEntidad) {
            base.Channel.Habilitar(Periodo, Cuenta, IdEntidad);
        }
        
        public System.Threading.Tasks.Task HabilitarAsync(System.DateTime Periodo, string Cuenta, string IdEntidad) {
            return base.Channel.HabilitarAsync(Periodo, Cuenta, IdEntidad);
        }
        
        public FGA.Models.Exclusion_Periodos_Proyectar[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Exclusion_Periodos_Proyectar[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Exclusion_Periodos_Proyectar Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Exclusion_Periodos_Proyectar> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.Exclusion_ProyectarService.AddResponse FGA_En_Linea.Exclusion_ProyectarService.IExclusion_PeriodoService.Add(FGA_En_Linea.Exclusion_ProyectarService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Exclusion_Periodos_Proyectar entity) {
            FGA_En_Linea.Exclusion_ProyectarService.AddRequest inValue = new FGA_En_Linea.Exclusion_ProyectarService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.Exclusion_ProyectarService.AddResponse retVal = ((FGA_En_Linea.Exclusion_ProyectarService.IExclusion_PeriodoService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.Exclusion_ProyectarService.AddResponse> AddAsync(FGA_En_Linea.Exclusion_ProyectarService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Exclusion_Periodos_Proyectar entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Exclusion_Periodos_Proyectar entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
