//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.MenuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuService.IServiceOf_Menu")]
    public interface IServiceOf_Menu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Menu/GetAllResponse")]
        FGA.Models.Menu[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Menu/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Menu[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Get", ReplyAction="http://tempuri.org/IServiceOf_Menu/GetResponse")]
        FGA.Models.Menu Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Get", ReplyAction="http://tempuri.org/IServiceOf_Menu/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Menu> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Add", ReplyAction="http://tempuri.org/IServiceOf_Menu/AddResponse")]
        FGA_En_Linea.MenuService.AddResponse Add(FGA_En_Linea.MenuService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Add", ReplyAction="http://tempuri.org/IServiceOf_Menu/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.MenuService.AddResponse> AddAsync(FGA_En_Linea.MenuService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Update", ReplyAction="http://tempuri.org/IServiceOf_Menu/UpdateResponse")]
        void Update(FGA.Models.Menu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Update", ReplyAction="http://tempuri.org/IServiceOf_Menu/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Menu entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Delete", ReplyAction="http://tempuri.org/IServiceOf_Menu/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Menu/Delete", ReplyAction="http://tempuri.org/IServiceOf_Menu/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Menu entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Menu entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Menu entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Menu entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_MenuChannel : FGA_En_Linea.MenuService.IServiceOf_Menu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_MenuClient : System.ServiceModel.ClientBase<FGA_En_Linea.MenuService.IServiceOf_Menu>, FGA_En_Linea.MenuService.IServiceOf_Menu {
        
        public ServiceOf_MenuClient() {
        }
        
        public ServiceOf_MenuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_MenuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_MenuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_MenuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Menu[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Menu[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Menu Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Menu> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.MenuService.AddResponse FGA_En_Linea.MenuService.IServiceOf_Menu.Add(FGA_En_Linea.MenuService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Menu entity) {
            FGA_En_Linea.MenuService.AddRequest inValue = new FGA_En_Linea.MenuService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.MenuService.AddResponse retVal = ((FGA_En_Linea.MenuService.IServiceOf_Menu)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.MenuService.AddResponse> AddAsync(FGA_En_Linea.MenuService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Menu entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Menu entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
