//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.MessageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageService.IMessageService")]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetLastMessages", ReplyAction="http://tempuri.org/IMessageService/GetLastMessagesResponse")]
        FGA.Models.Message[] GetLastMessages(string toUser, string fromUser, int num_LastMessages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetLastMessages", ReplyAction="http://tempuri.org/IMessageService/GetLastMessagesResponse")]
        System.Threading.Tasks.Task<FGA.Models.Message[]> GetLastMessagesAsync(string toUser, string fromUser, int num_LastMessages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetAll", ReplyAction="http://tempuri.org/IMessageService/GetAllResponse")]
        FGA.Models.Message[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetAll", ReplyAction="http://tempuri.org/IMessageService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Message[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Get", ReplyAction="http://tempuri.org/IMessageService/GetResponse")]
        FGA.Models.Message Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Get", ReplyAction="http://tempuri.org/IMessageService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Message> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Add", ReplyAction="http://tempuri.org/IMessageService/AddResponse")]
        FGA_En_Linea.MessageService.AddResponse Add(FGA_En_Linea.MessageService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Add", ReplyAction="http://tempuri.org/IMessageService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.MessageService.AddResponse> AddAsync(FGA_En_Linea.MessageService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Update", ReplyAction="http://tempuri.org/IMessageService/UpdateResponse")]
        void Update(FGA.Models.Message entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Update", ReplyAction="http://tempuri.org/IMessageService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Message entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Delete", ReplyAction="http://tempuri.org/IMessageService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Delete", ReplyAction="http://tempuri.org/IMessageService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Message entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Message entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Message entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Message entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : FGA_En_Linea.MessageService.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.MessageService.IMessageService>, FGA_En_Linea.MessageService.IMessageService {
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Message[] GetLastMessages(string toUser, string fromUser, int num_LastMessages) {
            return base.Channel.GetLastMessages(toUser, fromUser, num_LastMessages);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Message[]> GetLastMessagesAsync(string toUser, string fromUser, int num_LastMessages) {
            return base.Channel.GetLastMessagesAsync(toUser, fromUser, num_LastMessages);
        }
        
        public FGA.Models.Message[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Message[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Message Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Message> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.MessageService.AddResponse FGA_En_Linea.MessageService.IMessageService.Add(FGA_En_Linea.MessageService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Message entity) {
            FGA_En_Linea.MessageService.AddRequest inValue = new FGA_En_Linea.MessageService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.MessageService.AddResponse retVal = ((FGA_En_Linea.MessageService.IMessageService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.MessageService.AddResponse> AddAsync(FGA_En_Linea.MessageService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Message entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Message entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
