//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.SolicitudCambioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SolicitudCambioService.ISolicitudCambioService")]
    public interface ISolicitudCambioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/GetAll", ReplyAction="http://tempuri.org/ISolicitudCambioService/GetAllResponse")]
        FGA.Models.SolicitudCambio[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/GetAll", ReplyAction="http://tempuri.org/ISolicitudCambioService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.SolicitudCambio[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Get", ReplyAction="http://tempuri.org/ISolicitudCambioService/GetResponse")]
        FGA.Models.SolicitudCambio Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Get", ReplyAction="http://tempuri.org/ISolicitudCambioService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.SolicitudCambio> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Add", ReplyAction="http://tempuri.org/ISolicitudCambioService/AddResponse")]
        FGA_En_Linea.SolicitudCambioService.AddResponse Add(FGA_En_Linea.SolicitudCambioService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Add", ReplyAction="http://tempuri.org/ISolicitudCambioService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.SolicitudCambioService.AddResponse> AddAsync(FGA_En_Linea.SolicitudCambioService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Update", ReplyAction="http://tempuri.org/ISolicitudCambioService/UpdateResponse")]
        void Update(FGA.Models.SolicitudCambio entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Update", ReplyAction="http://tempuri.org/ISolicitudCambioService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.SolicitudCambio entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Delete", ReplyAction="http://tempuri.org/ISolicitudCambioService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudCambioService/Delete", ReplyAction="http://tempuri.org/ISolicitudCambioService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.SolicitudCambio entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.SolicitudCambio entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.SolicitudCambio entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.SolicitudCambio entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitudCambioServiceChannel : FGA_En_Linea.SolicitudCambioService.ISolicitudCambioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudCambioServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.SolicitudCambioService.ISolicitudCambioService>, FGA_En_Linea.SolicitudCambioService.ISolicitudCambioService {
        
        public SolicitudCambioServiceClient() {
        }
        
        public SolicitudCambioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudCambioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudCambioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudCambioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.SolicitudCambio[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.SolicitudCambio[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.SolicitudCambio Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.SolicitudCambio> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.SolicitudCambioService.AddResponse FGA_En_Linea.SolicitudCambioService.ISolicitudCambioService.Add(FGA_En_Linea.SolicitudCambioService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.SolicitudCambio entity) {
            FGA_En_Linea.SolicitudCambioService.AddRequest inValue = new FGA_En_Linea.SolicitudCambioService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.SolicitudCambioService.AddResponse retVal = ((FGA_En_Linea.SolicitudCambioService.ISolicitudCambioService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.SolicitudCambioService.AddResponse> AddAsync(FGA_En_Linea.SolicitudCambioService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.SolicitudCambio entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.SolicitudCambio entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
