//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.CategoriaRiesgoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoriaRiesgoService.IServiceOf_Categoria_Riesgo")]
    public interface IServiceOf_Categoria_Riesgo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/GetAllResponse")]
        FGA.Models.Categoria_Riesgo[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Categoria_Riesgo[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Get", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/GetResponse")]
        FGA.Models.Categoria_Riesgo Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Get", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Categoria_Riesgo> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Add", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/AddResponse")]
        FGA_En_Linea.CategoriaRiesgoService.AddResponse Add(FGA_En_Linea.CategoriaRiesgoService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Add", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.CategoriaRiesgoService.AddResponse> AddAsync(FGA_En_Linea.CategoriaRiesgoService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Update", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/UpdateResponse")]
        void Update(FGA.Models.Categoria_Riesgo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Update", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Categoria_Riesgo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Delete", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Categoria_Riesgo/Delete", ReplyAction="http://tempuri.org/IServiceOf_Categoria_Riesgo/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Categoria_Riesgo entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Categoria_Riesgo entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Categoria_Riesgo entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Categoria_Riesgo entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Categoria_RiesgoChannel : FGA_En_Linea.CategoriaRiesgoService.IServiceOf_Categoria_Riesgo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Categoria_RiesgoClient : System.ServiceModel.ClientBase<FGA_En_Linea.CategoriaRiesgoService.IServiceOf_Categoria_Riesgo>, FGA_En_Linea.CategoriaRiesgoService.IServiceOf_Categoria_Riesgo {
        
        public ServiceOf_Categoria_RiesgoClient() {
        }
        
        public ServiceOf_Categoria_RiesgoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Categoria_RiesgoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Categoria_RiesgoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Categoria_RiesgoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Categoria_Riesgo[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Categoria_Riesgo[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Categoria_Riesgo Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Categoria_Riesgo> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.CategoriaRiesgoService.AddResponse FGA_En_Linea.CategoriaRiesgoService.IServiceOf_Categoria_Riesgo.Add(FGA_En_Linea.CategoriaRiesgoService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Categoria_Riesgo entity) {
            FGA_En_Linea.CategoriaRiesgoService.AddRequest inValue = new FGA_En_Linea.CategoriaRiesgoService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.CategoriaRiesgoService.AddResponse retVal = ((FGA_En_Linea.CategoriaRiesgoService.IServiceOf_Categoria_Riesgo)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.CategoriaRiesgoService.AddResponse> AddAsync(FGA_En_Linea.CategoriaRiesgoService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Categoria_Riesgo entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Categoria_Riesgo entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
