//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.BCCR_TipoIndicadorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BCCR_TipoIndicadorService.IBCCR_TipoIndicadorService")]
    public interface IBCCR_TipoIndicadorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/GetAll", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/GetAllResponse")]
        FGA.Models.BCCR_TipoIndicador[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/GetAll", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.BCCR_TipoIndicador[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Get", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/GetResponse")]
        FGA.Models.BCCR_TipoIndicador Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Get", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.BCCR_TipoIndicador> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Add", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/AddResponse")]
        FGA_En_Linea.BCCR_TipoIndicadorService.AddResponse Add(FGA_En_Linea.BCCR_TipoIndicadorService.AddRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Add", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.BCCR_TipoIndicadorService.AddResponse> AddAsync(FGA_En_Linea.BCCR_TipoIndicadorService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Update", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/UpdateResponse")]
        void Update(FGA.Models.BCCR_TipoIndicador entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Update", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.BCCR_TipoIndicador entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Delete", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_TipoIndicadorService/Delete", ReplyAction="http://tempuri.org/IBCCR_TipoIndicadorService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.BCCR_TipoIndicador entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.BCCR_TipoIndicador entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.BCCR_TipoIndicador entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.BCCR_TipoIndicador entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBCCR_TipoIndicadorServiceChannel : FGA_En_Linea.BCCR_TipoIndicadorService.IBCCR_TipoIndicadorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BCCR_TipoIndicadorServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.BCCR_TipoIndicadorService.IBCCR_TipoIndicadorService>, FGA_En_Linea.BCCR_TipoIndicadorService.IBCCR_TipoIndicadorService {
        
        public BCCR_TipoIndicadorServiceClient() {
        }
        
        public BCCR_TipoIndicadorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BCCR_TipoIndicadorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BCCR_TipoIndicadorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BCCR_TipoIndicadorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.BCCR_TipoIndicador[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.BCCR_TipoIndicador[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.BCCR_TipoIndicador Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.BCCR_TipoIndicador> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.BCCR_TipoIndicadorService.AddResponse FGA_En_Linea.BCCR_TipoIndicadorService.IBCCR_TipoIndicadorService.Add(FGA_En_Linea.BCCR_TipoIndicadorService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.BCCR_TipoIndicador entity) {
            FGA_En_Linea.BCCR_TipoIndicadorService.AddRequest inValue = new FGA_En_Linea.BCCR_TipoIndicadorService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.BCCR_TipoIndicadorService.AddResponse retVal = ((FGA_En_Linea.BCCR_TipoIndicadorService.IBCCR_TipoIndicadorService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.BCCR_TipoIndicadorService.AddResponse> AddAsync(FGA_En_Linea.BCCR_TipoIndicadorService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.BCCR_TipoIndicador entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.BCCR_TipoIndicador entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
