//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.SectorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SectorService.ISectorService")]
    public interface ISectorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/GetAll", ReplyAction="http://tempuri.org/ISectorService/GetAllResponse")]
        FGA.Models.Sector[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/GetAll", ReplyAction="http://tempuri.org/ISectorService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Sector[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Get", ReplyAction="http://tempuri.org/ISectorService/GetResponse")]
        FGA.Models.Sector Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Get", ReplyAction="http://tempuri.org/ISectorService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Sector> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Add", ReplyAction="http://tempuri.org/ISectorService/AddResponse")]
        FGA_En_Linea.SectorService.AddResponse Add(FGA_En_Linea.SectorService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Add", ReplyAction="http://tempuri.org/ISectorService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.SectorService.AddResponse> AddAsync(FGA_En_Linea.SectorService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Update", ReplyAction="http://tempuri.org/ISectorService/UpdateResponse")]
        void Update(FGA.Models.Sector entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Update", ReplyAction="http://tempuri.org/ISectorService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Sector entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Delete", ReplyAction="http://tempuri.org/ISectorService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISectorService/Delete", ReplyAction="http://tempuri.org/ISectorService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Sector entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Sector entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Sector entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Sector entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISectorServiceChannel : FGA_En_Linea.SectorService.ISectorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SectorServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.SectorService.ISectorService>, FGA_En_Linea.SectorService.ISectorService {
        
        public SectorServiceClient() {
        }
        
        public SectorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SectorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SectorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SectorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Sector[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Sector[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Sector Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Sector> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.SectorService.AddResponse FGA_En_Linea.SectorService.ISectorService.Add(FGA_En_Linea.SectorService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Sector entity) {
            FGA_En_Linea.SectorService.AddRequest inValue = new FGA_En_Linea.SectorService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.SectorService.AddResponse retVal = ((FGA_En_Linea.SectorService.ISectorService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.SectorService.AddResponse> AddAsync(FGA_En_Linea.SectorService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Sector entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Sector entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
