//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.TCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCService.IServiceOf_Hist_TipoCambio")]
    public interface IServiceOf_Hist_TipoCambio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/GetAllResponse")]
        FGA.Models.Hist_TipoCambio[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_TipoCambio[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/GetResponse")]
        FGA.Models.Hist_TipoCambio Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_TipoCambio> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/AddResponse")]
        FGA_En_Linea.TCService.AddResponse Add(FGA_En_Linea.TCService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.TCService.AddResponse> AddAsync(FGA_En_Linea.TCService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/UpdateResponse")]
        void Update(FGA.Models.Hist_TipoCambio entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_TipoCambio entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TipoCambio/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_TipoCambio/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_TipoCambio entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Hist_TipoCambio entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_TipoCambio entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Hist_TipoCambio entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Hist_TipoCambioChannel : FGA_En_Linea.TCService.IServiceOf_Hist_TipoCambio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Hist_TipoCambioClient : System.ServiceModel.ClientBase<FGA_En_Linea.TCService.IServiceOf_Hist_TipoCambio>, FGA_En_Linea.TCService.IServiceOf_Hist_TipoCambio {
        
        public ServiceOf_Hist_TipoCambioClient() {
        }
        
        public ServiceOf_Hist_TipoCambioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Hist_TipoCambioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_TipoCambioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_TipoCambioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Hist_TipoCambio[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_TipoCambio[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Hist_TipoCambio Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_TipoCambio> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.TCService.AddResponse FGA_En_Linea.TCService.IServiceOf_Hist_TipoCambio.Add(FGA_En_Linea.TCService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Hist_TipoCambio entity) {
            FGA_En_Linea.TCService.AddRequest inValue = new FGA_En_Linea.TCService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.TCService.AddResponse retVal = ((FGA_En_Linea.TCService.IServiceOf_Hist_TipoCambio)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.TCService.AddResponse> AddAsync(FGA_En_Linea.TCService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Hist_TipoCambio entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_TipoCambio entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
