//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.IPCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPCService.IServiceOf_Hist_IPC")]
    public interface IServiceOf_Hist_IPC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/GetAllResponse")]
        FGA.Models.Hist_IPC[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_IPC[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/GetResponse")]
        FGA.Models.Hist_IPC Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_IPC> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/AddResponse")]
        FGA_En_Linea.IPCService.AddResponse Add(FGA_En_Linea.IPCService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.IPCService.AddResponse> AddAsync(FGA_En_Linea.IPCService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/UpdateResponse")]
        void Update(FGA.Models.Hist_IPC entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_IPC entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_IPC/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_IPC/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_IPC entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Hist_IPC entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_IPC entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Hist_IPC entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Hist_IPCChannel : FGA_En_Linea.IPCService.IServiceOf_Hist_IPC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Hist_IPCClient : System.ServiceModel.ClientBase<FGA_En_Linea.IPCService.IServiceOf_Hist_IPC>, FGA_En_Linea.IPCService.IServiceOf_Hist_IPC {
        
        public ServiceOf_Hist_IPCClient() {
        }
        
        public ServiceOf_Hist_IPCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Hist_IPCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_IPCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_IPCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Hist_IPC[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_IPC[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Hist_IPC Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_IPC> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.IPCService.AddResponse FGA_En_Linea.IPCService.IServiceOf_Hist_IPC.Add(FGA_En_Linea.IPCService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Hist_IPC entity) {
            FGA_En_Linea.IPCService.AddRequest inValue = new FGA_En_Linea.IPCService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.IPCService.AddResponse retVal = ((FGA_En_Linea.IPCService.IServiceOf_Hist_IPC)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.IPCService.AddResponse> AddAsync(FGA_En_Linea.IPCService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Hist_IPC entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_IPC entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
