//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.TBPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TBPService.IServiceOf_Hist_TBP")]
    public interface IServiceOf_Hist_TBP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/GetAllResponse")]
        FGA.Models.Hist_TBP[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_TBP[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/GetResponse")]
        FGA.Models.Hist_TBP Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_TBP> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/AddResponse")]
        FGA_En_Linea.TBPService.AddResponse Add(FGA_En_Linea.TBPService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.TBPService.AddResponse> AddAsync(FGA_En_Linea.TBPService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/UpdateResponse")]
        void Update(FGA.Models.Hist_TBP entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_TBP entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_TBP/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_TBP/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_TBP entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Hist_TBP entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_TBP entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Hist_TBP entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Hist_TBPChannel : FGA_En_Linea.TBPService.IServiceOf_Hist_TBP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Hist_TBPClient : System.ServiceModel.ClientBase<FGA_En_Linea.TBPService.IServiceOf_Hist_TBP>, FGA_En_Linea.TBPService.IServiceOf_Hist_TBP {
        
        public ServiceOf_Hist_TBPClient() {
        }
        
        public ServiceOf_Hist_TBPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Hist_TBPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_TBPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_TBPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Hist_TBP[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_TBP[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Hist_TBP Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_TBP> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.TBPService.AddResponse FGA_En_Linea.TBPService.IServiceOf_Hist_TBP.Add(FGA_En_Linea.TBPService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Hist_TBP entity) {
            FGA_En_Linea.TBPService.AddRequest inValue = new FGA_En_Linea.TBPService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.TBPService.AddResponse retVal = ((FGA_En_Linea.TBPService.IServiceOf_Hist_TBP)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.TBPService.AddResponse> AddAsync(FGA_En_Linea.TBPService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Hist_TBP entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_TBP entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
