//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.TipoXMLService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipoXMLService.IServiceOf_TipoXML")]
    public interface IServiceOf_TipoXML {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/GetAll", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/GetAllResponse")]
        FGA.Models.TipoXML[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/GetAll", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.TipoXML[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Get", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/GetResponse")]
        FGA.Models.TipoXML Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Get", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.TipoXML> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Add", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/AddResponse")]
        FGA_En_Linea.TipoXMLService.AddResponse Add(FGA_En_Linea.TipoXMLService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Add", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.TipoXMLService.AddResponse> AddAsync(FGA_En_Linea.TipoXMLService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Update", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/UpdateResponse")]
        void Update(FGA.Models.TipoXML entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Update", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.TipoXML entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Delete", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoXML/Delete", ReplyAction="http://tempuri.org/IServiceOf_TipoXML/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.TipoXML entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.TipoXML entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.TipoXML entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.TipoXML entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_TipoXMLChannel : FGA_En_Linea.TipoXMLService.IServiceOf_TipoXML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_TipoXMLClient : System.ServiceModel.ClientBase<FGA_En_Linea.TipoXMLService.IServiceOf_TipoXML>, FGA_En_Linea.TipoXMLService.IServiceOf_TipoXML {
        
        public ServiceOf_TipoXMLClient() {
        }
        
        public ServiceOf_TipoXMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_TipoXMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_TipoXMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_TipoXMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.TipoXML[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.TipoXML[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.TipoXML Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.TipoXML> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.TipoXMLService.AddResponse FGA_En_Linea.TipoXMLService.IServiceOf_TipoXML.Add(FGA_En_Linea.TipoXMLService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.TipoXML entity) {
            FGA_En_Linea.TipoXMLService.AddRequest inValue = new FGA_En_Linea.TipoXMLService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.TipoXMLService.AddResponse retVal = ((FGA_En_Linea.TipoXMLService.IServiceOf_TipoXML)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.TipoXMLService.AddResponse> AddAsync(FGA_En_Linea.TipoXMLService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.TipoXML entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.TipoXML entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
