//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.TipoCarteraService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipoCarteraService.IServiceOf_Tipo_Cartera")]
    public interface IServiceOf_Tipo_Cartera {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/GetAllResponse")]
        FGA.Models.Tipo_Cartera[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Tipo_Cartera[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Get", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/GetResponse")]
        FGA.Models.Tipo_Cartera Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Get", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Tipo_Cartera> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Add", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/AddResponse")]
        FGA_En_Linea.TipoCarteraService.AddResponse Add(FGA_En_Linea.TipoCarteraService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Add", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.TipoCarteraService.AddResponse> AddAsync(FGA_En_Linea.TipoCarteraService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Update", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/UpdateResponse")]
        void Update(FGA.Models.Tipo_Cartera entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Update", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Tipo_Cartera entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Delete", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Tipo_Cartera/Delete", ReplyAction="http://tempuri.org/IServiceOf_Tipo_Cartera/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Tipo_Cartera entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Tipo_Cartera entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Tipo_Cartera entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Tipo_Cartera entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Tipo_CarteraChannel : FGA_En_Linea.TipoCarteraService.IServiceOf_Tipo_Cartera, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Tipo_CarteraClient : System.ServiceModel.ClientBase<FGA_En_Linea.TipoCarteraService.IServiceOf_Tipo_Cartera>, FGA_En_Linea.TipoCarteraService.IServiceOf_Tipo_Cartera {
        
        public ServiceOf_Tipo_CarteraClient() {
        }
        
        public ServiceOf_Tipo_CarteraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Tipo_CarteraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Tipo_CarteraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Tipo_CarteraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Tipo_Cartera[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Tipo_Cartera[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Tipo_Cartera Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Tipo_Cartera> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.TipoCarteraService.AddResponse FGA_En_Linea.TipoCarteraService.IServiceOf_Tipo_Cartera.Add(FGA_En_Linea.TipoCarteraService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Tipo_Cartera entity) {
            FGA_En_Linea.TipoCarteraService.AddRequest inValue = new FGA_En_Linea.TipoCarteraService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.TipoCarteraService.AddResponse retVal = ((FGA_En_Linea.TipoCarteraService.IServiceOf_Tipo_Cartera)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.TipoCarteraService.AddResponse> AddAsync(FGA_En_Linea.TipoCarteraService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Tipo_Cartera entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Tipo_Cartera entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
