//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.SexoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SexoService.IServiceOf_Sexo")]
    public interface IServiceOf_Sexo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Sexo/GetAllResponse")]
        FGA.Models.Sexo[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Sexo/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Sexo[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Get", ReplyAction="http://tempuri.org/IServiceOf_Sexo/GetResponse")]
        FGA.Models.Sexo Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Get", ReplyAction="http://tempuri.org/IServiceOf_Sexo/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Sexo> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Add", ReplyAction="http://tempuri.org/IServiceOf_Sexo/AddResponse")]
        FGA_En_Linea.SexoService.AddResponse Add(FGA_En_Linea.SexoService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Add", ReplyAction="http://tempuri.org/IServiceOf_Sexo/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.SexoService.AddResponse> AddAsync(FGA_En_Linea.SexoService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Update", ReplyAction="http://tempuri.org/IServiceOf_Sexo/UpdateResponse")]
        void Update(FGA.Models.Sexo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Update", ReplyAction="http://tempuri.org/IServiceOf_Sexo/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Sexo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Delete", ReplyAction="http://tempuri.org/IServiceOf_Sexo/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Sexo/Delete", ReplyAction="http://tempuri.org/IServiceOf_Sexo/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Sexo entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Sexo entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Sexo entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Sexo entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_SexoChannel : FGA_En_Linea.SexoService.IServiceOf_Sexo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_SexoClient : System.ServiceModel.ClientBase<FGA_En_Linea.SexoService.IServiceOf_Sexo>, FGA_En_Linea.SexoService.IServiceOf_Sexo {
        
        public ServiceOf_SexoClient() {
        }
        
        public ServiceOf_SexoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_SexoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_SexoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_SexoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Sexo[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Sexo[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Sexo Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Sexo> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.SexoService.AddResponse FGA_En_Linea.SexoService.IServiceOf_Sexo.Add(FGA_En_Linea.SexoService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Sexo entity) {
            FGA_En_Linea.SexoService.AddRequest inValue = new FGA_En_Linea.SexoService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.SexoService.AddResponse retVal = ((FGA_En_Linea.SexoService.IServiceOf_Sexo)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.SexoService.AddResponse> AddAsync(FGA_En_Linea.SexoService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Sexo entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Sexo entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
