//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileService.CargaAsincronicaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CargaAsincronicaService.ICargaAsincronicaService")]
    public interface ICargaAsincronicaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/GetAll", ReplyAction="http://tempuri.org/ICargaAsincronicaService/GetAllResponse")]
        FGA.Models.CargaAsincronica[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/GetAll", ReplyAction="http://tempuri.org/ICargaAsincronicaService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.CargaAsincronica[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Get", ReplyAction="http://tempuri.org/ICargaAsincronicaService/GetResponse")]
        FGA.Models.CargaAsincronica Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Get", ReplyAction="http://tempuri.org/ICargaAsincronicaService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.CargaAsincronica> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Add", ReplyAction="http://tempuri.org/ICargaAsincronicaService/AddResponse")]
        AddResponse Add(AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Add", ReplyAction="http://tempuri.org/ICargaAsincronicaService/AddResponse")]
        System.Threading.Tasks.Task<AddResponse> AddAsync(AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Update", ReplyAction="http://tempuri.org/ICargaAsincronicaService/UpdateResponse")]
        void Update(FGA.Models.CargaAsincronica entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Update", ReplyAction="http://tempuri.org/ICargaAsincronicaService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.CargaAsincronica entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Delete", ReplyAction="http://tempuri.org/ICargaAsincronicaService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/Delete", ReplyAction="http://tempuri.org/ICargaAsincronicaService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/GetPendientesAsyc", ReplyAction="http://tempuri.org/ICargaAsincronicaService/GetPendientesAsycResponse")]
        FGA.Models.CargaAsincronica[] GetPendientesAsyc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaAsincronicaService/GetPendientesAsyc", ReplyAction="http://tempuri.org/ICargaAsincronicaService/GetPendientesAsycResponse")]
        System.Threading.Tasks.Task<FGA.Models.CargaAsincronica[]> GetPendientesAsycAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.CargaAsincronica entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.CargaAsincronica entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.CargaAsincronica entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.CargaAsincronica entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICargaAsincronicaServiceChannel : ICargaAsincronicaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargaAsincronicaServiceClient : System.ServiceModel.ClientBase<ICargaAsincronicaService>, ICargaAsincronicaService {
        
        public CargaAsincronicaServiceClient() {
        }
        
        public CargaAsincronicaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargaAsincronicaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargaAsincronicaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargaAsincronicaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.CargaAsincronica[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.CargaAsincronica[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.CargaAsincronica Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.CargaAsincronica> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
         AddResponse ICargaAsincronicaService.Add(AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.CargaAsincronica entity) {
            AddRequest inValue = new AddRequest();
            inValue.entity = entity;
            AddResponse retVal = ((ICargaAsincronicaService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<AddResponse> AddAsync(AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.CargaAsincronica entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.CargaAsincronica entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public FGA.Models.CargaAsincronica[] GetPendientesAsyc() {
            return base.Channel.GetPendientesAsyc();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.CargaAsincronica[]> GetPendientesAsycAsync() {
            return base.Channel.GetPendientesAsycAsync();
        }
    }
}
