//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.BCCR_IndicadoresService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndicadorRecienteDTO", Namespace="http://schemas.datacontract.org/2004/07/Concrete")]
    [System.SerializableAttribute()]
    public partial class IndicadorRecienteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ind_PorcentajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ind_Porcentaje {
            get {
                return this.Ind_PorcentajeField;
            }
            set {
                if ((object.ReferenceEquals(this.Ind_PorcentajeField, value) != true)) {
                    this.Ind_PorcentajeField = value;
                    this.RaisePropertyChanged("Ind_Porcentaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BCCR_IndicadoresService.IBCCR_IndicadoresService")]
    public interface IBCCR_IndicadoresService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/GetAll", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetAllResponse")]
        FGA.Models.BCCR_Indicadores[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/GetAll", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.BCCR_Indicadores[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Get", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetResponse")]
        FGA.Models.BCCR_Indicadores Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Get", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.BCCR_Indicadores> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/GetByType", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetByTypeResponse")]
        FGA.Models.BCCR_Indicadores[] GetByType(int idType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/GetByType", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetByTypeResponse")]
        System.Threading.Tasks.Task<FGA.Models.BCCR_Indicadores[]> GetByTypeAsync(int idType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Add", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/AddResponse")]
        FGA_En_Linea.BCCR_IndicadoresService.AddResponse Add(FGA_En_Linea.BCCR_IndicadoresService.AddRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Add", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.BCCR_IndicadoresService.AddResponse> AddAsync(FGA_En_Linea.BCCR_IndicadoresService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Update", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/UpdateResponse")]
        void Update(FGA.Models.BCCR_Indicadores entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Update", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.BCCR_Indicadores entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Delete", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/Delete", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/GetUltimosValoresPorIndicador", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetUltimosValoresPorIndicadorResponse" +
            "")]
        FGA_En_Linea.BCCR_IndicadoresService.IndicadorRecienteDTO[] GetUltimosValoresPorIndicador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCCR_IndicadoresService/GetUltimosValoresPorIndicador", ReplyAction="http://tempuri.org/IBCCR_IndicadoresService/GetUltimosValoresPorIndicadorResponse" +
            "")]
        System.Threading.Tasks.Task<FGA_En_Linea.BCCR_IndicadoresService.IndicadorRecienteDTO[]> GetUltimosValoresPorIndicadorAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.BCCR_Indicadores entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.BCCR_Indicadores entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.BCCR_Indicadores entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.BCCR_Indicadores entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBCCR_IndicadoresServiceChannel : FGA_En_Linea.BCCR_IndicadoresService.IBCCR_IndicadoresService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BCCR_IndicadoresServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.BCCR_IndicadoresService.IBCCR_IndicadoresService>, FGA_En_Linea.BCCR_IndicadoresService.IBCCR_IndicadoresService {
        
        public BCCR_IndicadoresServiceClient() {
        }
        
        public BCCR_IndicadoresServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BCCR_IndicadoresServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BCCR_IndicadoresServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BCCR_IndicadoresServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.BCCR_Indicadores[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.BCCR_Indicadores[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.BCCR_Indicadores Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.BCCR_Indicadores> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        public FGA.Models.BCCR_Indicadores[] GetByType(int idType) {
            return base.Channel.GetByType(idType);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.BCCR_Indicadores[]> GetByTypeAsync(int idType) {
            return base.Channel.GetByTypeAsync(idType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.BCCR_IndicadoresService.AddResponse FGA_En_Linea.BCCR_IndicadoresService.IBCCR_IndicadoresService.Add(FGA_En_Linea.BCCR_IndicadoresService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.BCCR_Indicadores entity) {
            FGA_En_Linea.BCCR_IndicadoresService.AddRequest inValue = new FGA_En_Linea.BCCR_IndicadoresService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.BCCR_IndicadoresService.AddResponse retVal = ((FGA_En_Linea.BCCR_IndicadoresService.IBCCR_IndicadoresService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.BCCR_IndicadoresService.AddResponse> AddAsync(FGA_En_Linea.BCCR_IndicadoresService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.BCCR_Indicadores entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.BCCR_Indicadores entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public FGA_En_Linea.BCCR_IndicadoresService.IndicadorRecienteDTO[] GetUltimosValoresPorIndicador() {
            return base.Channel.GetUltimosValoresPorIndicador();
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.BCCR_IndicadoresService.IndicadorRecienteDTO[]> GetUltimosValoresPorIndicadorAsync() {
            return base.Channel.GetUltimosValoresPorIndicadorAsync();
        }
    }
}
