//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.XML_EncabezadoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XML_EncabezadoService.IXML_EncabezadoService")]
    public interface IXML_EncabezadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/GetByCompany", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetByCompanyResponse")]
        FGA.Models.XML_Encabezado[] GetByCompany(string idEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/GetByCompany", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetByCompanyResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Encabezado[]> GetByCompanyAsync(string idEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/GetMonthFiles", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetMonthFilesResponse")]
        FGA.Models.XML_Encabezado[] GetMonthFiles(string idEntidad, System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/GetMonthFiles", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetMonthFilesResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Encabezado[]> GetMonthFilesAsync(string idEntidad, System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/IsLoadingFile", ReplyAction="http://tempuri.org/IXML_EncabezadoService/IsLoadingFileResponse")]
        bool IsLoadingFile(string idEntidad, System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/IsLoadingFile", ReplyAction="http://tempuri.org/IXML_EncabezadoService/IsLoadingFileResponse")]
        System.Threading.Tasks.Task<bool> IsLoadingFileAsync(string idEntidad, System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/IsUpload", ReplyAction="http://tempuri.org/IXML_EncabezadoService/IsUploadResponse")]
        bool IsUpload(string idEntidad, string idArchivo, System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/IsUpload", ReplyAction="http://tempuri.org/IXML_EncabezadoService/IsUploadResponse")]
        System.Threading.Tasks.Task<bool> IsUploadAsync(string idEntidad, string idArchivo, System.DateTime periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/GetAll", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetAllResponse")]
        FGA.Models.XML_Encabezado[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/GetAll", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Encabezado[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Get", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetResponse")]
        FGA.Models.XML_Encabezado Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Get", ReplyAction="http://tempuri.org/IXML_EncabezadoService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Encabezado> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Add", ReplyAction="http://tempuri.org/IXML_EncabezadoService/AddResponse")]
        FGA_En_Linea.XML_EncabezadoService.AddResponse Add(FGA_En_Linea.XML_EncabezadoService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Add", ReplyAction="http://tempuri.org/IXML_EncabezadoService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.XML_EncabezadoService.AddResponse> AddAsync(FGA_En_Linea.XML_EncabezadoService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Update", ReplyAction="http://tempuri.org/IXML_EncabezadoService/UpdateResponse")]
        void Update(FGA.Models.XML_Encabezado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Update", ReplyAction="http://tempuri.org/IXML_EncabezadoService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.XML_Encabezado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Delete", ReplyAction="http://tempuri.org/IXML_EncabezadoService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_EncabezadoService/Delete", ReplyAction="http://tempuri.org/IXML_EncabezadoService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.XML_Encabezado entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.XML_Encabezado entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.XML_Encabezado entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.XML_Encabezado entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXML_EncabezadoServiceChannel : FGA_En_Linea.XML_EncabezadoService.IXML_EncabezadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XML_EncabezadoServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.XML_EncabezadoService.IXML_EncabezadoService>, FGA_En_Linea.XML_EncabezadoService.IXML_EncabezadoService {
        
        public XML_EncabezadoServiceClient() {
        }
        
        public XML_EncabezadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XML_EncabezadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XML_EncabezadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XML_EncabezadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.XML_Encabezado[] GetByCompany(string idEntidad) {
            return base.Channel.GetByCompany(idEntidad);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Encabezado[]> GetByCompanyAsync(string idEntidad) {
            return base.Channel.GetByCompanyAsync(idEntidad);
        }
        
        public FGA.Models.XML_Encabezado[] GetMonthFiles(string idEntidad, System.DateTime periodo) {
            return base.Channel.GetMonthFiles(idEntidad, periodo);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Encabezado[]> GetMonthFilesAsync(string idEntidad, System.DateTime periodo) {
            return base.Channel.GetMonthFilesAsync(idEntidad, periodo);
        }
        
        public bool IsLoadingFile(string idEntidad, System.DateTime periodo) {
            return base.Channel.IsLoadingFile(idEntidad, periodo);
        }
        
        public System.Threading.Tasks.Task<bool> IsLoadingFileAsync(string idEntidad, System.DateTime periodo) {
            return base.Channel.IsLoadingFileAsync(idEntidad, periodo);
        }
        
        public bool IsUpload(string idEntidad, string idArchivo, System.DateTime periodo) {
            return base.Channel.IsUpload(idEntidad, idArchivo, periodo);
        }
        
        public System.Threading.Tasks.Task<bool> IsUploadAsync(string idEntidad, string idArchivo, System.DateTime periodo) {
            return base.Channel.IsUploadAsync(idEntidad, idArchivo, periodo);
        }
        
        public FGA.Models.XML_Encabezado[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Encabezado[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.XML_Encabezado Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Encabezado> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.XML_EncabezadoService.AddResponse FGA_En_Linea.XML_EncabezadoService.IXML_EncabezadoService.Add(FGA_En_Linea.XML_EncabezadoService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.XML_Encabezado entity) {
            FGA_En_Linea.XML_EncabezadoService.AddRequest inValue = new FGA_En_Linea.XML_EncabezadoService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.XML_EncabezadoService.AddResponse retVal = ((FGA_En_Linea.XML_EncabezadoService.IXML_EncabezadoService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.XML_EncabezadoService.AddResponse> AddAsync(FGA_En_Linea.XML_EncabezadoService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.XML_Encabezado entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.XML_Encabezado entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
