//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.ArchivoEstadoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArchivoEstadoService.IServiceOf_ArchivoEstado")]
    public interface IServiceOf_ArchivoEstado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/GetAll", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/GetAllResponse")]
        FGA.Models.ArchivoEstado[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/GetAll", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.ArchivoEstado[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Get", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/GetResponse")]
        FGA.Models.ArchivoEstado Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Get", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.ArchivoEstado> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Add", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/AddResponse")]
        FGA_En_Linea.ArchivoEstadoService.AddResponse Add(FGA_En_Linea.ArchivoEstadoService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Add", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.ArchivoEstadoService.AddResponse> AddAsync(FGA_En_Linea.ArchivoEstadoService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Update", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/UpdateResponse")]
        void Update(FGA.Models.ArchivoEstado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Update", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.ArchivoEstado entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Delete", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_ArchivoEstado/Delete", ReplyAction="http://tempuri.org/IServiceOf_ArchivoEstado/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.ArchivoEstado entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.ArchivoEstado entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.ArchivoEstado entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.ArchivoEstado entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_ArchivoEstadoChannel : FGA_En_Linea.ArchivoEstadoService.IServiceOf_ArchivoEstado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_ArchivoEstadoClient : System.ServiceModel.ClientBase<FGA_En_Linea.ArchivoEstadoService.IServiceOf_ArchivoEstado>, FGA_En_Linea.ArchivoEstadoService.IServiceOf_ArchivoEstado {
        
        public ServiceOf_ArchivoEstadoClient() {
        }
        
        public ServiceOf_ArchivoEstadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_ArchivoEstadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_ArchivoEstadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_ArchivoEstadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.ArchivoEstado[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.ArchivoEstado[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.ArchivoEstado Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.ArchivoEstado> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.ArchivoEstadoService.AddResponse FGA_En_Linea.ArchivoEstadoService.IServiceOf_ArchivoEstado.Add(FGA_En_Linea.ArchivoEstadoService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.ArchivoEstado entity) {
            FGA_En_Linea.ArchivoEstadoService.AddRequest inValue = new FGA_En_Linea.ArchivoEstadoService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.ArchivoEstadoService.AddResponse retVal = ((FGA_En_Linea.ArchivoEstadoService.IServiceOf_ArchivoEstado)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.ArchivoEstadoService.AddResponse> AddAsync(FGA_En_Linea.ArchivoEstadoService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.ArchivoEstado entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.ArchivoEstado entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
