//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.RoleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoleService.IServiceOf_Role")]
    public interface IServiceOf_Role {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Role/GetAllResponse")]
        FGA.Models.Role[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Role/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Role[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Get", ReplyAction="http://tempuri.org/IServiceOf_Role/GetResponse")]
        FGA.Models.Role Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Get", ReplyAction="http://tempuri.org/IServiceOf_Role/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Role> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Add", ReplyAction="http://tempuri.org/IServiceOf_Role/AddResponse")]
        FGA_En_Linea.RoleService.AddResponse Add(FGA_En_Linea.RoleService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Add", ReplyAction="http://tempuri.org/IServiceOf_Role/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.RoleService.AddResponse> AddAsync(FGA_En_Linea.RoleService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Update", ReplyAction="http://tempuri.org/IServiceOf_Role/UpdateResponse")]
        void Update(FGA.Models.Role entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Update", ReplyAction="http://tempuri.org/IServiceOf_Role/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Role entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Delete", ReplyAction="http://tempuri.org/IServiceOf_Role/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Role/Delete", ReplyAction="http://tempuri.org/IServiceOf_Role/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Role entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Role entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Role entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Role entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_RoleChannel : FGA_En_Linea.RoleService.IServiceOf_Role, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_RoleClient : System.ServiceModel.ClientBase<FGA_En_Linea.RoleService.IServiceOf_Role>, FGA_En_Linea.RoleService.IServiceOf_Role {
        
        public ServiceOf_RoleClient() {
        }
        
        public ServiceOf_RoleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_RoleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_RoleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_RoleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Role[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Role[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Role Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Role> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.RoleService.AddResponse FGA_En_Linea.RoleService.IServiceOf_Role.Add(FGA_En_Linea.RoleService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Role entity) {
            FGA_En_Linea.RoleService.AddRequest inValue = new FGA_En_Linea.RoleService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.RoleService.AddResponse retVal = ((FGA_En_Linea.RoleService.IServiceOf_Role)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.RoleService.AddResponse> AddAsync(FGA_En_Linea.RoleService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Role entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Role entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
