//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.ProcessFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessFileService.IProcessFileService")]
    public interface IProcessFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFileService/SaveFile", ReplyAction="http://tempuri.org/IProcessFileService/SaveFileResponse")]
        string SaveFile(string zipPath, string fileName, string idEntidad, int idUsuario, System.DateTime fechaCarga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFileService/SaveFile", ReplyAction="http://tempuri.org/IProcessFileService/SaveFileResponse")]
        System.Threading.Tasks.Task<string> SaveFileAsync(string zipPath, string fileName, string idEntidad, int idUsuario, System.DateTime fechaCarga);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProcessFileService/ProcessIndustria")]
        void ProcessIndustria(string xlsPath, long idEncabezado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProcessFileService/ProcessIndustria")]
        System.Threading.Tasks.Task ProcessIndustriaAsync(string xlsPath, long idEncabezado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProcessFileService/ProcessIndicador")]
        void ProcessIndicador(string xlsPath, long idEncabezado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProcessFileService/ProcessIndicador")]
        System.Threading.Tasks.Task ProcessIndicadorAsync(string xlsPath, long idEncabezado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProcessFileService/ProcessCartera")]
        void ProcessCartera(string xlsPath, long idEncabezado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IProcessFileService/ProcessCartera")]
        System.Threading.Tasks.Task ProcessCarteraAsync(string xlsPath, long idEncabezado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessFileServiceChannel : FGA_En_Linea.ProcessFileService.IProcessFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessFileServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.ProcessFileService.IProcessFileService>, FGA_En_Linea.ProcessFileService.IProcessFileService {
        
        public ProcessFileServiceClient() {
        }
        
        public ProcessFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveFile(string zipPath, string fileName, string idEntidad, int idUsuario, System.DateTime fechaCarga) {
            return base.Channel.SaveFile(zipPath, fileName, idEntidad, idUsuario, fechaCarga);
        }
        
        public System.Threading.Tasks.Task<string> SaveFileAsync(string zipPath, string fileName, string idEntidad, int idUsuario, System.DateTime fechaCarga) {
            return base.Channel.SaveFileAsync(zipPath, fileName, idEntidad, idUsuario, fechaCarga);
        }
        
        public void ProcessIndustria(string xlsPath, long idEncabezado) {
            base.Channel.ProcessIndustria(xlsPath, idEncabezado);
        }
        
        public System.Threading.Tasks.Task ProcessIndustriaAsync(string xlsPath, long idEncabezado) {
            return base.Channel.ProcessIndustriaAsync(xlsPath, idEncabezado);
        }
        
        public void ProcessIndicador(string xlsPath, long idEncabezado) {
            base.Channel.ProcessIndicador(xlsPath, idEncabezado);
        }
        
        public System.Threading.Tasks.Task ProcessIndicadorAsync(string xlsPath, long idEncabezado) {
            return base.Channel.ProcessIndicadorAsync(xlsPath, idEncabezado);
        }
        
        public void ProcessCartera(string xlsPath, long idEncabezado) {
            base.Channel.ProcessCartera(xlsPath, idEncabezado);
        }
        
        public System.Threading.Tasks.Task ProcessCarteraAsync(string xlsPath, long idEncabezado) {
            return base.Channel.ProcessCarteraAsync(xlsPath, idEncabezado);
        }
    }
}
