//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.Rpt_Analisis_VHService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Rpt_Analisis_VHService.IServiceOf_Rpt_Analisis_VH")]
    public interface IServiceOf_Rpt_Analisis_VH {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/GetAllResponse")]
        FGA.Models.Rpt_Analisis_VH[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Rpt_Analisis_VH[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Get", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/GetResponse")]
        FGA.Models.Rpt_Analisis_VH Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Get", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Rpt_Analisis_VH> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Add", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/AddResponse")]
        FGA_En_Linea.Rpt_Analisis_VHService.AddResponse Add(FGA_En_Linea.Rpt_Analisis_VHService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Add", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.Rpt_Analisis_VHService.AddResponse> AddAsync(FGA_En_Linea.Rpt_Analisis_VHService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Update", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/UpdateResponse")]
        void Update(FGA.Models.Rpt_Analisis_VH entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Update", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Rpt_Analisis_VH entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Delete", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/Delete", ReplyAction="http://tempuri.org/IServiceOf_Rpt_Analisis_VH/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Rpt_Analisis_VH entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Rpt_Analisis_VH entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Rpt_Analisis_VH entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Rpt_Analisis_VH entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Rpt_Analisis_VHChannel : FGA_En_Linea.Rpt_Analisis_VHService.IServiceOf_Rpt_Analisis_VH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Rpt_Analisis_VHClient : System.ServiceModel.ClientBase<FGA_En_Linea.Rpt_Analisis_VHService.IServiceOf_Rpt_Analisis_VH>, FGA_En_Linea.Rpt_Analisis_VHService.IServiceOf_Rpt_Analisis_VH {
        
        public ServiceOf_Rpt_Analisis_VHClient() {
        }
        
        public ServiceOf_Rpt_Analisis_VHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Rpt_Analisis_VHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Rpt_Analisis_VHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Rpt_Analisis_VHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Rpt_Analisis_VH[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Rpt_Analisis_VH[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Rpt_Analisis_VH Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Rpt_Analisis_VH> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.Rpt_Analisis_VHService.AddResponse FGA_En_Linea.Rpt_Analisis_VHService.IServiceOf_Rpt_Analisis_VH.Add(FGA_En_Linea.Rpt_Analisis_VHService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Rpt_Analisis_VH entity) {
            FGA_En_Linea.Rpt_Analisis_VHService.AddRequest inValue = new FGA_En_Linea.Rpt_Analisis_VHService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.Rpt_Analisis_VHService.AddResponse retVal = ((FGA_En_Linea.Rpt_Analisis_VHService.IServiceOf_Rpt_Analisis_VH)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.Rpt_Analisis_VHService.AddResponse> AddAsync(FGA_En_Linea.Rpt_Analisis_VHService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Rpt_Analisis_VH entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Rpt_Analisis_VH entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
