//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.MenuPermissionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuPermissionService.IMenuPermissionService")]
    public interface IMenuPermissionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/GetMenu", ReplyAction="http://tempuri.org/IMenuPermissionService/GetMenuResponse")]
        FGA.Models.MenuPermission[] GetMenu(int role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/GetMenu", ReplyAction="http://tempuri.org/IMenuPermissionService/GetMenuResponse")]
        System.Threading.Tasks.Task<FGA.Models.MenuPermission[]> GetMenuAsync(int role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/GetAll", ReplyAction="http://tempuri.org/IMenuPermissionService/GetAllResponse")]
        FGA.Models.MenuPermission[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/GetAll", ReplyAction="http://tempuri.org/IMenuPermissionService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.MenuPermission[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Get", ReplyAction="http://tempuri.org/IMenuPermissionService/GetResponse")]
        FGA.Models.MenuPermission Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Get", ReplyAction="http://tempuri.org/IMenuPermissionService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.MenuPermission> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Add", ReplyAction="http://tempuri.org/IMenuPermissionService/AddResponse")]
        FGA_En_Linea.MenuPermissionService.AddResponse Add(FGA_En_Linea.MenuPermissionService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Add", ReplyAction="http://tempuri.org/IMenuPermissionService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.MenuPermissionService.AddResponse> AddAsync(FGA_En_Linea.MenuPermissionService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Update", ReplyAction="http://tempuri.org/IMenuPermissionService/UpdateResponse")]
        void Update(FGA.Models.MenuPermission entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Update", ReplyAction="http://tempuri.org/IMenuPermissionService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.MenuPermission entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Delete", ReplyAction="http://tempuri.org/IMenuPermissionService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuPermissionService/Delete", ReplyAction="http://tempuri.org/IMenuPermissionService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.MenuPermission entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.MenuPermission entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.MenuPermission entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.MenuPermission entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuPermissionServiceChannel : FGA_En_Linea.MenuPermissionService.IMenuPermissionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuPermissionServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.MenuPermissionService.IMenuPermissionService>, FGA_En_Linea.MenuPermissionService.IMenuPermissionService {
        
        public MenuPermissionServiceClient() {
        }
        
        public MenuPermissionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuPermissionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuPermissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuPermissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.MenuPermission[] GetMenu(int role) {
            return base.Channel.GetMenu(role);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.MenuPermission[]> GetMenuAsync(int role) {
            return base.Channel.GetMenuAsync(role);
        }
        
        public FGA.Models.MenuPermission[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.MenuPermission[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.MenuPermission Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.MenuPermission> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.MenuPermissionService.AddResponse FGA_En_Linea.MenuPermissionService.IMenuPermissionService.Add(FGA_En_Linea.MenuPermissionService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.MenuPermission entity) {
            FGA_En_Linea.MenuPermissionService.AddRequest inValue = new FGA_En_Linea.MenuPermissionService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.MenuPermissionService.AddResponse retVal = ((FGA_En_Linea.MenuPermissionService.IMenuPermissionService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.MenuPermissionService.AddResponse> AddAsync(FGA_En_Linea.MenuPermissionService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.MenuPermission entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.MenuPermission entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
