//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.XML_ErrorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XML_ErrorService.IXML_ErrorService")]
    public interface IXML_ErrorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/GetByEncabezado", ReplyAction="http://tempuri.org/IXML_ErrorService/GetByEncabezadoResponse")]
        FGA.Models.XML_Errores[] GetByEncabezado(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/GetByEncabezado", ReplyAction="http://tempuri.org/IXML_ErrorService/GetByEncabezadoResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Errores[]> GetByEncabezadoAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/GetAll", ReplyAction="http://tempuri.org/IXML_ErrorService/GetAllResponse")]
        FGA.Models.XML_Errores[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/GetAll", ReplyAction="http://tempuri.org/IXML_ErrorService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Errores[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Get", ReplyAction="http://tempuri.org/IXML_ErrorService/GetResponse")]
        FGA.Models.XML_Errores Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Get", ReplyAction="http://tempuri.org/IXML_ErrorService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.XML_Errores> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Add", ReplyAction="http://tempuri.org/IXML_ErrorService/AddResponse")]
        FGA_En_Linea.XML_ErrorService.AddResponse Add(FGA_En_Linea.XML_ErrorService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Add", ReplyAction="http://tempuri.org/IXML_ErrorService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.XML_ErrorService.AddResponse> AddAsync(FGA_En_Linea.XML_ErrorService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Update", ReplyAction="http://tempuri.org/IXML_ErrorService/UpdateResponse")]
        void Update(FGA.Models.XML_Errores entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Update", ReplyAction="http://tempuri.org/IXML_ErrorService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.XML_Errores entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Delete", ReplyAction="http://tempuri.org/IXML_ErrorService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXML_ErrorService/Delete", ReplyAction="http://tempuri.org/IXML_ErrorService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.XML_Errores entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.XML_Errores entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.XML_Errores entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.XML_Errores entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXML_ErrorServiceChannel : FGA_En_Linea.XML_ErrorService.IXML_ErrorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XML_ErrorServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.XML_ErrorService.IXML_ErrorService>, FGA_En_Linea.XML_ErrorService.IXML_ErrorService {
        
        public XML_ErrorServiceClient() {
        }
        
        public XML_ErrorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XML_ErrorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XML_ErrorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XML_ErrorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.XML_Errores[] GetByEncabezado(long id) {
            return base.Channel.GetByEncabezado(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Errores[]> GetByEncabezadoAsync(long id) {
            return base.Channel.GetByEncabezadoAsync(id);
        }
        
        public FGA.Models.XML_Errores[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Errores[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.XML_Errores Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.XML_Errores> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.XML_ErrorService.AddResponse FGA_En_Linea.XML_ErrorService.IXML_ErrorService.Add(FGA_En_Linea.XML_ErrorService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.XML_Errores entity) {
            FGA_En_Linea.XML_ErrorService.AddRequest inValue = new FGA_En_Linea.XML_ErrorService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.XML_ErrorService.AddResponse retVal = ((FGA_En_Linea.XML_ErrorService.IXML_ErrorService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.XML_ErrorService.AddResponse> AddAsync(FGA_En_Linea.XML_ErrorService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.XML_Errores entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.XML_Errores entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
