//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.EvalRespuestaUsuarioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvalRespuestaUsuarioService.IServiceOf_EvalRespuestaUsuario")]
    public interface IServiceOf_EvalRespuestaUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/GetAll", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/GetAllResponse")]
        Entities.Entities.Evaluacion.EvalRespuestaUsuario[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/GetAll", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/GetAllResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalRespuestaUsuario[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Get", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/GetResponse")]
        Entities.Entities.Evaluacion.EvalRespuestaUsuario Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Get", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/GetResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalRespuestaUsuario> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Add", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/AddResponse")]
        FGA_En_Linea.EvalRespuestaUsuarioService.AddResponse Add(FGA_En_Linea.EvalRespuestaUsuarioService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Add", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.EvalRespuestaUsuarioService.AddResponse> AddAsync(FGA_En_Linea.EvalRespuestaUsuarioService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Update", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/UpdateResponse")]
        void Update(Entities.Entities.Evaluacion.EvalRespuestaUsuario entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Update", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalRespuestaUsuario entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Delete", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/Delete", ReplyAction="http://tempuri.org/IServiceOf_EvalRespuestaUsuario/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalRespuestaUsuario entity;
        
        public AddRequest() {
        }
        
        public AddRequest(Entities.Entities.Evaluacion.EvalRespuestaUsuario entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalRespuestaUsuario entity;
        
        public AddResponse() {
        }
        
        public AddResponse(Entities.Entities.Evaluacion.EvalRespuestaUsuario entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_EvalRespuestaUsuarioChannel : FGA_En_Linea.EvalRespuestaUsuarioService.IServiceOf_EvalRespuestaUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_EvalRespuestaUsuarioClient : System.ServiceModel.ClientBase<FGA_En_Linea.EvalRespuestaUsuarioService.IServiceOf_EvalRespuestaUsuario>, FGA_En_Linea.EvalRespuestaUsuarioService.IServiceOf_EvalRespuestaUsuario {
        
        public ServiceOf_EvalRespuestaUsuarioClient() {
        }
        
        public ServiceOf_EvalRespuestaUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_EvalRespuestaUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_EvalRespuestaUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_EvalRespuestaUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Entities.Evaluacion.EvalRespuestaUsuario[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalRespuestaUsuario[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Entities.Entities.Evaluacion.EvalRespuestaUsuario Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalRespuestaUsuario> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.EvalRespuestaUsuarioService.AddResponse FGA_En_Linea.EvalRespuestaUsuarioService.IServiceOf_EvalRespuestaUsuario.Add(FGA_En_Linea.EvalRespuestaUsuarioService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref Entities.Entities.Evaluacion.EvalRespuestaUsuario entity) {
            FGA_En_Linea.EvalRespuestaUsuarioService.AddRequest inValue = new FGA_En_Linea.EvalRespuestaUsuarioService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.EvalRespuestaUsuarioService.AddResponse retVal = ((FGA_En_Linea.EvalRespuestaUsuarioService.IServiceOf_EvalRespuestaUsuario)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.EvalRespuestaUsuarioService.AddResponse> AddAsync(FGA_En_Linea.EvalRespuestaUsuarioService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(Entities.Entities.Evaluacion.EvalRespuestaUsuario entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalRespuestaUsuario entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
