//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.Proy_EEFFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proy_EEFFService.IProy_EEFFService")]
    public interface IProy_EEFFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/GetProy", ReplyAction="http://tempuri.org/IProy_EEFFService/GetProyResponse")]
        FGA.Models.Proy_EEFF GetProy(string idEntidad, System.DateTime PeriodoCorte, string TipoPlazo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/GetProy", ReplyAction="http://tempuri.org/IProy_EEFFService/GetProyResponse")]
        System.Threading.Tasks.Task<FGA.Models.Proy_EEFF> GetProyAsync(string idEntidad, System.DateTime PeriodoCorte, string TipoPlazo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/GetAll", ReplyAction="http://tempuri.org/IProy_EEFFService/GetAllResponse")]
        FGA.Models.Proy_EEFF[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/GetAll", ReplyAction="http://tempuri.org/IProy_EEFFService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Proy_EEFF[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Get", ReplyAction="http://tempuri.org/IProy_EEFFService/GetResponse")]
        FGA.Models.Proy_EEFF Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Get", ReplyAction="http://tempuri.org/IProy_EEFFService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Proy_EEFF> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Add", ReplyAction="http://tempuri.org/IProy_EEFFService/AddResponse")]
        FGA_En_Linea.Proy_EEFFService.AddResponse Add(FGA_En_Linea.Proy_EEFFService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Add", ReplyAction="http://tempuri.org/IProy_EEFFService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.Proy_EEFFService.AddResponse> AddAsync(FGA_En_Linea.Proy_EEFFService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Update", ReplyAction="http://tempuri.org/IProy_EEFFService/UpdateResponse")]
        void Update(FGA.Models.Proy_EEFF entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Update", ReplyAction="http://tempuri.org/IProy_EEFFService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Proy_EEFF entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Delete", ReplyAction="http://tempuri.org/IProy_EEFFService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProy_EEFFService/Delete", ReplyAction="http://tempuri.org/IProy_EEFFService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Proy_EEFF entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Proy_EEFF entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Proy_EEFF entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Proy_EEFF entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProy_EEFFServiceChannel : FGA_En_Linea.Proy_EEFFService.IProy_EEFFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Proy_EEFFServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.Proy_EEFFService.IProy_EEFFService>, FGA_En_Linea.Proy_EEFFService.IProy_EEFFService {
        
        public Proy_EEFFServiceClient() {
        }
        
        public Proy_EEFFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Proy_EEFFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Proy_EEFFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Proy_EEFFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Proy_EEFF GetProy(string idEntidad, System.DateTime PeriodoCorte, string TipoPlazo) {
            return base.Channel.GetProy(idEntidad, PeriodoCorte, TipoPlazo);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Proy_EEFF> GetProyAsync(string idEntidad, System.DateTime PeriodoCorte, string TipoPlazo) {
            return base.Channel.GetProyAsync(idEntidad, PeriodoCorte, TipoPlazo);
        }
        
        public FGA.Models.Proy_EEFF[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Proy_EEFF[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Proy_EEFF Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Proy_EEFF> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.Proy_EEFFService.AddResponse FGA_En_Linea.Proy_EEFFService.IProy_EEFFService.Add(FGA_En_Linea.Proy_EEFFService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Proy_EEFF entity) {
            FGA_En_Linea.Proy_EEFFService.AddRequest inValue = new FGA_En_Linea.Proy_EEFFService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.Proy_EEFFService.AddResponse retVal = ((FGA_En_Linea.Proy_EEFFService.IProy_EEFFService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.Proy_EEFFService.AddResponse> AddAsync(FGA_En_Linea.Proy_EEFFService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Proy_EEFF entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Proy_EEFF entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
