//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.SeccionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeccionService.IServiceOf_Seccion")]
    public interface IServiceOf_Seccion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Seccion/GetAllResponse")]
        FGA.Models.Seccion[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Seccion/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Seccion[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Get", ReplyAction="http://tempuri.org/IServiceOf_Seccion/GetResponse")]
        FGA.Models.Seccion Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Get", ReplyAction="http://tempuri.org/IServiceOf_Seccion/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Seccion> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Add", ReplyAction="http://tempuri.org/IServiceOf_Seccion/AddResponse")]
        FGA_En_Linea.SeccionService.AddResponse Add(FGA_En_Linea.SeccionService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Add", ReplyAction="http://tempuri.org/IServiceOf_Seccion/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.SeccionService.AddResponse> AddAsync(FGA_En_Linea.SeccionService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Update", ReplyAction="http://tempuri.org/IServiceOf_Seccion/UpdateResponse")]
        void Update(FGA.Models.Seccion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Update", ReplyAction="http://tempuri.org/IServiceOf_Seccion/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Seccion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Delete", ReplyAction="http://tempuri.org/IServiceOf_Seccion/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Seccion/Delete", ReplyAction="http://tempuri.org/IServiceOf_Seccion/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Seccion entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Seccion entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Seccion entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Seccion entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_SeccionChannel : FGA_En_Linea.SeccionService.IServiceOf_Seccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_SeccionClient : System.ServiceModel.ClientBase<FGA_En_Linea.SeccionService.IServiceOf_Seccion>, FGA_En_Linea.SeccionService.IServiceOf_Seccion {
        
        public ServiceOf_SeccionClient() {
        }
        
        public ServiceOf_SeccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_SeccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_SeccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_SeccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Seccion[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Seccion[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Seccion Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Seccion> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.SeccionService.AddResponse FGA_En_Linea.SeccionService.IServiceOf_Seccion.Add(FGA_En_Linea.SeccionService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Seccion entity) {
            FGA_En_Linea.SeccionService.AddRequest inValue = new FGA_En_Linea.SeccionService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.SeccionService.AddResponse retVal = ((FGA_En_Linea.SeccionService.IServiceOf_Seccion)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.SeccionService.AddResponse> AddAsync(FGA_En_Linea.SeccionService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Seccion entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Seccion entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
