//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.UsuarioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioService.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByEmail", ReplyAction="http://tempuri.org/IUsuarioService/GetByEmailResponse")]
        FGA.Models.Usuario GetByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByEmail", ReplyAction="http://tempuri.org/IUsuarioService/GetByEmailResponse")]
        System.Threading.Tasks.Task<FGA.Models.Usuario> GetByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByCredentials", ReplyAction="http://tempuri.org/IUsuarioService/GetByCredentialsResponse")]
        FGA.Models.Usuario GetByCredentials(string id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByCredentials", ReplyAction="http://tempuri.org/IUsuarioService/GetByCredentialsResponse")]
        System.Threading.Tasks.Task<FGA.Models.Usuario> GetByCredentialsAsync(string id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByIden", ReplyAction="http://tempuri.org/IUsuarioService/GetByIdenResponse")]
        FGA.Models.Usuario GetByIden(string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByIden", ReplyAction="http://tempuri.org/IUsuarioService/GetByIdenResponse")]
        System.Threading.Tasks.Task<FGA.Models.Usuario> GetByIdenAsync(string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByCompany", ReplyAction="http://tempuri.org/IUsuarioService/GetByCompanyResponse")]
        FGA.Models.Usuario[] GetByCompany(string idEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetByCompany", ReplyAction="http://tempuri.org/IUsuarioService/GetByCompanyResponse")]
        System.Threading.Tasks.Task<FGA.Models.Usuario[]> GetByCompanyAsync(string idEntidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetAll", ReplyAction="http://tempuri.org/IUsuarioService/GetAllResponse")]
        FGA.Models.Usuario[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/GetAll", ReplyAction="http://tempuri.org/IUsuarioService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Usuario[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Get", ReplyAction="http://tempuri.org/IUsuarioService/GetResponse")]
        FGA.Models.Usuario Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Get", ReplyAction="http://tempuri.org/IUsuarioService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Usuario> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Add", ReplyAction="http://tempuri.org/IUsuarioService/AddResponse")]
        FGA_En_Linea.UsuarioService.AddResponse Add(FGA_En_Linea.UsuarioService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Add", ReplyAction="http://tempuri.org/IUsuarioService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.UsuarioService.AddResponse> AddAsync(FGA_En_Linea.UsuarioService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Update", ReplyAction="http://tempuri.org/IUsuarioService/UpdateResponse")]
        void Update(FGA.Models.Usuario entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Update", ReplyAction="http://tempuri.org/IUsuarioService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Usuario entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Delete", ReplyAction="http://tempuri.org/IUsuarioService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Delete", ReplyAction="http://tempuri.org/IUsuarioService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Usuario entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Usuario entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Usuario entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Usuario entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : FGA_En_Linea.UsuarioService.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.UsuarioService.IUsuarioService>, FGA_En_Linea.UsuarioService.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Usuario GetByEmail(string email) {
            return base.Channel.GetByEmail(email);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Usuario> GetByEmailAsync(string email) {
            return base.Channel.GetByEmailAsync(email);
        }
        
        public FGA.Models.Usuario GetByCredentials(string id, string password) {
            return base.Channel.GetByCredentials(id, password);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Usuario> GetByCredentialsAsync(string id, string password) {
            return base.Channel.GetByCredentialsAsync(id, password);
        }
        
        public FGA.Models.Usuario GetByIden(string identificacion) {
            return base.Channel.GetByIden(identificacion);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Usuario> GetByIdenAsync(string identificacion) {
            return base.Channel.GetByIdenAsync(identificacion);
        }
        
        public FGA.Models.Usuario[] GetByCompany(string idEntidad) {
            return base.Channel.GetByCompany(idEntidad);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Usuario[]> GetByCompanyAsync(string idEntidad) {
            return base.Channel.GetByCompanyAsync(idEntidad);
        }
        
        public FGA.Models.Usuario[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Usuario[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Usuario Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Usuario> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.UsuarioService.AddResponse FGA_En_Linea.UsuarioService.IUsuarioService.Add(FGA_En_Linea.UsuarioService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Usuario entity) {
            FGA_En_Linea.UsuarioService.AddRequest inValue = new FGA_En_Linea.UsuarioService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.UsuarioService.AddResponse retVal = ((FGA_En_Linea.UsuarioService.IUsuarioService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.UsuarioService.AddResponse> AddAsync(FGA_En_Linea.UsuarioService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Usuario entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Usuario entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
