USE [FGA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[FGA_Consultar_Dashboard]
	@IDENTIDAD NVARCHAR(5),
	@PERIODOI DATE, 
	@PERIODOF DATE
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @IND_PRUDENCIAL INT 
	SET @IND_PRUDENCIAL = (SELECT Perfil_Entidad_Id FROM ENTIDAD WHERE ID = @IDENTIDAD)
		
	IF @IDENTIDAD = 99 BEGIN
		SET @IDENTIDAD = 13
	END

	SET FMTONLY OFF
	CREATE TABLE #RESUMEN(ID INT, MONTO DECIMAL(35, 2), CALIFICACION DECIMAL(35, 2), PERIODO DATE, IND_PORCENTAJE NVARCHAR(1))	
	
	DECLARE @IPC DECIMAL(10,6)
	DECLARE @FORM_5 DECIMAL(35,2)
	DECLARE @FORM_15 DECIMAL(35,2)

	SET @IPC = (SELECT VARIACIONINTER FROM HIST_IPC WHERE datepart(month, FECHA) = datepart(month, @PERIODOF) and datepart(year, FECHA) = datepart(year, @PERIODOF))
	SET @FORM_5 = (5 / (@IPC / 8 + 5)) * 100
	SET @FORM_15 = (15 / (-@IPC / 8 + 15)) * 100

	/* =========================================================================
	   SECCIÃ“N 1: INDICADORES ORIGINALES (SITIO LEGADO - IDS INTACTOS)
	   ========================================================================= */

	/*COMPROMISO PATRIMONIAL (ID 3)*/			
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO <= 0 THEN 
								CASE WHEN MONTO = 0 AND Monto >= -0.5 THEN 1.45
									 WHEN MONTO < -0.5 AND MONTO >= -1 THEN 1.25 
 									 WHEN MONTO < -1 AND MONTO >= -5 THEN 1 
									 WHEN MONTO < -5 AND MONTO > -10 THEN 0.75 
									 ELSE 0.51 END
				  WHEN MONTO > 0 AND MONTO <= 10 THEN 1.5 + (Monto / 10)
				  WHEN MONTO > 10 AND MONTO <= 20  THEN 2.5 + ((Monto - 10) / 10)
				  WHEN MONTO > 20 THEN
								CASE WHEN Monto <= 20.5 THEN 3.51
									WHEN MONTO > 20.5 AND MONTO <= 21.5 THEN 3.75 
 									WHEN MONTO > 21.5 AND MONTO <= 25 THEN 4 
									WHEN MONTO > 25 AND MONTO < 30 THEN 4.25 
									ELSE 4.49 END
				END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B 
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 3 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

	/*MOROSIDAD (ID 22)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE,
    (SELECT CASE WHEN MONTO <= 5 THEN 
					CASE WHEN MONTO >= 4.80 THEN 1.49
						 WHEN MONTO < 4.80 AND MONTO >= 4 THEN 1.35 
 						 WHEN MONTO < 4 AND MONTO >= 3 THEN 1.2 
						 WHEN MONTO < 3 AND MONTO > 2 THEN 1
						 WHEN MONTO < 2 AND MONTO > 1 THEN 0.75
						 ELSE 0.51 END 
				 WHEN MONTO > 5 AND MONTO <= 7 THEN 1.5 + ((Monto - 5) / 2)
				 WHEN MONTO > 7 AND MONTO <= 12  THEN 2.5 + ((Monto - 7) / 5)
				 WHEN MONTO > 12 THEN 
					CASE WHEN Monto <= 12.5 THEN 3.51
						WHEN MONTO > 12.5 AND MONTO <= 14.5 THEN 3.75 
 						WHEN MONTO > 14.5 AND MONTO <= 16.5 THEN 4 
						WHEN MONTO > 16.5 AND MONTO < 19 THEN 4.25 
						ELSE 4.49 END
					END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 22 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

	/*RIESGO (ID 333)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO <= 5 THEN 
					CASE WHEN MONTO >= 4.80 THEN 1.45
						 WHEN MONTO < 4.80 AND MONTO >= 3 THEN 1.25 
 						 WHEN MONTO < 3 AND MONTO >= 1.5 THEN 1 
						 WHEN MONTO < 1.5 AND MONTO > 0.5 THEN 0.75 
						 ELSE 0.51 END  
				 WHEN MONTO > 5 AND MONTO <= 20 THEN 1.5 + ((Monto - 5) / 15) 
				 WHEN MONTO > 20 AND MONTO <= 35  THEN 2.5 + ((Monto - 20) / 15) 
				 WHEN MONTO > 35 THEN 
					CASE WHEN Monto <= 36 THEN 3.51
						WHEN MONTO > 36 AND MONTO <= 39 THEN 3.75 
 						WHEN MONTO > 39 AND MONTO <= 45 THEN 4 
						WHEN MONTO > 45 AND MONTO < 48 THEN 4.25 
						ELSE 4.49 END
				 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 333 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 
		
	/*ACTIVO (ID 60)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO >= 0.95 THEN 
					CASE WHEN MONTO <= 1 THEN 1.45
						 WHEN MONTO > 1 AND MONTO <= 1.15 THEN 1.25 
 						 WHEN MONTO > 1.15 AND MONTO <= 1.25 THEN 1 
						 WHEN MONTO > 1.25 AND MONTO < 1.35 THEN 0.75 
						 ELSE 0.51 END  
				 WHEN MONTO >= 0.85 AND MONTO < 0.95 THEN 1.5 + ((Monto + 0.15) / 1.10)
				 WHEN MONTO >= 0.75 AND MONTO < 0.85  THEN 2.5 + ((Monto + 0.25) / 1.10)
				 WHEN MONTO < 0.75 THEN 
					CASE WHEN Monto >= 0.70 THEN 3.51
						WHEN MONTO < 0.70 AND MONTO >= 0.60 THEN 3.75 
 						WHEN MONTO < 0.60 AND MONTO >= 0.50 THEN 4 
						WHEN MONTO < 0.5 AND MONTO > 0.35 THEN 4.25 
						ELSE 4.49 END 
					END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID 
	WHERE B.ID = 60 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 
	
	/*COSTO / GASTO DE ADMINISTRACIÃ“N ORIGINAL (ID 118)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO < 75 THEN 0.5 + (Monto / 75)
				 WHEN MONTO < 80 AND MONTO >= 75 THEN 1.5 + ((Monto - 75) / 5) 
				 WHEN MONTO < 90 AND MONTO >= 80 THEN 2.5 + ((Monto - 80) / 10)
				 WHEN MONTO >= 90 THEN 4 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 118 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 
	
	/*SUFICIENCIA ORIGINAL (ID 1, 1100, -1, -2)*/
	IF @IND_PRUDENCIAL = 1 BEGIN
		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 14 THEN 
						CASE WHEN MONTO <= 15 THEN 1.45
							 WHEN MONTO > 15 AND MONTO <= 17 THEN 1.25 
 							 WHEN MONTO > 17 AND MONTO <= 19 THEN 1 
							 WHEN MONTO > 19 AND MONTO < 21 THEN 0.75 
							 ELSE 0.51 END   
					 WHEN MONTO < 14 AND MONTO >= 10 THEN 1.5 + ((14 - Monto) / 4) 
					 WHEN MONTO >= 8 AND MONTO < 10  THEN 2.5 + ((10 - Monto) / 2)
					 WHEN MONTO < 8 THEN 
						CASE WHEN Monto <= 7.5 THEN 3.51
							WHEN MONTO < 7.5 AND MONTO >= 6 THEN 3.75 
 							WHEN MONTO < 6 AND MONTO >= 4 THEN 4 
							WHEN MONTO < 4 AND MONTO > 2 THEN 4.25 
							ELSE 4.49 END 
					END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = 1 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 6 THEN 
						CASE WHEN MONTO <= 7 THEN 1.45
							 WHEN MONTO > 7 AND MONTO <= 10 THEN 1.25 
 							 WHEN MONTO > 10 AND MONTO <= 13 THEN 1 
							 WHEN MONTO > 13 AND MONTO <= 16 THEN 0.75 
							 ELSE 0.51 END   
					 WHEN MONTO < 6 AND MONTO >= 5 THEN 1.5 + (6 - Monto) 
					 WHEN MONTO > 5 AND MONTO < 3  THEN 2.5 + ((5 - Monto) / 2)
					 WHEN MONTO <= 3 THEN 
						CASE WHEN Monto <= 3 THEN 3.51
							WHEN MONTO < 3 AND MONTO >= 2.5 THEN 3.75 
 							WHEN MONTO < 2.5 AND MONTO >= 1.5 THEN 4 
							WHEN MONTO < 1.5 AND MONTO >= 0.75 THEN 4.25 
							ELSE 4.49 END 
					END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA_306 B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA_306 A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = 1100 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

		--CN1
		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 10 THEN 
						CASE WHEN MONTO <= 10 THEN 1.45
							 WHEN MONTO > 10 AND MONTO <= 12 THEN 1.25 
 							 WHEN MONTO > 12 AND MONTO <= 14 THEN 1 
							 WHEN MONTO > 14 AND MONTO < 16 THEN 0.75 
							 ELSE 0.51 END   
					 WHEN MONTO < 10 AND MONTO >= 8 THEN 1.5 + ((10 - Monto) / 2)
					 WHEN MONTO > 8 AND MONTO <= 6  THEN 2.5 + ((8 - Monto) / 2 )
					 WHEN MONTO < 6 THEN 
						CASE WHEN Monto > 5.5 THEN 3.51
							WHEN MONTO > 4.5 AND MONTO <= 4 THEN 3.75 
 							WHEN MONTO > 3 AND MONTO < 4 THEN 4 
							WHEN MONTO > 2 AND MONTO < 3 THEN 4.25 
							ELSE 4.49 END 
					END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA_306 B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA_306 A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = -1 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 7.5 THEN 
						CASE WHEN MONTO <= 7.5 THEN 1.45
							 WHEN MONTO > 7.5 AND MONTO <= 9 THEN 1.25 
 							 WHEN MONTO > 9 AND MONTO <= 11 THEN 1 
							 WHEN MONTO > 11 AND MONTO <= 13 THEN 0.75 
							 ELSE 0.51 END   
					 WHEN MONTO < 7.5 AND MONTO >= 6.5 THEN 1.5 + ((7.5 - Monto))
					 WHEN MONTO < 6.5 AND MONTO >= 4.5  THEN 2.5 + ((6.5 - Monto)/2)
					 WHEN MONTO < 4.5 THEN 
						CASE WHEN Monto >= 4 THEN 3.51
							WHEN MONTO > 3 AND MONTO <= 4 THEN 3.75 
 							WHEN MONTO > 2 AND MONTO <= 3 THEN 4 
							WHEN MONTO > 1 AND MONTO <= 2 THEN 4.25 
							ELSE 4.49 END 
					END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA_306 B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA_306 A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = -2 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

	END ELSE BEGIN
		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 16 THEN 
						CASE WHEN MONTO <= 17 THEN 1.45
							 WHEN MONTO > 17 AND MONTO <= 19 THEN 1.25 
 							 WHEN MONTO > 19 AND MONTO <= 21 THEN 1 
							 WHEN MONTO > 21 AND MONTO < 23 THEN 0.75 
							 ELSE 0.51 END   
					 WHEN MONTO < 16 AND MONTO >= 14 THEN 1.5 + ((Monto - 14) / 2) 
					 WHEN MONTO > 14 AND MONTO <= 12  THEN 2.5 + ((Monto - 12) / 2) 
					 WHEN MONTO < 12 THEN 
						CASE WHEN Monto >= 11 THEN 3.51
							WHEN MONTO < 11 AND MONTO >= 10 THEN 3.75 
 							WHEN MONTO < 10 AND MONTO >= 9 THEN 4.25 
							ELSE 4.49 END 
					END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = 1 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 8 THEN 
						CASE WHEN MONTO <= 9 THEN 1.45
							 WHEN MONTO > 9 AND MONTO <= 12 THEN 1.25 
 							 WHEN MONTO > 12 AND MONTO <= 15 THEN 1 
							 WHEN MONTO > 15 AND MONTO < 18 THEN 0.75 
							 ELSE 0.51 END   
					 WHEN MONTO < 8 AND MONTO >= 7 THEN 1.5 + (8 - Monto) 
					 WHEN MONTO > 7 AND MONTO <= 4  THEN 2.5 + ((7 - Monto) / 3)
					 WHEN MONTO < 4 THEN 
						CASE WHEN Monto >= 3.5 THEN 3.51
							WHEN MONTO < 3.5 AND MONTO >= 2.5 THEN 3.75 
 							WHEN MONTO < 2.5 AND MONTO >= 1.5 THEN 4 
							WHEN MONTO < 1.5 AND MONTO >= 0.75 THEN 4.25 
							ELSE 4.49 END 
					END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA_306 B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA_306 A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = 1100 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 12.5 THEN 
						CASE WHEN MONTO <= 14.5 THEN 1.45
							 WHEN MONTO > 14.5 AND MONTO <= 16.5 THEN 1.25 
 								 WHEN MONTO > 16.5 AND MONTO <= 18.5 THEN 1 
								 WHEN MONTO > 18.5 AND MONTO < 20.5 THEN 0.75 
								 ELSE 0.51 END   
						 WHEN MONTO < 12.5 AND MONTO >= 10 THEN 1.5 + ((12.5 - Monto) / 2.5)
						 WHEN MONTO < 10 AND MONTO >= 7  THEN 2.5 + ((10 - Monto)  / 3)
						 WHEN MONTO < 7 THEN 
							CASE WHEN Monto >= 6 THEN 3.51
								WHEN MONTO > 4.5 AND MONTO <= 6 THEN 3.75 
 								WHEN MONTO > 3 AND MONTO <= 4.5 THEN 4 
								WHEN MONTO > 1.5 AND MONTO <= 3 THEN 4.25 
								ELSE 4.49 END 
						END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA_306 B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA_306 A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = -1 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

		INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
		SELECT B.ID, ISNULL(ROUND(A.MONTO, 2), 0), @PERIODOI, B.IND_PORCENTAJE, 
		(SELECT CASE WHEN MONTO >= 11 THEN 
						CASE WHEN MONTO <= 12 THEN 1.45
							 WHEN MONTO > 12 AND MONTO <= 14 THEN 1.25 
 								 WHEN MONTO > 14 AND MONTO <= 16 THEN 1 
								 WHEN MONTO > 16 AND MONTO <= 18 THEN 0.75 
								 ELSE 0.51 END   
						 WHEN MONTO < 11 AND MONTO >= 8.5 THEN 1.5 + ((11 - Monto) / 2.5)
						 WHEN MONTO < 8.5 AND MONTO >= 6.5  THEN 2.5 + ((8.5 - Monto)/2)
						 WHEN MONTO < 6.5 THEN 
							CASE WHEN Monto >= 6 THEN 3.51
								WHEN MONTO >= 4.5 AND MONTO < 6 THEN 3.75 
 								WHEN MONTO >= 3 AND MONTO < 4.5 THEN 4 
								WHEN MONTO >= 1.5 AND MONTO < 3 THEN 4.25 
								ELSE 4.49 END 
						END)						
		FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA_306 B
		INNER JOIN FGA.DBO.SALIDA_SUFICIENCIA_306 A ON A.IDRPT_SUFICIENCIA = B.ID 
		WHERE B.ID = -2 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

	END

	/*COSTO 1 MES ORIGINAL (ID 192)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO >= 1 THEN 
					CASE WHEN MONTO < 1.3 THEN 1.45
						 WHEN MONTO > 1.3 AND MONTO <= 1.5 THEN 1.25 
 						 WHEN MONTO > 1.5 AND MONTO <= 1.7 THEN 1 
						 WHEN MONTO > 1.7 AND MONTO < 2 THEN 0.75 
						 ELSE 0.51 END   
				 WHEN MONTO < 1 AND MONTO >= 0.83 THEN 2.5 - (Monto-0.83) / 0.17
				 WHEN MONTO >= 0.65 AND MONTO < 0.83 THEN 3.5 - (Monto-0.65) / 0.18 
				 WHEN MONTO < 0.65 THEN 
					CASE WHEN Monto >= 0.6 THEN 3.51
						WHEN MONTO < 0.6 AND MONTO >= 0.45 THEN 3.75 
 						WHEN MONTO < 0.45 AND MONTO >= 0.30 THEN 4 
						WHEN MONTO < 0.30 AND MONTO > 0.15 THEN 4.25 
						ELSE 4.49 END 
			 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 192 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

	/*COSTO 3 MESES ORIGINAL (ID 258)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO >= 0.85 THEN 
					CASE WHEN MONTO <= 0.95 THEN 1.45
						 WHEN MONTO > 0.95 AND MONTO <= 1.5 THEN 1.25 
 						 WHEN MONTO > 1.5 AND MONTO <= 1.7 THEN 1 
						 WHEN MONTO > 1.7 AND MONTO < 2 THEN 0.75 
						 ELSE 0.51 END   
				 WHEN MONTO < 0.85 AND MONTO >= 0.7 THEN 2.5 - (Monto-0.7) / 0.15 
				 WHEN MONTO >= 0.5 AND MONTO < 0.7 THEN 3.5 - (Monto-0.5) / 0.2
				 WHEN MONTO < 0.5 THEN 
					CASE WHEN Monto >= 0.45 THEN 3.51
						WHEN MONTO < 0.45 AND MONTO >= 0.35 THEN 3.75 
 						WHEN MONTO < 0.35 AND MONTO >= 0.25 THEN 4 
						WHEN MONTO < 0.25 AND MONTO > 0.15 THEN 4.25 
						ELSE 4.49 END 
			 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 258 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 
    
	/*PÃ‰RDIDA ESPERADA ORIGINAL (ID 30)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO/100, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO/100 <= 1.7 THEN 
					CASE WHEN MONTO/100 >= 1.6 THEN 1.45
						 WHEN MONTO/100 < 1.6 AND MONTO/100 >= 1.2 THEN 1.25 
 						 WHEN MONTO/100 < 1.2 AND MONTO/100 >= 0.7 THEN 1 
						 WHEN MONTO/100 < 0.7 AND MONTO/100 >= 0.2 THEN 0.75 
						 ELSE 0.51 
					END   
				 WHEN MONTO/100 > 1.7 AND MONTO/100 <= 3.7 THEN 1.5 + (Monto/100-1.7) / 2
				 WHEN MONTO/100 > 3.7 AND MONTO/100 <= 8.6  THEN 2.5 + (Monto/100-3.7) / 5
				 WHEN MONTO/100 > 8.6 THEN 
					CASE WHEN Monto/100 <= 9 THEN 3.51
						WHEN MONTO/100 > 9 AND MONTO/100 <= 10.5 THEN 3.75 
 						WHEN MONTO/100 > 10.5 AND MONTO/100 <= 12 THEN 4 
						WHEN MONTO/100 > 12 AND MONTO/100 <= 13.5 THEN 4.25 
						ELSE 4.49 END 
		 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 30 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 
   
    /*UTILIDAD O PÃ‰RDIDA ACUMULADA ORIGINAL (ID 127)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO >= 1 THEN 
	   			   CASE WHEN MONTO >= 1 AND Monto <= 1.5 THEN 1.45
 						WHEN MONTO > 1.5 AND MONTO <= 2 THEN 1.25 
 						WHEN MONTO > 2 AND MONTO <= 7 THEN 1 
						WHEN MONTO > 7 THEN 0.51 END
				 WHEN MONTO >= 0 THEN 1.5 + (1 - MONTO) 
				 WHEN MONTO >= -10  THEN 
									CASE WHEN MONTO >= -2 THEN 2.51
									WHEN MONTO >= -5 AND MONTO < -2 THEN 2.75 
 									WHEN MONTO >= -7 AND MONTO < -5 THEN 3 
									WHEN MONTO >= -9 AND MONTO < -7 THEN 3.25 
									ELSE 3.49 END
				 WHEN MONTO < -10 THEN 
					 CASE WHEN MONTO >= -12  THEN 3.51
									WHEN MONTO >= -14 AND MONTO < -12 THEN 3.75 
 									WHEN MONTO >= -16 AND MONTO < -14 THEN 4 
									WHEN MONTO >= -18 AND MONTO < -16 THEN 4.25 
									ELSE 4.49 END
			 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 127 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 
   
    /*RIESGO TASAS MONEDA EXTRANJERA ORIGINAL (ID 342)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO <= 5 THEN 
					CASE WHEN MONTO >= 4.80 THEN 1.45
						 WHEN MONTO < 4.80 AND MONTO >= 3 THEN 1.25 
 						 WHEN MONTO < 3 AND MONTO >= 1.5 THEN 1 
						 WHEN MONTO < 1.5 AND MONTO > 0.5 THEN 0.75 
						 ELSE 0.51 END  
				 WHEN MONTO <= 20 THEN 1.5 + ((Monto - 5) / 15)
				 WHEN MONTO <= 35 THEN 2.5 + ((Monto - 20) / 15)
				 WHEN MONTO > 35 THEN 
						CASE WHEN Monto <= 36 THEN 3.51
						WHEN MONTO > 36 AND MONTO <= 39 THEN 3.75 
 						WHEN MONTO > 39 AND MONTO <= 45 THEN 4 
						WHEN MONTO > 45 AND MONTO < 48 THEN 4.25 
						ELSE 4.49 END
				 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 342 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 
   
    /*RIESGO CAMBIARIO ORIGINAL (ID 351)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT B.ID, ISNULL(A.MONTO, 0), @PERIODOI, B.IND_PORCENTAJE, 
	(SELECT CASE WHEN MONTO <= 5 THEN 
					CASE WHEN MONTO >= 4.80 THEN 1.45
						 WHEN MONTO < 4.80 AND MONTO >= 3 THEN 1.25 
 						 WHEN MONTO < 3 AND MONTO >= 1.5 THEN 1 
						 WHEN MONTO < 1.5 AND MONTO > 0.5 THEN 0.75 
						 ELSE 0.51 END  
				 WHEN MONTO <= 20 THEN  1.5 + ((Monto - 5) / 15) 
				 WHEN MONTO <= 35 THEN 2.5 + ((Monto - 20) / 15) 
				 WHEN MONTO > 35 THEN 
					CASE WHEN Monto <= 36 THEN 3.51
						WHEN MONTO > 36 AND MONTO <= 39 THEN 3.75 
 						WHEN MONTO > 39 AND MONTO <= 45 THEN 4 
						WHEN MONTO > 45 AND MONTO < 48 THEN 4.25 
						ELSE 4.49 END
				 END)
	FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
	INNER JOIN FGA.DBO.SALIDA_CAMEL A ON A.IDRPT_CAMEL = B.ID
	WHERE B.ID = 351 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD 

	/*ICL ORIGINAL (ID 100000)*/
	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT 100000, ISNULL(B.MONTOPONDERADO, 0) MONTO, @PERIODOI, 'N', 
	(SELECT CASE WHEN MONTOPONDERADO >= 1.5 THEN 
					CASE WHEN MONTOPONDERADO < 2  THEN 1.45
						 WHEN MONTOPONDERADO >= 2 AND MONTOPONDERADO < 4 THEN 1.25 
 						 WHEN MONTOPONDERADO >= 4 AND MONTOPONDERADO < 6 THEN 1 
						 WHEN MONTOPONDERADO >= 6 AND MONTOPONDERADO < 8 THEN 0.75 
						 ELSE 0.51 END  
				 WHEN MONTOPONDERADO < 1.5 AND MONTOPONDERADO >= 1 THEN  1.5 + (MONTOPONDERADO - 0.5) 
				 WHEN MONTOPONDERADO < 1 AND MONTO >= 0.9 THEN 2.5  
				 WHEN MONTOPONDERADO < 0.9 THEN 
					CASE WHEN MONTOPONDERADO >= 0.5  THEN 3.51
						WHEN MONTOPONDERADO >= 0  THEN 3.75 
 						WHEN MONTOPONDERADO >= -2 THEN 4 
						WHEN MONTOPONDERADO >= -4 THEN 4.25 
						ELSE 4.49 END
				 END)
	FROM FGA.DBO.XML_ICL B
	INNER JOIN FGA.DBO.XML_Encabezado A ON A.ID = B.IDENCABEZADO_ID
	WHERE B.CUENTACATALOGO = '100000' AND MONEDA = 1 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD_ID = @IDENTIDAD 

	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT 100000, ISNULL(B.MONTOPONDERADO, 0) MONTO, @PERIODOI, 'S', 
	(SELECT CASE WHEN MONTOPONDERADO >= 1.5 THEN 
					CASE WHEN MONTOPONDERADO < 2  THEN 1.45
						 WHEN MONTOPONDERADO >= 2 AND MONTOPONDERADO < 4 THEN 1.25 
 						 WHEN MONTOPONDERADO >= 4 AND MONTOPONDERADO < 6 THEN 1 
						 WHEN MONTOPONDERADO >= 6 AND MONTOPONDERADO < 8 THEN 0.75 
						 ELSE 0.51 END  
				 WHEN MONTOPONDERADO < 1.5 AND MONTOPONDERADO >= 1 THEN  1.5 + (MONTOPONDERADO - 0.5) 
				 WHEN MONTOPONDERADO < 1 AND MONTOPONDERADO >= 0.9 THEN 2.5  
				 WHEN MONTOPONDERADO < 0.9 THEN 
					CASE WHEN MONTOPONDERADO >= 0.5  THEN 3.51
						WHEN MONTOPONDERADO >= 0  THEN 3.75 
 						WHEN MONTOPONDERADO >= -2 THEN 4 
						WHEN MONTOPONDERADO >= -4 THEN 4.25 
						ELSE 4.49 END
				 END)
	FROM FGA.DBO.XML_ICL_HIS B
	INNER JOIN FGA.DBO.XML_Encabezado_HIS A ON A.ID = B.IDENCABEZADO_ID
	WHERE B.CUENTACATALOGO = '100000' AND A.PERIODO = @PERIODOF AND A.IDENTIDAD_ID = @IDENTIDAD 

	INSERT INTO #RESUMEN (ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION) 
	SELECT 100000, ISNULL(B.MONTOPONDERADO, 0) MONTO, @PERIODOI, 'N', 
	(SELECT CASE WHEN MONTO >= 1.5 THEN 
					CASE WHEN MONTOPONDERADO < 2  THEN 1.45
						 WHEN MONTOPONDERADO >= 2 AND MONTOPONDERADO < 4 THEN 1.25 
 						 WHEN MONTOPONDERADO >= 4 AND MONTOPONDERADO < 6 THEN 1 
						 WHEN MONTOPONDERADO >= 6 AND MONTOPONDERADO < 8 THEN 0.75 
						 ELSE 0.51 END  
				 WHEN MONTOPONDERADO < 1.5 AND MONTOPONDERADO >= 1 THEN  1.5 + (MONTOPONDERADO - 0.5) 
				 WHEN MONTOPONDERADO < 1 AND MONTOPONDERADO >= 0.9 THEN 2.5  
				 WHEN MONTOPONDERADO < 0.9 THEN 
					CASE WHEN MONTOPONDERADO >= 0.5  THEN 3.51
						WHEN MONTOPONDERADO >= 0  THEN 3.75 
 						WHEN MONTOPONDERADO >= -2 THEN 4 
						WHEN MONTOPONDERADO >= -4 THEN 4.25 
						ELSE 4.49 END
				 END)
	FROM FGA.DBO.XML_ICL B
	INNER JOIN FGA.DBO.XML_Encabezado_HIS A ON A.ID = B.IDENCABEZADO_ID
	WHERE B.CUENTACATALOGO = '100000' AND A.PERIODO = @PERIODOF AND A.IDENTIDAD_ID = @IDENTIDAD 
	
	/* CUENTAS DE BALANCE ORIGINALES */
	DECLARE @CARTERA_I DECIMAL(35,2) = ISNULL(
		(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '13000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '13000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '13000000'), 0))
	)
	DECLARE @CARTERA_F DECIMAL(35,2) = ISNULL(
		(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOF AND CUENTA = '13000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '13000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '13000000'), 0))
	)

	-- 2. Obligaciones con el PÃºblico (Cuenta 21000000)
	DECLARE @OBLIG_I DECIMAL(35,2) = ISNULL(
		(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '21000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '21000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '21000000'), 0))
	)
	DECLARE @OBLIG_F DECIMAL(35,2) = ISNULL(
		(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOF AND CUENTA = '21000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '21000000'),
		ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '21000000'), 0))
	)

	-- 3. Resultado del PerÃ­odo Acumulado
	DECLARE @RESULT_I DECIMAL(35,2) = ISNULL(
		(SELECT (ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '50000000'), 0)
			   - ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '40000000'), 0)) / 1000000.0), 0)
	IF @RESULT_I = 0 BEGIN
		SET @RESULT_I = ISNULL(
			(SELECT (ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '50000000'), 0)
			       - ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '40000000'), 0)) / 1000000.0), 0)
	END
	IF @RESULT_I = 0 BEGIN
		SET @RESULT_I = ISNULL(
			(SELECT (ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '50000000'), 0)
			       - ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '40000000'), 0)) / 1000000.0), 0)
	END
	IF @RESULT_I = 0 BEGIN
		SET @RESULT_I = ISNULL(
			(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA IN ('33000000', '33100000')),
			ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA IN ('33000000', '33100000')),
			ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA IN ('33000000', '33100000')), 0)))
	END

	DECLARE @RESULT_F DECIMAL(35,2) = ISNULL(
		(SELECT (ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOF AND CUENTA = '50000000'), 0)
			   - ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOF AND CUENTA = '40000000'), 0)) / 1000000.0), 0)
	IF @RESULT_F = 0 BEGIN
		SET @RESULT_F = ISNULL(
			(SELECT (ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '50000000'), 0)
			       - ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '40000000'), 0)) / 1000000.0), 0)
	END
	IF @RESULT_F = 0 BEGIN
		SET @RESULT_F = ISNULL(
			(SELECT (ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '50000000'), 0)
			       - ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '40000000'), 0)) / 1000000.0), 0)
	END
	IF @RESULT_F = 0 BEGIN
		SET @RESULT_F = ISNULL(
			(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOF AND CUENTA IN ('33000000', '33100000')),
			ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA IN ('33000000', '33100000')),
			ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOF AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA IN ('33000000', '33100000')), 0)))
	END

	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE) VALUES (400, @RESULT_I, @RESULT_F, @PERIODOI, 'N');
	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE) VALUES (130, @CARTERA_I, @CARTERA_F, @PERIODOI, 'N');
	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE) VALUES (210, @OBLIG_I, @OBLIG_F, @PERIODOI, 'N');

	/* OTROS INDICADORES ORIGINALES */
	-- ID = 2: 100 deudores
	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE)
	SELECT 
		2,
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_INDICADORES_CARTERA A WITH(NOLOCK) WHERE A.IDINDICADOR = 2 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0),
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_INDICADORES_CARTERA A WITH(NOLOCK) WHERE A.IDINDICADOR = 2 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0),
		@PERIODOI,
		'N';

	-- ID = 104: Inversiones en tÃ­tulos valores
	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE)
	SELECT 
		104,
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 104 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0),
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 104 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0),
		@PERIODOI,
		'S';

	-- ID = 106: Captaciones a plazo con el pÃºblico
	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE)
	SELECT 
		106,
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 106 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0),
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 106 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0),
		@PERIODOI,
		'S';

	-- ID = 109: Estimaciones sobre cartera
	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE)
	SELECT 
		109,
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 109 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0),
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 109 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0),
		@PERIODOI,
		'S';

	-- ID = 112: Rentabilidad nominal
	INSERT INTO #RESUMEN (ID, MONTO, CALIFICACION, PERIODO, IND_PORCENTAJE)
	SELECT 
		112,
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 112 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0),
		ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 112 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0),
		@PERIODOI,
		'S';


	/* =========================================================================
	   SECCIÃ“N 2: NUEVOS INDICADORES PARA EL DASHBOARD MODERNO (SERIE 8000)
	   Valores reales para ambos perÃ­odos (@PERIODOI y @PERIODOF).
	   Permite calcular variaciones precisas sin afectar los IDs del sitio legado.
	   ========================================================================= */

	-- 1. Compromiso Patrimonial (ID 8003)
	DECLARE @MOD_COMP_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 3 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_COMP_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 3 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8003, @MOD_COMP_I, @MOD_COMP_F, @PERIODOI, 'S'), (8003, @MOD_COMP_F, @MOD_COMP_F, @PERIODOF, 'S');

	-- 2. Morosidad Mayor a 90 DÃ­as (ID 8022)
	DECLARE @MOD_MORO_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 22 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_MORO_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 22 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8022, @MOD_MORO_I, @MOD_MORO_F, @PERIODOI, 'S'), (8022, @MOD_MORO_F, @MOD_MORO_F, @PERIODOF, 'S');

	-- 3. Riesgo de Cartera (ID 8333)
	DECLARE @MOD_RIES_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 333 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_RIES_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 333 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8333, @MOD_RIES_I, @MOD_RIES_F, @PERIODOI, 'S'), (8333, @MOD_RIES_F, @MOD_RIES_F, @PERIODOF, 'S');

	-- 4. Activo Productivo / Pasivo con Costo (ID 8060)
	DECLARE @MOD_ACTI_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 60 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_ACTI_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 60 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8060, @MOD_ACTI_I, @MOD_ACTI_F, @PERIODOI, 'S'), (8060, @MOD_ACTI_F, @MOD_ACTI_F, @PERIODOF, 'S');

	-- 5. Gasto de AdministraciÃ³n / Costo (ID 8118)
	DECLARE @MOD_COSTO_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 118 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_COSTO_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 118 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8118, @MOD_COSTO_I, @MOD_COSTO_F, @PERIODOI, 'S'), (8118, @MOD_COSTO_F, @MOD_COSTO_F, @PERIODOF, 'S');

	-- 6. Suficiencia Patrimonial (ID 8001)
	DECLARE @MOD_SUFI_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA WHERE IDRPT_SUFICIENCIA = 1 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_SUFI_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA WHERE IDRPT_SUFICIENCIA = 1 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8001, @MOD_SUFI_I, @MOD_SUFI_F, @PERIODOI, 'S'), (8001, @MOD_SUFI_F, @MOD_SUFI_F, @PERIODOF, 'S');

	-- 7. Apalancamiento (ID 9100)
	DECLARE @MOD_APAL_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA_306 WHERE IDRPT_SUFICIENCIA = 1100 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_APAL_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA_306 WHERE IDRPT_SUFICIENCIA = 1100 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (9100, @MOD_APAL_I, @MOD_APAL_F, @PERIODOI, 'S'), (9100, @MOD_APAL_F, @MOD_APAL_F, @PERIODOF, 'S');

	-- 8. Capital Nivel 1 - CN1 (ID 8991)
	DECLARE @MOD_CN1_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA_306 WHERE IDRPT_SUFICIENCIA = -1 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_CN1_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA_306 WHERE IDRPT_SUFICIENCIA = -1 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8991, @MOD_CN1_I, @MOD_CN1_F, @PERIODOI, 'S'), (8991, @MOD_CN1_F, @MOD_CN1_F, @PERIODOF, 'S');

	-- 9. Capital ComÃºn Nivel 1 - CCN1 (ID 8992)
	DECLARE @MOD_CCN1_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA_306 WHERE IDRPT_SUFICIENCIA = -2 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_CCN1_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 ROUND(MONTO, 2) FROM FGA.DBO.SALIDA_SUFICIENCIA_306 WHERE IDRPT_SUFICIENCIA = -2 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8992, @MOD_CCN1_I, @MOD_CCN1_F, @PERIODOI, 'S'), (8992, @MOD_CCN1_F, @MOD_CCN1_F, @PERIODOF, 'S');

	-- 10. Calce de Plazos a 1 Mes (ID 8192)
	DECLARE @MOD_CAL1_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 192 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_CAL1_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 192 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8192, @MOD_CAL1_I, @MOD_CAL1_F, @PERIODOI, 'S'), (8192, @MOD_CAL1_F, @MOD_CAL1_F, @PERIODOF, 'S');

	-- 11. Calce de Plazos a 3 Meses (ID 8258)
	DECLARE @MOD_CAL3_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 258 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_CAL3_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 258 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8258, @MOD_CAL3_I, @MOD_CAL3_F, @PERIODOI, 'S'), (8258, @MOD_CAL3_F, @MOD_CAL3_F, @PERIODOF, 'S');

	-- 12. PÃ©rdida Esperada Cartera (ID 8030)
	DECLARE @MOD_PERDE_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO/100.0 FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 30 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_PERDE_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO/100.0 FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 30 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8030, @MOD_PERDE_I, @MOD_PERDE_F, @PERIODOI, 'S'), (8030, @MOD_PERDE_F, @MOD_PERDE_F, @PERIODOF, 'S');

	-- 13. PÃ©rdida Acumulada Trimestral (ID 8127)
	DECLARE @MOD_PERDA_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 127 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_PERDA_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 127 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8127, @MOD_PERDA_I, @MOD_PERDA_F, @PERIODOI, 'S'), (8127, @MOD_PERDA_F, @MOD_PERDA_F, @PERIODOF, 'S');

	-- 14. Riesgo por Tasa Moneda Extranjera (ID 8342)
	DECLARE @MOD_RTAS_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 342 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_RTAS_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 342 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8342, @MOD_RTAS_I, @MOD_RTAS_F, @PERIODOI, 'S'), (8342, @MOD_RTAS_F, @MOD_RTAS_F, @PERIODOF, 'S');

	-- 15. Riesgo Cambiario (ID 8351)
	DECLARE @MOD_RCAM_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 351 AND PERIODO = @PERIODOI AND IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_RCAM_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 MONTO FROM FGA.DBO.SALIDA_CAMEL WHERE IDRPT_CAMEL = 351 AND PERIODO = @PERIODOF AND IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8351, @MOD_RCAM_I, @MOD_RCAM_F, @PERIODOI, 'S'), (8351, @MOD_RCAM_F, @MOD_RCAM_F, @PERIODOF, 'S');

	-- 16. ICL Ponderado (ID 8900)
	DECLARE @MOD_ICL_I DECIMAL(35,2) = (
		SELECT TOP 1 ISNULL(B.MONTOPONDERADO, 0)
		FROM FGA.DBO.XML_ICL B
		INNER JOIN FGA.DBO.XML_Encabezado A ON A.ID = B.IDENCABEZADO_ID
		WHERE B.CUENTACATALOGO = '100000' AND MONEDA = 1 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD_ID = @IDENTIDAD
	);
	IF @MOD_ICL_I IS NULL
		SELECT TOP 1 @MOD_ICL_I = ISNULL(B.MONTOPONDERADO, 0)
		FROM FGA.DBO.XML_ICL_HIS B
		INNER JOIN FGA.DBO.XML_Encabezado_HIS A ON A.ID = B.IDENCABEZADO_ID
		WHERE B.CUENTACATALOGO = '100000' AND A.PERIODO = @PERIODOI AND A.IDENTIDAD_ID = @IDENTIDAD;

	DECLARE @MOD_ICL_F DECIMAL(35,2) = (
		SELECT TOP 1 ISNULL(B.MONTOPONDERADO, 0)
		FROM FGA.DBO.XML_ICL B
		INNER JOIN FGA.DBO.XML_Encabezado A ON A.ID = B.IDENCABEZADO_ID
		WHERE B.CUENTACATALOGO = '100000' AND MONEDA = 1 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD_ID = @IDENTIDAD
	);
	IF @MOD_ICL_F IS NULL
		SELECT TOP 1 @MOD_ICL_F = ISNULL(B.MONTOPONDERADO, 0)
		FROM FGA.DBO.XML_ICL_HIS B
		INNER JOIN FGA.DBO.XML_Encabezado_HIS A ON A.ID = B.IDENCABEZADO_ID
		WHERE B.CUENTACATALOGO = '100000' AND A.PERIODO = @PERIODOF AND A.IDENTIDAD_ID = @IDENTIDAD;

	INSERT INTO #RESUMEN VALUES (8900, ISNULL(@MOD_ICL_I, 0), ISNULL(@MOD_ICL_F, 0), @PERIODOI, 'S'), (8900, ISNULL(@MOD_ICL_F, 0), ISNULL(@MOD_ICL_F, 0), @PERIODOF, 'S');

	-- 17. Cuentas de Balance (ID 8130, 8210, 8400)
	INSERT INTO #RESUMEN VALUES (8130, @CARTERA_I, @CARTERA_F, @PERIODOI, 'N'), (8130, @CARTERA_F, @CARTERA_F, @PERIODOF, 'N');
	INSERT INTO #RESUMEN VALUES (8210, @OBLIG_I, @OBLIG_F, @PERIODOI, 'N'), (8210, @OBLIG_F, @OBLIG_F, @PERIODOF, 'N');
	INSERT INTO #RESUMEN VALUES (8400, @RESULT_I, @RESULT_F, @PERIODOI, 'N'), (8400, @RESULT_F, @RESULT_F, @PERIODOF, 'N');

	-- 18. Indicadores de Cartera & Otros (ID 8002, 8104, 8106, 8109, 8112)
	DECLARE @MOD_DEUD_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_INDICADORES_CARTERA A WITH(NOLOCK) WHERE A.IDINDICADOR = 2 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_DEUD_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_INDICADORES_CARTERA A WITH(NOLOCK) WHERE A.IDINDICADOR = 2 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8002, @MOD_DEUD_I, @MOD_DEUD_F, @PERIODOI, 'N'), (8002, @MOD_DEUD_F, @MOD_DEUD_F, @PERIODOF, 'N');

	DECLARE @MOD_INV_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 104 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_INV_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 104 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8104, @MOD_INV_I, @MOD_INV_F, @PERIODOI, 'S'), (8104, @MOD_INV_F, @MOD_INV_F, @PERIODOF, 'S');

	DECLARE @MOD_CAPT_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 106 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_CAPT_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 106 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8106, @MOD_CAPT_I, @MOD_CAPT_F, @PERIODOI, 'S'), (8106, @MOD_CAPT_F, @MOD_CAPT_F, @PERIODOF, 'S');

	DECLARE @MOD_ESTM_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 109 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_ESTM_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 109 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8109, @MOD_ESTM_I, @MOD_ESTM_F, @PERIODOI, 'S'), (8109, @MOD_ESTM_F, @MOD_ESTM_F, @PERIODOF, 'S');

	DECLARE @MOD_RENT_I DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 112 AND A.PERIODO = @PERIODOI AND A.IDENTIDAD = @IDENTIDAD), 0);
	DECLARE @MOD_RENT_F DECIMAL(35,2) = ISNULL((SELECT TOP 1 A.PORCENTAJE FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WITH(NOLOCK) WHERE A.IDINDICADOR = 112 AND A.PERIODO = @PERIODOF AND A.IDENTIDAD = @IDENTIDAD), 0);
	INSERT INTO #RESUMEN VALUES (8112, @MOD_RENT_I, @MOD_RENT_F, @PERIODOI, 'S'), (8112, @MOD_RENT_F, @MOD_RENT_F, @PERIODOF, 'S');


	/* RETORNAR RESULTADO CONJUNTO */
	SELECT ID, MONTO, PERIODO, IND_PORCENTAJE, CALIFICACION
	FROM #RESUMEN
	ORDER BY ID, PERIODO;

END
GO