USE [FGA]
GO

/****** Object:  StoredProcedure [dbo].[FGA_Generar_Matrices_Perdida_Estimada] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[FGA_Generar_Matrices_Perdida_Estimada]
	@IDENTIDAD NVARCHAR(5),
	@PERIODO DATE
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @CANTIDAD AS INT;	
	DECLARE @TOTAL AS DECIMAL(32, 5);	
	DECLARE @C13000000 AS DECIMAL(32, 5);
	DECLARE @C13900000 AS DECIMAL(32, 5);
	DECLARE @PERDIDA_ESTIMADA AS DECIMAL(32, 5);
	DECLARE @PORCENTAJE AS DECIMAL(32, 5);

	-- Verificar si existen registros en SALIDA_MATRICES especificamente para esta entidad y periodo
	SELECT @CANTIDAD = ISNULL(COUNT(1), 0) 
	FROM FGA.DBO.SALIDA_MATRICES 
	WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODO;

	IF @CANTIDAD > 0 
	BEGIN
		-- Saldo cuenta 13000000 (Cartera de credito)
		SELECT @C13000000 = ISNULL(SUM(SALDOFINAL), 0)
		FROM (
			SELECT ISNULL(SUM(A.SALDOFINAL), 0) AS SALDOFINAL
			FROM SALIDA_BALANCE_COMPROBACION A WITH (NOLOCK)
			WHERE A.PERIODO = @PERIODO AND A.IDENTIDAD = @IDENTIDAD AND A.CUENTA = '13000000'
		) Z;
		
		-- Saldo cuenta 13900000 (Estimaciones)
		SELECT @C13900000 = ISNULL(SUM(SALDOFINAL), 0)
		FROM (
			SELECT ISNULL(SUM(A.SALDOFINAL), 0) AS SALDOFINAL
			FROM SALIDA_BALANCE_COMPROBACION A WITH (NOLOCK)
			WHERE A.PERIODO = @PERIODO AND A.IDENTIDAD = @IDENTIDAD AND A.CUENTA = '13900000'
		) Z;

		CREATE TABLE #SALDO_PROMEDIO (
			IDENTIDAD NVARCHAR(5), 
			FILA_INICIO NVARCHAR(150), 
			ID_INICIO INT,
			COLUMNA_FINAL NVARCHAR(150),
			ID_FINAL INT, 
			SALDO DECIMAL(32, 5), 
			PROMEDIOFILA DECIMAL(32, 5), 
			PROMEDIOTOTAL DECIMAL(32, 5)
		);

		INSERT INTO #SALDO_PROMEDIO (
			[IDENTIDAD],
			[FILA_INICIO],
			[ID_INICIO],
			[COLUMNA_FINAL],
			[ID_FINAL],
			[SALDO]
		)
		SELECT 	
			[IDENTIDAD],
			[FILA_INICIO],
			[ID_INICIO],
			[COLUMNA_FINAL],
			[ID_FINAL],
			ISNULL(SUM([SALDO]), 0)
		FROM FGA.DBO.SALIDA_MATRICES 
		WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODO
		GROUP BY [IDENTIDAD], [FILA_INICIO], [ID_INICIO], [COLUMNA_FINAL], [ID_FINAL];

		SELECT @TOTAL = ISNULL(SUM(SALDO), 0) FROM #SALDO_PROMEDIO;
	
		-- Proteccion contra division por cero cuando @TOTAL es 0
		IF @TOTAL > 0
		BEGIN
			UPDATE #SALDO_PROMEDIO
			SET PROMEDIOTOTAL = (SALDO / @TOTAL);
		END
		ELSE
		BEGIN
			UPDATE #SALDO_PROMEDIO
			SET PROMEDIOTOTAL = 0;
		END
	
		SELECT @PERDIDA_ESTIMADA = ISNULL(SUM(PROMEDIOTOTAL), 0) 
		FROM #SALDO_PROMEDIO
		WHERE ID_FINAL >= ID_INICIO 
		  AND ID_FINAL >= 5;

		-- Proteccion contra division por cero en Cuenta 13900000
		IF ISNULL(@C13900000, 0) <> 0
		BEGIN
			SET @PORCENTAJE = (@C13000000 * @PERDIDA_ESTIMADA / @C13900000) * 100;
		END
		ELSE
		BEGIN
			SET @PORCENTAJE = 0;
		END

		-- Limpieza preventiva para no duplicar registros de este periodo y entidad
		DELETE FROM [DBO].[SALIDA_MATRICES_PERDIDA_ESTIMADA]
		WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODO;
	
		INSERT INTO [DBO].[SALIDA_MATRICES_PERDIDA_ESTIMADA] (
			[IDENTIDAD],
			[PERIODO],
			[PERDIDA_ESTIMADA],
			[ESTIMACION_MATRIZ],
			[PORCENTAJE],
			[CUENTA139]
		)	
		SELECT 
			@IDENTIDAD, 
			@PERIODO, 
			@PERDIDA_ESTIMADA * 100, 
			(@C13000000 * @PERDIDA_ESTIMADA), 
			@PORCENTAJE, 
			@C13900000;

		DROP TABLE #SALDO_PROMEDIO;
	END
END
GO
