USE [FGA]
GO
/****** Object:  StoredProcedure [dbo].[FGA_Consultar_Grafico_Indicador]    Script Date: 16/09/2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[FGA_Consultar_Grafico_Indicador]
	@IDENTIDAD NVARCHAR(5),
	@PERIODOI DATE,
	@PERIODOF DATE,
	@INDICADOR NVARCHAR(10)
AS
BEGIN
	SET NOCOUNT ON;

	IF @IDENTIDAD = 99 BEGIN
		SET @IDENTIDAD = 13
	END

	DECLARE @RESULTADO DECIMAL(35,5)
	DECLARE @PROMEDIO DECIMAL(35,5)
	DECLARE @EXISTE INT

	DECLARE @TIPO NVARCHAR(1) 
	SET @TIPO = SUBSTRING(@INDICADOR, 1, 1)
	
	DECLARE @ID INT
	SET  @ID = CONVERT(INT, SUBSTRING(@INDICADOR, 2, 15))
	
	SET FMTONLY OFF
	CREATE TABLE #RESUMEN( NOMBRE NVARCHAR(150), MONTO DECIMAL(35, 5), PROMEDIO DECIMAL(35, 5), PERIODO DATE, IND_PORCENTAJE NVARCHAR(1))	
	
	/* =========================================================================
	   RAMA C: ESTRUCTURA CAMEL
	   ========================================================================= */
	IF @TIPO = 'C' BEGIN

		WHILE @PERIODOI <= @PERIODOF
		BEGIN	

			SELECT @RESULTADO = ISNULL(A.MONTO, 0) FROM FGA.DBO.SALIDA_CAMEL A WHERE A.IDENTIDAD = @IDENTIDAD AND A.PERIODO = @PERIODOI AND A.IDRPT_CAMEL = @ID 	
			SELECT @PROMEDIO = AVG(ISNULL(A.MONTO, 0)) FROM FGA.DBO.SALIDA_CAMEL A WHERE A.PERIODO = @PERIODOI AND A.IDRPT_CAMEL = @ID AND A.MONTO != 0					

			INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE) 
							 	  SELECT  LTRIM(REPLACE(NOMBRE, '-', '')), ISNULL(@RESULTADO, 0), @PROMEDIO, @PERIODOI, B.IND_PORCENTAJE
						 	      FROM FGA.DBO.RPT_ESTRUCTURA_CAMEL B
							      WHERE B.ID = @ID
		
			SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
		END
	
	/* =========================================================================
	   RAMA S: ESTRUCTURA SUFICIENCIA
	   ========================================================================= */
	END ELSE IF @TIPO = 'S' BEGIN

		WHILE @PERIODOI <= @PERIODOF
		BEGIN	

			SELECT @RESULTADO = ISNULL(A.MONTO, 0) FROM FGA.DBO.SALIDA_SUFICIENCIA A WHERE A.IDENTIDAD = @IDENTIDAD AND A.PERIODO = @PERIODOI AND A.IDRPT_SUFICIENCIA = @ID 	
			SELECT @PROMEDIO = AVG(ISNULL(A.MONTO, 0)) FROM FGA.DBO.SALIDA_SUFICIENCIA A WHERE A.PERIODO = @PERIODOI AND A.IDRPT_SUFICIENCIA = @ID AND A.MONTO != 0					
		
			INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE) 
							 	  SELECT  LTRIM(REPLACE(NOMBRE, '-', '')), ISNULL(@RESULTADO, 0), @PROMEDIO, @PERIODOI, B.IND_PORCENTAJE
						 	      FROM FGA.DBO.RPT_ESTRUCTURA_SUFICIENCIA B
							      WHERE B.ID = @ID
		
			SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
		END
	
	/* =========================================================================
	   RAMA P: FÓRMULAS DINÁMICAS
	   ========================================================================= */
	END ELSE IF @TIPO = 'P' BEGIN
	
		DECLARE @POSICION INT
		DECLARE @FORMULA_REAL NVARCHAR(150)
		DECLARE @FORMULA_REALP NVARCHAR(150)

		DECLARE @NOMBRE_FORMULA NVARCHAR(150)
		DECLARE @VALOR_ACTUAL NVARCHAR(150)
		DECLARE @FORMULA_ACTUAL NVARCHAR(250)
		DECLARE @IND_PORCENTAJE NVARCHAR(1)
		DECLARE @CHAR NVARCHAR(250)		

		SELECT @FORMULA_ACTUAL = B.FORMULA, @NOMBRE_FORMULA = B.NOMBRE FROM FGA.DBO.FORMULAS B WHERE B.ID = @ID
		SELECT @IND_PORCENTAJE = CASE B.IND_PORCENTAJE WHEN 1 THEN 'S' ELSE 'N' END FROM FGA.DBO.FORMULAS B WHERE B.ID = @ID
				
		WHILE @PERIODOI <= @PERIODOF
		BEGIN	
			SET @FORMULA_REAL = ''
			SET @FORMULA_REALP = ''
			SET @VALOR_ACTUAL = ''
			SET @POSICION = 1
		
			WHILE @POSICION <= DATALENGTH(@FORMULA_ACTUAL)  
			BEGIN 
				   
				SET @CHAR = SUBSTRING(@FORMULA_ACTUAL, @POSICION, 1)									   
  				SET @POSICION = @POSICION + 1  
					
				IF @CHAR != '' BEGIN
					
					IF @CHAR IN ('+','-','*','/','(',')','A','B','S') AND SUBSTRING(@FORMULA_ACTUAL, @POSICION, 1) NOT IN ('C','N') BEGIN
						IF LEN(@VALOR_ACTUAL) > 0 BEGIN
							SET @FORMULA_REALP  += CONVERT(NVARCHAR(50), ISNULL(FGA.DBO.FN_OBTENERSALDO(@VALOR_ACTUAL, @PERIODOI, -1), 0))
							SET @FORMULA_REAL  += CONVERT(NVARCHAR(50), ISNULL(FGA.DBO.FN_OBTENERSALDO(@VALOR_ACTUAL, @PERIODOI, @IDENTIDAD), 0))
							SET @VALOR_ACTUAL = ''
						END
						
						SET @FORMULA_REAL += @CHAR
						SET @FORMULA_REALP  += @CHAR

					END ELSE BEGIN
						SET @VALOR_ACTUAL += @CHAR						
					END
				END
			END	
				
			IF LEN(@VALOR_ACTUAL) > 3 BEGIN
				SET @FORMULA_REALP  += CONVERT(NVARCHAR(50), ISNULL(FGA.DBO.FN_OBTENERSALDO(@VALOR_ACTUAL, @PERIODOI, -1), 0))
				SET @FORMULA_REAL  += CONVERT(NVARCHAR(50), ISNULL(FGA.DBO.FN_OBTENERSALDO(@VALOR_ACTUAL, @PERIODOI, @IDENTIDAD), 0))
			END 

			DECLARE @THESQL NVARCHAR(MAX)
			SET @THESQL = 'SELECT @THEOUTPUT = ' + @FORMULA_REAL

			BEGIN TRY
				EXEC SP_EXECUTESQL @STMT = @THESQL
					, @PARAMS= N'@THEOUTPUT DECIMAL(35,5) OUTPUT'
					, @THEOUTPUT = @RESULTADO OUTPUT
						
			END TRY
			BEGIN CATCH
				SET @RESULTADO = 0
			END CATCH					
		
			SET @THESQL = 'SELECT @THEOUTPUT = ' + @FORMULA_REALP

			BEGIN TRY
				EXEC SP_EXECUTESQL @STMT = @THESQL
					, @PARAMS= N'@THEOUTPUT DECIMAL(35,5) OUTPUT'
					, @THEOUTPUT = @PROMEDIO OUTPUT
						
			END TRY
			BEGIN CATCH
				SET @PROMEDIO = 0
			END CATCH					

			INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE) VALUES (@NOMBRE_FORMULA, CASE @IND_PORCENTAJE WHEN 'N' THEN @RESULTADO ELSE @RESULTADO * 100 END, 
								   CASE @IND_PORCENTAJE WHEN 'N' THEN @PROMEDIO ELSE @PROMEDIO * 100 END, @PERIODOI, @IND_PORCENTAJE)	
			SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
				
		END

	/* =========================================================================
	   RAMA B: CUENTAS PRINCIPALES DE BALANCE (DASHBOARD)
	   Muestra secuencia mensual completa en millones de colones
	   ========================================================================= */
	END ELSE IF @TIPO = 'B' BEGIN

		DECLARE @NOM_B NVARCHAR(150)
		DECLARE @RES_B DECIMAL(35,5)
		DECLARE @PROM_B DECIMAL(35,5)

		-- 1. Resultado del Período Acumulado (ID 400 u 8400)
		IF @ID IN (400, 8400) BEGIN
			SET @NOM_B = 'Resultado del período acumulado'

			WHILE @PERIODOI <= @PERIODOF
			BEGIN
				-- Monto Entidad (Ingresos 50000000 - Gastos 40000000) en Millones de Colones
				SET @RES_B = ISNULL(
					(SELECT (ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '50000000'), 0)
					       - ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '40000000'), 0)) / 1000000.0), 0)

				IF @RES_B = 0 BEGIN
					SET @RES_B = ISNULL(
						(SELECT (ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '50000000'), 0)
						       - ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '40000000'), 0)) / 1000000.0), 0)
				END

				IF @RES_B = 0 BEGIN
					SET @RES_B = ISNULL(
						(SELECT (ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '50000000'), 0)
						       - ISNULL((SELECT TOP 1 C.SALDOFINAL FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '40000000'), 0)) / 1000000.0), 0)
				END

				IF @RES_B = 0 BEGIN
					SET @RES_B = ISNULL(
						(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA IN ('33000000', '33100000')),
						ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA IN ('33000000', '33100000')),
						ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA IN ('33000000', '33100000')), 0)))
				END

				-- Promedio del Sistema
				SET @PROM_B = ISNULL(
					(SELECT (ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = '-1' AND PERIODO = @PERIODOI AND CUENTA = '50000000'), 0)
					       - ISNULL((SELECT TOP 1 SALDOACUMULADO FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = '-1' AND PERIODO = @PERIODOI AND CUENTA = '40000000'), 0)) / 1000000.0), 0)

				IF @PROM_B = 0 BEGIN
					SELECT @PROM_B = ISNULL(AVG(RES_M), 0) FROM (
						SELECT (ISNULL(MAX(CASE WHEN CUENTA = '50000000' THEN SALDOACUMULADO ELSE 0 END), 0)
						      - ISNULL(MAX(CASE WHEN CUENTA = '40000000' THEN SALDOACUMULADO ELSE 0 END), 0)) / 1000000.0 AS RES_M
						FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK)
						WHERE PERIODO = @PERIODOI AND CUENTA IN ('50000000', '40000000') AND IDENTIDAD NOT IN ('-1', '99')
						GROUP BY IDENTIDAD
					) T WHERE T.RES_M != 0
				END

				INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE)
				VALUES (@NOM_B, @RES_B, @PROM_B, @PERIODOI, 'N')

				SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
			END
		
		-- 2. Cartera de Crédito (ID 130, 8130 o cuenta 13000000)
		END ELSE IF @ID IN (130, 8130, 13000000) BEGIN
			SET @NOM_B = 'Cartera de crédito'

			WHILE @PERIODOI <= @PERIODOF
			BEGIN
				-- Monto Entidad
				SET @RES_B = ISNULL(
					(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '13000000'),
					ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '13000000'),
					ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '13000000'), 0))
				)

				-- Promedio del Sistema
				SET @PROM_B = ISNULL((SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = '-1' AND PERIODO = @PERIODOI AND CUENTA = '13000000'), 0)

				IF @PROM_B = 0 BEGIN
					SELECT @PROM_B = ISNULL(AVG(SALDOFINAL / 1000000.0), 0)
					FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK)
					WHERE PERIODO = @PERIODOI AND CUENTA = '13000000' AND IDENTIDAD NOT IN ('-1', '99') AND SALDOFINAL != 0
				END

				INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE)
				VALUES (@NOM_B, @RES_B, @PROM_B, @PERIODOI, 'N')

				SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
			END

		-- 3. Obligaciones con el Público (ID 210, 8210 o cuenta 21000000)
		END ELSE IF @ID IN (210, 8210, 21000000) BEGIN
			SET @NOM_B = 'Obligaciones con el público'

			WHILE @PERIODOI <= @PERIODOF
			BEGIN
				-- Monto Entidad
				SET @RES_B = ISNULL(
					(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = '21000000'),
					ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '21000000'),
					ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO_HIS C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO_HIS E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = '21000000'), 0))
				)

				-- Promedio del Sistema
				SET @PROM_B = ISNULL((SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = '-1' AND PERIODO = @PERIODOI AND CUENTA = '21000000'), 0)

				IF @PROM_B = 0 BEGIN
					SELECT @PROM_B = ISNULL(AVG(SALDOFINAL / 1000000.0), 0)
					FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK)
					WHERE PERIODO = @PERIODOI AND CUENTA = '21000000' AND IDENTIDAD NOT IN ('-1', '99') AND SALDOFINAL != 0
				END

				INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE)
				VALUES (@NOM_B, @RES_B, @PROM_B, @PERIODOI, 'N')

				SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
			END

		-- 4. Cuenta genérica de Balance de Comprobación
		END ELSE BEGIN
			DECLARE @CUENTA_GEN NVARCHAR(8) = CAST(@ID AS NVARCHAR(8))
			IF LEN(@CUENTA_GEN) < 8 BEGIN
				SET @CUENTA_GEN = @CUENTA_GEN + REPLICATE('0', 8 - LEN(@CUENTA_GEN))
			END

			SELECT TOP 1 @NOM_B = LTRIM(REPLACE(NOMBRE, '-', ''))
			FROM FGA.DBO.CATALOGOCUENTA WITH(NOLOCK)
			WHERE CUENTA = @CUENTA_GEN

			IF @NOM_B = '' OR @NOM_B IS NULL BEGIN
				SET @NOM_B = 'Cuenta ' + @CUENTA_GEN
			END

			WHILE @PERIODOI <= @PERIODOF
			BEGIN
				SET @RES_B = ISNULL(
					(SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = @IDENTIDAD AND PERIODO = @PERIODOI AND CUENTA = @CUENTA_GEN),
					ISNULL((SELECT TOP 1 C.SALDOFINAL / 1000000.0 FROM FGA.DBO.XML_CONTABLE_ESTADO C WITH(NOLOCK) INNER JOIN FGA.DBO.XML_ENCABEZADO E WITH(NOLOCK) ON E.ID = C.IDENCABEZADO_ID WHERE E.IDENTIDAD_ID = @IDENTIDAD AND E.PERIODO = @PERIODOI AND E.IDARCHIVO_ID = 201 AND E.IDESTADO_ID = 3 AND C.CUENTA = @CUENTA_GEN), 0)
				)

				SET @PROM_B = ISNULL((SELECT TOP 1 SALDOFINAL / 1000000.0 FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK) WHERE IDENTIDAD = '-1' AND PERIODO = @PERIODOI AND CUENTA = @CUENTA_GEN), 0)

				IF @PROM_B = 0 BEGIN
					SELECT @PROM_B = ISNULL(AVG(SALDOFINAL / 1000000.0), 0)
					FROM FGA.DBO.SALIDA_BALANCE_COMPROBACION WITH(NOLOCK)
					WHERE PERIODO = @PERIODOI AND CUENTA = @CUENTA_GEN AND IDENTIDAD NOT IN ('-1', '99') AND SALDOFINAL != 0
				END

				INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE)
				VALUES (@NOM_B, @RES_B, @PROM_B, @PERIODOI, 'N')

				SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
			END
		END

	/* =========================================================================
	   RAMA POR DEFECTO: INDICADORES DE CARTERA Y OTROS INDICADORES
	   ========================================================================= */
	END ELSE BEGIN
		
		WHILE @PERIODOI <= @PERIODOF
		BEGIN	

			SET @RESULTADO = 0
			SELECT @RESULTADO = ISNULL(A.PORCENTAJE, 0) FROM FGA.DBO.SALIDA_INDICADORES_CARTERA A WHERE A.IDENTIDAD = @IDENTIDAD AND A.PERIODO = @PERIODOI AND  A.IDINDICADOR = @ID 	
			SELECT @PROMEDIO = ISNULL(A.PORCENTAJE, 0) FROM FGA.DBO.SALIDA_INDICADORES_CARTERA A WHERE A.IDENTIDAD = @IDENTIDAD AND A.PORCENTAJE != 0 AND  A.IDINDICADOR = @ID 	
			
			IF ISNULL(@RESULTADO, 0) = 0 BEGIN
				SELECT @RESULTADO = ISNULL(A.PORCENTAJE, 0) FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WHERE A.IDENTIDAD = @IDENTIDAD AND A.PERIODO = @PERIODOI AND  A.IDINDICADOR = @ID 	
				SELECT @PROMEDIO = AVG(ISNULL(A.PORCENTAJE, 0)) FROM FGA.DBO.SALIDA_OTROS_INDICADORES A WHERE A.PORCENTAJE != 0 AND A.PERIODO = @PERIODOI AND  A.IDINDICADOR = @ID 	
			END
					
			INSERT INTO #RESUMEN (NOMBRE, MONTO, PROMEDIO, PERIODO, IND_PORCENTAJE) 		
									SELECT B.NOMBRE, ISNULL(@RESULTADO, 0), @PROMEDIO, @PERIODOI, CASE B.IND_PORCENTAJE WHEN 1 THEN 'S' ELSE 'N' END
									FROM  FGA.DBO.INDICADORES B
									WHERE B.ID = @ID

			SET @PERIODOI = DATEADD(MONTH, 1, @PERIODOI)
		END
	END

	/* =========================================================================
	   RESULTADO FINAL ORDENADO CRONOLÓGICAMENTE
	   ========================================================================= */
	SELECT NOMBRE, CAST(ROUND(MONTO, 2) AS DECIMAL(35,2)) MONTO, CAST(ROUND(PROMEDIO, 2) AS DECIMAL(35,2)) PROMEDIO, PERIODO, IND_PORCENTAJE 
	FROM #RESUMEN 
	ORDER BY PERIODO ASC

END
GO
