//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.FormulaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FormulaService.IServiceOf_Formulas")]
    public interface IServiceOf_Formulas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Formulas/GetAllResponse")]
        FGA.Models.Formulas[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Formulas/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Formulas[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Get", ReplyAction="http://tempuri.org/IServiceOf_Formulas/GetResponse")]
        FGA.Models.Formulas Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Get", ReplyAction="http://tempuri.org/IServiceOf_Formulas/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Formulas> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Add", ReplyAction="http://tempuri.org/IServiceOf_Formulas/AddResponse")]
        FGA_En_Linea.FormulaService.AddResponse Add(FGA_En_Linea.FormulaService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Add", ReplyAction="http://tempuri.org/IServiceOf_Formulas/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.FormulaService.AddResponse> AddAsync(FGA_En_Linea.FormulaService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Update", ReplyAction="http://tempuri.org/IServiceOf_Formulas/UpdateResponse")]
        void Update(FGA.Models.Formulas entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Update", ReplyAction="http://tempuri.org/IServiceOf_Formulas/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Formulas entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Delete", ReplyAction="http://tempuri.org/IServiceOf_Formulas/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Formulas/Delete", ReplyAction="http://tempuri.org/IServiceOf_Formulas/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Formulas entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Formulas entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Formulas entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Formulas entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_FormulasChannel : FGA_En_Linea.FormulaService.IServiceOf_Formulas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_FormulasClient : System.ServiceModel.ClientBase<FGA_En_Linea.FormulaService.IServiceOf_Formulas>, FGA_En_Linea.FormulaService.IServiceOf_Formulas {
        
        public ServiceOf_FormulasClient() {
        }
        
        public ServiceOf_FormulasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_FormulasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_FormulasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_FormulasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Formulas[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Formulas[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Formulas Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Formulas> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.FormulaService.AddResponse FGA_En_Linea.FormulaService.IServiceOf_Formulas.Add(FGA_En_Linea.FormulaService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Formulas entity) {
            FGA_En_Linea.FormulaService.AddRequest inValue = new FGA_En_Linea.FormulaService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.FormulaService.AddResponse retVal = ((FGA_En_Linea.FormulaService.IServiceOf_Formulas)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.FormulaService.AddResponse> AddAsync(FGA_En_Linea.FormulaService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Formulas entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Formulas entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
