//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.AlbumService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlbumService.IServiceOf_Album")]
    public interface IServiceOf_Album {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Album/GetAllResponse")]
        FGA.Models.Album[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Album/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Album[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Get", ReplyAction="http://tempuri.org/IServiceOf_Album/GetResponse")]
        FGA.Models.Album Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Get", ReplyAction="http://tempuri.org/IServiceOf_Album/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Album> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Add", ReplyAction="http://tempuri.org/IServiceOf_Album/AddResponse")]
        FGA_En_Linea.AlbumService.AddResponse Add(FGA_En_Linea.AlbumService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Add", ReplyAction="http://tempuri.org/IServiceOf_Album/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.AlbumService.AddResponse> AddAsync(FGA_En_Linea.AlbumService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Update", ReplyAction="http://tempuri.org/IServiceOf_Album/UpdateResponse")]
        void Update(FGA.Models.Album entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Update", ReplyAction="http://tempuri.org/IServiceOf_Album/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Album entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Delete", ReplyAction="http://tempuri.org/IServiceOf_Album/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Album/Delete", ReplyAction="http://tempuri.org/IServiceOf_Album/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Album entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Album entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Album entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Album entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_AlbumChannel : FGA_En_Linea.AlbumService.IServiceOf_Album, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_AlbumClient : System.ServiceModel.ClientBase<FGA_En_Linea.AlbumService.IServiceOf_Album>, FGA_En_Linea.AlbumService.IServiceOf_Album {
        
        public ServiceOf_AlbumClient() {
        }
        
        public ServiceOf_AlbumClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_AlbumClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_AlbumClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_AlbumClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Album[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Album[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Album Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Album> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.AlbumService.AddResponse FGA_En_Linea.AlbumService.IServiceOf_Album.Add(FGA_En_Linea.AlbumService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Album entity) {
            FGA_En_Linea.AlbumService.AddRequest inValue = new FGA_En_Linea.AlbumService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.AlbumService.AddResponse retVal = ((FGA_En_Linea.AlbumService.IServiceOf_Album)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.AlbumService.AddResponse> AddAsync(FGA_En_Linea.AlbumService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Album entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Album entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
