//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.Bit_SessionesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Bit_SessionesService.IServiceOf_Bit_Sessiones")]
    public interface IServiceOf_Bit_Sessiones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/GetAllResponse")]
        FGA.Models.Bit_Sessiones[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Bit_Sessiones[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Get", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/GetResponse")]
        FGA.Models.Bit_Sessiones Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Get", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Bit_Sessiones> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Add", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/AddResponse")]
        FGA_En_Linea.Bit_SessionesService.AddResponse Add(FGA_En_Linea.Bit_SessionesService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Add", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.Bit_SessionesService.AddResponse> AddAsync(FGA_En_Linea.Bit_SessionesService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Update", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/UpdateResponse")]
        void Update(FGA.Models.Bit_Sessiones entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Update", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Bit_Sessiones entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Delete", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Bit_Sessiones/Delete", ReplyAction="http://tempuri.org/IServiceOf_Bit_Sessiones/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Bit_Sessiones entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Bit_Sessiones entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Bit_Sessiones entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Bit_Sessiones entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Bit_SessionesChannel : FGA_En_Linea.Bit_SessionesService.IServiceOf_Bit_Sessiones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Bit_SessionesClient : System.ServiceModel.ClientBase<FGA_En_Linea.Bit_SessionesService.IServiceOf_Bit_Sessiones>, FGA_En_Linea.Bit_SessionesService.IServiceOf_Bit_Sessiones {
        
        public ServiceOf_Bit_SessionesClient() {
        }
        
        public ServiceOf_Bit_SessionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Bit_SessionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Bit_SessionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Bit_SessionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Bit_Sessiones[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Bit_Sessiones[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Bit_Sessiones Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Bit_Sessiones> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.Bit_SessionesService.AddResponse FGA_En_Linea.Bit_SessionesService.IServiceOf_Bit_Sessiones.Add(FGA_En_Linea.Bit_SessionesService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Bit_Sessiones entity) {
            FGA_En_Linea.Bit_SessionesService.AddRequest inValue = new FGA_En_Linea.Bit_SessionesService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.Bit_SessionesService.AddResponse retVal = ((FGA_En_Linea.Bit_SessionesService.IServiceOf_Bit_Sessiones)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.Bit_SessionesService.AddResponse> AddAsync(FGA_En_Linea.Bit_SessionesService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Bit_Sessiones entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Bit_Sessiones entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
