//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.EvalCategoriaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvalCategoriaService.IEvalCategoriaService")]
    public interface IEvalCategoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/GetByUser", ReplyAction="http://tempuri.org/IEvalCategoriaService/GetByUserResponse")]
        Entities.Entities.Evaluacion.EvalCategoria[] GetByUser(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/GetByUser", ReplyAction="http://tempuri.org/IEvalCategoriaService/GetByUserResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalCategoria[]> GetByUserAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/GetAll", ReplyAction="http://tempuri.org/IEvalCategoriaService/GetAllResponse")]
        Entities.Entities.Evaluacion.EvalCategoria[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/GetAll", ReplyAction="http://tempuri.org/IEvalCategoriaService/GetAllResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalCategoria[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Get", ReplyAction="http://tempuri.org/IEvalCategoriaService/GetResponse")]
        Entities.Entities.Evaluacion.EvalCategoria Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Get", ReplyAction="http://tempuri.org/IEvalCategoriaService/GetResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalCategoria> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Add", ReplyAction="http://tempuri.org/IEvalCategoriaService/AddResponse")]
        FGA_En_Linea.EvalCategoriaService.AddResponse Add(FGA_En_Linea.EvalCategoriaService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Add", ReplyAction="http://tempuri.org/IEvalCategoriaService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.EvalCategoriaService.AddResponse> AddAsync(FGA_En_Linea.EvalCategoriaService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Update", ReplyAction="http://tempuri.org/IEvalCategoriaService/UpdateResponse")]
        void Update(Entities.Entities.Evaluacion.EvalCategoria entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Update", ReplyAction="http://tempuri.org/IEvalCategoriaService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalCategoria entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Delete", ReplyAction="http://tempuri.org/IEvalCategoriaService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalCategoriaService/Delete", ReplyAction="http://tempuri.org/IEvalCategoriaService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalCategoria entity;
        
        public AddRequest() {
        }
        
        public AddRequest(Entities.Entities.Evaluacion.EvalCategoria entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalCategoria entity;
        
        public AddResponse() {
        }
        
        public AddResponse(Entities.Entities.Evaluacion.EvalCategoria entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvalCategoriaServiceChannel : FGA_En_Linea.EvalCategoriaService.IEvalCategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvalCategoriaServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.EvalCategoriaService.IEvalCategoriaService>, FGA_En_Linea.EvalCategoriaService.IEvalCategoriaService {
        
        public EvalCategoriaServiceClient() {
        }
        
        public EvalCategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvalCategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvalCategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvalCategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Entities.Evaluacion.EvalCategoria[] GetByUser(int idUser) {
            return base.Channel.GetByUser(idUser);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalCategoria[]> GetByUserAsync(int idUser) {
            return base.Channel.GetByUserAsync(idUser);
        }
        
        public Entities.Entities.Evaluacion.EvalCategoria[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalCategoria[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Entities.Entities.Evaluacion.EvalCategoria Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalCategoria> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.EvalCategoriaService.AddResponse FGA_En_Linea.EvalCategoriaService.IEvalCategoriaService.Add(FGA_En_Linea.EvalCategoriaService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref Entities.Entities.Evaluacion.EvalCategoria entity) {
            FGA_En_Linea.EvalCategoriaService.AddRequest inValue = new FGA_En_Linea.EvalCategoriaService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.EvalCategoriaService.AddResponse retVal = ((FGA_En_Linea.EvalCategoriaService.IEvalCategoriaService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.EvalCategoriaService.AddResponse> AddAsync(FGA_En_Linea.EvalCategoriaService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(Entities.Entities.Evaluacion.EvalCategoria entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalCategoria entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
