//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.LiborService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LiborService.IServiceOf_Hist_Libor")]
    public interface IServiceOf_Hist_Libor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/GetAllResponse")]
        FGA.Models.Hist_Libor[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_Libor[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/GetResponse")]
        FGA.Models.Hist_Libor Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Get", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Hist_Libor> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/AddResponse")]
        FGA_En_Linea.LiborService.AddResponse Add(FGA_En_Linea.LiborService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Add", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.LiborService.AddResponse> AddAsync(FGA_En_Linea.LiborService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/UpdateResponse")]
        void Update(FGA.Models.Hist_Libor entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Update", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_Libor entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Hist_Libor/Delete", ReplyAction="http://tempuri.org/IServiceOf_Hist_Libor/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_Libor entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Hist_Libor entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Hist_Libor entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Hist_Libor entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_Hist_LiborChannel : FGA_En_Linea.LiborService.IServiceOf_Hist_Libor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_Hist_LiborClient : System.ServiceModel.ClientBase<FGA_En_Linea.LiborService.IServiceOf_Hist_Libor>, FGA_En_Linea.LiborService.IServiceOf_Hist_Libor {
        
        public ServiceOf_Hist_LiborClient() {
        }
        
        public ServiceOf_Hist_LiborClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_Hist_LiborClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_LiborClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_Hist_LiborClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Hist_Libor[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_Libor[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Hist_Libor Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Hist_Libor> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.LiborService.AddResponse FGA_En_Linea.LiborService.IServiceOf_Hist_Libor.Add(FGA_En_Linea.LiborService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Hist_Libor entity) {
            FGA_En_Linea.LiborService.AddRequest inValue = new FGA_En_Linea.LiborService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.LiborService.AddResponse retVal = ((FGA_En_Linea.LiborService.IServiceOf_Hist_Libor)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.LiborService.AddResponse> AddAsync(FGA_En_Linea.LiborService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Hist_Libor entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Hist_Libor entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
