//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.EvalSubCategoriaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvalSubCategoriaService.IEvalSubCategoriaService")]
    public interface IEvalSubCategoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/GetAll", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/GetAllResponse")]
        Entities.Entities.Evaluacion.EvalSubCategoria[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/GetAll", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/GetAllResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalSubCategoria[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/GetByCategory", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/GetByCategoryResponse")]
        Entities.Entities.Evaluacion.EvalSubCategoria[] GetByCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/GetByCategory", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/GetByCategoryResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalSubCategoria[]> GetByCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Get", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/GetResponse")]
        Entities.Entities.Evaluacion.EvalSubCategoria Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Get", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/GetResponse")]
        System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalSubCategoria> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Add", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/AddResponse")]
        FGA_En_Linea.EvalSubCategoriaService.AddResponse Add(FGA_En_Linea.EvalSubCategoriaService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Add", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.EvalSubCategoriaService.AddResponse> AddAsync(FGA_En_Linea.EvalSubCategoriaService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Update", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/UpdateResponse")]
        void Update(Entities.Entities.Evaluacion.EvalSubCategoria entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Update", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalSubCategoria entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Delete", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvalSubCategoriaService/Delete", ReplyAction="http://tempuri.org/IEvalSubCategoriaService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalSubCategoria entity;
        
        public AddRequest() {
        }
        
        public AddRequest(Entities.Entities.Evaluacion.EvalSubCategoria entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Entities.Entities.Evaluacion.EvalSubCategoria entity;
        
        public AddResponse() {
        }
        
        public AddResponse(Entities.Entities.Evaluacion.EvalSubCategoria entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvalSubCategoriaServiceChannel : FGA_En_Linea.EvalSubCategoriaService.IEvalSubCategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvalSubCategoriaServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.EvalSubCategoriaService.IEvalSubCategoriaService>, FGA_En_Linea.EvalSubCategoriaService.IEvalSubCategoriaService {
        
        public EvalSubCategoriaServiceClient() {
        }
        
        public EvalSubCategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvalSubCategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvalSubCategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvalSubCategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Entities.Evaluacion.EvalSubCategoria[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalSubCategoria[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Entities.Entities.Evaluacion.EvalSubCategoria[] GetByCategory(int id) {
            return base.Channel.GetByCategory(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalSubCategoria[]> GetByCategoryAsync(int id) {
            return base.Channel.GetByCategoryAsync(id);
        }
        
        public Entities.Entities.Evaluacion.EvalSubCategoria Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Entities.Entities.Evaluacion.EvalSubCategoria> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.EvalSubCategoriaService.AddResponse FGA_En_Linea.EvalSubCategoriaService.IEvalSubCategoriaService.Add(FGA_En_Linea.EvalSubCategoriaService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref Entities.Entities.Evaluacion.EvalSubCategoria entity) {
            FGA_En_Linea.EvalSubCategoriaService.AddRequest inValue = new FGA_En_Linea.EvalSubCategoriaService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.EvalSubCategoriaService.AddResponse retVal = ((FGA_En_Linea.EvalSubCategoriaService.IEvalSubCategoriaService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.EvalSubCategoriaService.AddResponse> AddAsync(FGA_En_Linea.EvalSubCategoriaService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(Entities.Entities.Evaluacion.EvalSubCategoria entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Entities.Entities.Evaluacion.EvalSubCategoria entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
