//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.TipoInformeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipoInformeService.IServiceOf_TipoInforme")]
    public interface IServiceOf_TipoInforme {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/GetAll", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/GetAllResponse")]
        FGA.Models.TipoInforme[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/GetAll", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.TipoInforme[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Get", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/GetResponse")]
        FGA.Models.TipoInforme Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Get", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.TipoInforme> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Add", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/AddResponse")]
        FGA_En_Linea.TipoInformeService.AddResponse Add(FGA_En_Linea.TipoInformeService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Add", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.TipoInformeService.AddResponse> AddAsync(FGA_En_Linea.TipoInformeService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Update", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/UpdateResponse")]
        void Update(FGA.Models.TipoInforme entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Update", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.TipoInforme entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Delete", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_TipoInforme/Delete", ReplyAction="http://tempuri.org/IServiceOf_TipoInforme/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.TipoInforme entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.TipoInforme entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.TipoInforme entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.TipoInforme entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_TipoInformeChannel : FGA_En_Linea.TipoInformeService.IServiceOf_TipoInforme, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_TipoInformeClient : System.ServiceModel.ClientBase<FGA_En_Linea.TipoInformeService.IServiceOf_TipoInforme>, FGA_En_Linea.TipoInformeService.IServiceOf_TipoInforme {
        
        public ServiceOf_TipoInformeClient() {
        }
        
        public ServiceOf_TipoInformeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_TipoInformeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_TipoInformeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_TipoInformeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.TipoInforme[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.TipoInforme[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.TipoInforme Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.TipoInforme> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.TipoInformeService.AddResponse FGA_En_Linea.TipoInformeService.IServiceOf_TipoInforme.Add(FGA_En_Linea.TipoInformeService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.TipoInforme entity) {
            FGA_En_Linea.TipoInformeService.AddRequest inValue = new FGA_En_Linea.TipoInformeService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.TipoInformeService.AddResponse retVal = ((FGA_En_Linea.TipoInformeService.IServiceOf_TipoInforme)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.TipoInformeService.AddResponse> AddAsync(FGA_En_Linea.TipoInformeService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.TipoInforme entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.TipoInforme entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
