//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.EntidadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntidadService.IEntidadService")]
    public interface IEntidadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/GetMails", ReplyAction="http://tempuri.org/IEntidadService/GetMailsResponse")]
        string[] GetMails(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/GetMails", ReplyAction="http://tempuri.org/IEntidadService/GetMailsResponse")]
        System.Threading.Tasks.Task<string[]> GetMailsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/GetByIden", ReplyAction="http://tempuri.org/IEntidadService/GetByIdenResponse")]
        FGA.Models.Entidad GetByIden(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/GetByIden", ReplyAction="http://tempuri.org/IEntidadService/GetByIdenResponse")]
        System.Threading.Tasks.Task<FGA.Models.Entidad> GetByIdenAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/GetAll", ReplyAction="http://tempuri.org/IEntidadService/GetAllResponse")]
        FGA.Models.Entidad[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/GetAll", ReplyAction="http://tempuri.org/IEntidadService/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Entidad[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Get", ReplyAction="http://tempuri.org/IEntidadService/GetResponse")]
        FGA.Models.Entidad Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Get", ReplyAction="http://tempuri.org/IEntidadService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Entidad> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Add", ReplyAction="http://tempuri.org/IEntidadService/AddResponse")]
        FGA_En_Linea.EntidadService.AddResponse Add(FGA_En_Linea.EntidadService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Add", ReplyAction="http://tempuri.org/IEntidadService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.EntidadService.AddResponse> AddAsync(FGA_En_Linea.EntidadService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Update", ReplyAction="http://tempuri.org/IEntidadService/UpdateResponse")]
        void Update(FGA.Models.Entidad entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Update", ReplyAction="http://tempuri.org/IEntidadService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Entidad entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Delete", ReplyAction="http://tempuri.org/IEntidadService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntidadService/Delete", ReplyAction="http://tempuri.org/IEntidadService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Entidad entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Entidad entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Entidad entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Entidad entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntidadServiceChannel : FGA_En_Linea.EntidadService.IEntidadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntidadServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.EntidadService.IEntidadService>, FGA_En_Linea.EntidadService.IEntidadService {
        
        public EntidadServiceClient() {
        }
        
        public EntidadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntidadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntidadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetMails(string id) {
            return base.Channel.GetMails(id);
        }
        
        public System.Threading.Tasks.Task<string[]> GetMailsAsync(string id) {
            return base.Channel.GetMailsAsync(id);
        }
        
        public FGA.Models.Entidad GetByIden(string id) {
            return base.Channel.GetByIden(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Entidad> GetByIdenAsync(string id) {
            return base.Channel.GetByIdenAsync(id);
        }
        
        public FGA.Models.Entidad[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Entidad[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Entidad Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Entidad> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.EntidadService.AddResponse FGA_En_Linea.EntidadService.IEntidadService.Add(FGA_En_Linea.EntidadService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Entidad entity) {
            FGA_En_Linea.EntidadService.AddRequest inValue = new FGA_En_Linea.EntidadService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.EntidadService.AddResponse retVal = ((FGA_En_Linea.EntidadService.IEntidadService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.EntidadService.AddResponse> AddAsync(FGA_En_Linea.EntidadService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Entidad entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Entidad entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
