//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.ErrorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorService.IServiceOf_Error")]
    public interface IServiceOf_Error {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Error/GetAllResponse")]
        FGA.Models.Error[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/GetAll", ReplyAction="http://tempuri.org/IServiceOf_Error/GetAllResponse")]
        System.Threading.Tasks.Task<FGA.Models.Error[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Get", ReplyAction="http://tempuri.org/IServiceOf_Error/GetResponse")]
        FGA.Models.Error Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Get", ReplyAction="http://tempuri.org/IServiceOf_Error/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Error> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Add", ReplyAction="http://tempuri.org/IServiceOf_Error/AddResponse")]
        FGA_En_Linea.ErrorService.AddResponse Add(FGA_En_Linea.ErrorService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Add", ReplyAction="http://tempuri.org/IServiceOf_Error/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.ErrorService.AddResponse> AddAsync(FGA_En_Linea.ErrorService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Update", ReplyAction="http://tempuri.org/IServiceOf_Error/UpdateResponse")]
        void Update(FGA.Models.Error entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Update", ReplyAction="http://tempuri.org/IServiceOf_Error/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Error entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Delete", ReplyAction="http://tempuri.org/IServiceOf_Error/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Error/Delete", ReplyAction="http://tempuri.org/IServiceOf_Error/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Error entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Error entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Error entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Error entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_ErrorChannel : FGA_En_Linea.ErrorService.IServiceOf_Error, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_ErrorClient : System.ServiceModel.ClientBase<FGA_En_Linea.ErrorService.IServiceOf_Error>, FGA_En_Linea.ErrorService.IServiceOf_Error {
        
        public ServiceOf_ErrorClient() {
        }
        
        public ServiceOf_ErrorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_ErrorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_ErrorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_ErrorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Error[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Error[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public FGA.Models.Error Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Error> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.ErrorService.AddResponse FGA_En_Linea.ErrorService.IServiceOf_Error.Add(FGA_En_Linea.ErrorService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Error entity) {
            FGA_En_Linea.ErrorService.AddRequest inValue = new FGA_En_Linea.ErrorService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.ErrorService.AddResponse retVal = ((FGA_En_Linea.ErrorService.IServiceOf_Error)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.ErrorService.AddResponse> AddAsync(FGA_En_Linea.ErrorService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Error entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Error entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
