//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA_En_Linea.ProyeccionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProyeccionService.IProyeccionService")]
    public interface IProyeccionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Get", ReplyAction="http://tempuri.org/IProyeccionService/GetResponse")]
        FGA.Models.Proyeccion Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Get", ReplyAction="http://tempuri.org/IProyeccionService/GetResponse")]
        System.Threading.Tasks.Task<FGA.Models.Proyeccion> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Add", ReplyAction="http://tempuri.org/IProyeccionService/AddResponse")]
        FGA_En_Linea.ProyeccionService.AddResponse Add(FGA_En_Linea.ProyeccionService.AddRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Add", ReplyAction="http://tempuri.org/IProyeccionService/AddResponse")]
        System.Threading.Tasks.Task<FGA_En_Linea.ProyeccionService.AddResponse> AddAsync(FGA_En_Linea.ProyeccionService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Update", ReplyAction="http://tempuri.org/IProyeccionService/UpdateResponse")]
        void Update(FGA.Models.Proyeccion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Update", ReplyAction="http://tempuri.org/IProyeccionService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(FGA.Models.Proyeccion entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Delete", ReplyAction="http://tempuri.org/IProyeccionService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Delete", ReplyAction="http://tempuri.org/IProyeccionService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Existe", ReplyAction="http://tempuri.org/IProyeccionService/ExisteResponse")]
        FGA.Models.TipoProyeccion Existe(string IdEntidad, System.DateTime Periodo, string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProyeccionService/Existe", ReplyAction="http://tempuri.org/IProyeccionService/ExisteResponse")]
        System.Threading.Tasks.Task<FGA.Models.TipoProyeccion> ExisteAsync(string IdEntidad, System.DateTime Periodo, string Cuenta);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Proyeccion entity;
        
        public AddRequest() {
        }
        
        public AddRequest(FGA.Models.Proyeccion entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FGA.Models.Proyeccion entity;
        
        public AddResponse() {
        }
        
        public AddResponse(FGA.Models.Proyeccion entity) {
            this.entity = entity;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProyeccionServiceChannel : FGA_En_Linea.ProyeccionService.IProyeccionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProyeccionServiceClient : System.ServiceModel.ClientBase<FGA_En_Linea.ProyeccionService.IProyeccionService>, FGA_En_Linea.ProyeccionService.IProyeccionService {
        
        public ProyeccionServiceClient() {
        }
        
        public ProyeccionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProyeccionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyeccionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyeccionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGA.Models.Proyeccion Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.Proyeccion> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FGA_En_Linea.ProyeccionService.AddResponse FGA_En_Linea.ProyeccionService.IProyeccionService.Add(FGA_En_Linea.ProyeccionService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(ref FGA.Models.Proyeccion entity) {
            FGA_En_Linea.ProyeccionService.AddRequest inValue = new FGA_En_Linea.ProyeccionService.AddRequest();
            inValue.entity = entity;
            FGA_En_Linea.ProyeccionService.AddResponse retVal = ((FGA_En_Linea.ProyeccionService.IProyeccionService)(this)).Add(inValue);
            entity = retVal.entity;
        }
        
        public System.Threading.Tasks.Task<FGA_En_Linea.ProyeccionService.AddResponse> AddAsync(FGA_En_Linea.ProyeccionService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(FGA.Models.Proyeccion entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(FGA.Models.Proyeccion entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public FGA.Models.TipoProyeccion Existe(string IdEntidad, System.DateTime Periodo, string Cuenta) {
            return base.Channel.Existe(IdEntidad, Periodo, Cuenta);
        }
        
        public System.Threading.Tasks.Task<FGA.Models.TipoProyeccion> ExisteAsync(string IdEntidad, System.DateTime Periodo, string Cuenta) {
            return base.Channel.ExisteAsync(IdEntidad, Periodo, Cuenta);
        }
    }
}
